GoogleCloudPlatform/compute-image-tools

daisy/workflow/step_create_disks.go, daisy/workflow/step_create_disks_test.go, daisy/workflow/step_create_images.go, daisy/workflow/step_create_images_test.go, daisy/workflow/step_create_instances.go, daisy/workflow/step_create_instances_test.go, daisy/workflow/step_delete_resources_test.go, daisy/workflow/step_import_disks.go, daisy/workflow/step_wait_for_instances_stopped_test.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
Resource creation steps' Persist field is now NoCleanup.
Workflow.ephemeralName is now Workflow.genName.
=> Added ExactName to resource creation steps. Renamed Persist field. Also renamed ephemeralName.

daisy/compute/compute.go, daisy/workflow/step_wait_for_instances_stopped.go
* VM metadata: all value strings were using the same pointer, setting all the values to the same string.
* step_wait_for_instances_stopped was passing the VM selfLink as the VM name.
=> Bug fixes: VM metadata and step_wait_for_instances_stopped

daisy/workflow/step_create_disks.go, daisy/workflow/step_create_images.go, daisy/workflow/step_create_instances.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
Added get*() methods and a test for them. Resources are queried at the local workflow level, then the parent, then grandparent, etc.
=> Hierarchical resource references. 

daisy/workflow/common.go, daisy/workflow/common_test.go, daisy/workflow/validate.go, daisy/workflow/validate_test.go
Unsubbed var checking. Moved traversal logic out of substitute(). Reused logic to traverse workflow data again looking for unsubbed vars.
=> Unsubbed var checking.

daisy/daisy.go, daisy/workflow/common.go, daisy/workflow/common_test.go, daisy/workflow/sources.go, daisy/workflow/step_create_disks_test.go, daisy/workflow/step_create_images.go, daisy/workflow/step_create_images_test.go, daisy/workflow/step_create_instances.go, daisy/workflow/step_create_instances_test.go, daisy/workflow/validate.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
- Resolve SourceFile in CreateDisks
- SourceFile can be either GCS path or a file reference from sources.
- Test cleanups
- Change FromFile to NewFromFile
- Allow for storage and compute endpoint overrides
=> Resolve SourceFile in CreateDisks and some cleanups/TODOs

daisy/workflow/common.go, daisy/workflow/sources.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
ensure gcs objects don't contain '\' (the case when windows paths get translated to GCS objects)
add timestamp to scratchpath
=> Ensure gcs objects don't contain '\', add timestamp to scratchpath

daisy/workflow/sources_test.go, daisy/workflow/workflow.go
SubWorkflows weren't cleaning up if they were running when the root workflow exits from another step failing. Also was happening if the SubWorkflow step times out.
Added a redundant backstop Subworkflow cleanup() call in the parent workflows' cleanup().
Also, fixed TestUploadSources on Windows.
=> Fixed SubWorkflow cleanup issue.

daisy/README.md, daisy/workflow/step_create_instances.go
Documentation for:
CreateInstances, DeleteResources, SubWorkflow, and WaitForInstancesSignal.
Also, removed logic on startup-script-url vs windows-startup-script-url. I think we need to find a better way to determine if a VM is Windows. Until then, I'm copying the script url into both.
=> README for rest of step types and a startup script fix.

daisy/compute/compute.go, daisy/daisy.go, daisy/workflow/step_create_disks.go, daisy/workflow/step_create_images.go, daisy/workflow/step_create_instances.go, daisy/workflow/step_sub_workflow.go, daisy/workflow/step_wait_for_instances_signal.go, daisy/workflow/step_wait_for_instances_signal_test.go, daisy/workflow/test.workflow, daisy/workflow/test_common.go, daisy/workflow/test_sub.workflow, daisy/workflow/validate.go, daisy/workflow/validate_test.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
WaitForInstancesSignal doesn't error when instance is stopped or stopping
Add tests for WaitForInstancesSignal
Fixed bug on subworkflow failure not ending workflow
Don't log errors after a workflow is canceled
Subworkflows are named after their step name
=> Clean up cleanup on cancel, validate step and workflow names

daisy/README.md, daisy/daisy.go, daisy/workflow/sources_test.go, daisy/workflow/test.workflow, daisy/workflow/validate.go, daisy/workflow/validate_test.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
Vars can now be marked as required and have a description while still allowing for the old var style:
"Vars": {
"some-normal-var": "some-string"
"some-required-var": {"Required": true, "Description": "this is a description"}
}
Fix logging for subworkflows
=> Modify how vars are parsed to allow for additional fields

daisy/step_create_instances.go, daisy/step_wait_for_instances_signal.go, daisy/step_wait_for_instances_signal_test.go
Increase logSerialOutput interval from 1s to 5s
Increase default WaitForInstanceSignal interval from 5s to 10s
For normal workflows (WaitForInstanceSignal checking serial port and stopped status) this raises the number of concurrent instances from ~14 to ~50 while staying below 2000 QPS per 100s
=> Reduce QPS to compute API

daisy/common.go, daisy/compute/compute.go, daisy/daisy/daisy.go, daisy/daisy/daisy_test.go, daisy/workflow.go, daisy/workflow_test.go
Any arguments passed to daisy in the format -var:<text> will be parsed as flags and then passed to workflows as Vars.
For example to pass the var 'myVar' with value 'myValue' you use the flag -var:myVar=myValue
=> Allow workflow variables to be set using flags to daisy

daisy/README.md
#118 moved the `main` package from github.com/GoogleCloudPlatform/compute-image-tools/daisy to github.com/GoogleCloudPlatform/compute-image-tools/daisy/daisy this change updates the README.md build from source instructions to reflect the new path.
=> Update README.md to reflect new path to main package

daisy_workflows/import_userguide.md
Fix import user guide by removing one "--scopes" from the example
command when configuring permissions for Daisy
=> Remove double --scopes option in import_userguide.md

daisy/common.go, daisy/common_test.go, daisy/step_copy_gcs_objects.go, daisy/step_copy_gcs_objects_test.go, daisy/storage.go, daisy/storage_test.go, daisy/test_common_test.go
Populate function ensures Role is uppercase
Validate function checks:
- read access to source 
- write access to destination
- ACLRule.Entity is not empty
- ACLRule.Entity can actually be used
- ACLRule.Role matches a known value
Reorganize GCS specific code.
=> Apply GCS ACLs on a recursive copy, add populate and validate for CopyGCSObjects

daisy/step_copy_gcs_objects.go, daisy/step_copy_gcs_objects_test.go, daisy/storage.go
Multiple steps can have the same name (like inside an IncludeWorkflow)
=> Globally lock during GCS validation

daisy/README.md, daisy/step_wait_for_instances_signal.go, daisy/step_wait_for_instances_signal_test.go
Serial output matching FailureMatch, SuccessMatch or StatusMatch will log for easier debugging.
=> Add StatusMatch to WaitForInstancesSignal

daisy_workflows/image_import/enterprise_linux/translate_el.py, daisy_workflows/image_import/ubuntu/translate_ubuntu.py
The libguestfs framework already copies the resolv.conf when network
option is set. Copying the /etc/resolv.conf file from the host is not
necessary.
=> translate: remove unecessary overwrite of resolv.conf

daisy/compute/compute.go, daisy/compute/test_client.go, daisy/compute/test_client_test.go, daisy/disk.go, daisy/image.go, daisy/instance.go, daisy/machinetype.go, daisy/project.go, daisy/resources.go, daisy/resources_test.go, daisy/step_create_disks.go, daisy/step_create_disks_test.go, daisy/step_create_images.go, daisy/step_create_images_test.go, daisy/step_create_instances.go, daisy/step_create_instances_test.go, daisy/step_includeworkflow_test.go, daisy/step_wait_for_instances_signal_test.go, daisy/test_common_test.go, daisy/zone.go
Checks for dependency existence of any non workflow created resources
Checks for naming collisions of workflow created resources
Lookups are cached to limit the amount of API calls needed.
=> Add additional checks for resources existing in GCE

daisy_workflows/image_import/enterprise_linux/translate_el.py, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_licensed.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json
RHEL licensed doesn't use Debian as host for the translation to allow
the system to download the google-rhui-client-rhel package.
Fix the bash script to install the dependencies using yum if available
and also fix the package installation process of the rhui.
=> translate_el: Fix translation of RHEL licensed

daisy_workflows/image_import/enterprise_linux/translate_el.py, daisy_workflows/image_import/ubuntu/translate_ubuntu.py
- It fails in 14.04 for one mount point that ultimately doesn't matter.
=> Allow for unmount to fail in Ubuntu translations.

daisy_workflows/image_build/enterprise_linux/build_installer.py, daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/co7-post.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/ol7-post.cfg
On EL7-based distros, Anaconda writes /var/log/anaconda and /root/*-ks.cfg
*after* all of the postinstall kickstart scripts have run. This means it's
not possible to remove all of these logs in a postinstall script. Instead,
the inst.nosave=all kernel param triggers it to avoid saving logs.
This change enables this parameter by default and adds an el_savelogs
option to the workflows to disable this for debugging purposes.
The relevant postinstall scripts are also fixed to remove the now unnecessary
cleanup.
=> Clean up for Anaconda log saving on *EL7.

daisy_workflows/image_import/linux_common/utils.py
libguestfs limits the memory to 500MB, this was causing the post install
script from google-compute-engine-oslogin package to run out of memory.
Increasing it to 4G solves the problem.
=> image_import: increase libguestfs memory to 4G

daisy_workflows/image_import/enterprise_linux/translate.py
Restore selinux labels after the entire operation.
This is necessary after instaling package google-compute-engine-oslogin
as it installs a new selinux module.
This fixes the followin issues:
- Centos 7: useradd was unable to access ld.so.cache, making the image
unable to create new users
- Centos 6: the link to libaudit.so.1 was not defined, making the image
unable to login
=> image_import: el: restore selinux labels

daisy_workflows/image_build/enterprise_linux/centos_6.wf.json, daisy_workflows/image_build/enterprise_linux/centos_7.wf.json, daisy_workflows/image_build/enterprise_linux/oraclelinux.wf.json, daisy_workflows/image_build/enterprise_linux/oraclelinux6.wf.json, daisy_workflows/image_build/enterprise_linux/oraclelinux7.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_6.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_6_byol.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_7.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_7_byol.wf.json
Only create the image (faster).
Change default dates to use UTC timestamp for uniqueness.
=> Remove export from enterprise_linux workflows.

daisy_workflows/e2e_tests/scripts/post_translate_test.sh
Centos 6 uses initctl for the google-compute-engine scripts. Update the tests
to check accordinly
=> e2e_tests: use initctl for upstart scripts

daisy_workflows/image_build/enterprise_linux/README.md, daisy_workflows/image_build/enterprise_linux/oraclelinux.wf.json, daisy_workflows/image_build/enterprise_linux/oraclelinux6.wf.json, daisy_workflows/image_build/enterprise_linux/oraclelinux7.wf.json
This variable isn't used for anything important and just results in one more
thing to specify when building an Oracle Linux image.
=> image_build: Remove minor version var from Oracle Linux workflows.

daisy_workflows/e2e_tests/scripts/post_translate_test.sh
Attempt to deflake connection tests by moving them further out.
=> Linux translate test failures return more useful errors.

daisy/README.md, docs/daisy-installation-usage.md, docs/daisy.md
Also copy "What is Daisy?" content to root Daisy docs page.
=> Move installation and usage instructions into their own page in docs

daisy_workflows/image_import/debian/translate.py
sdk post script is working again, use apt to install it instead of
skiping the post install script with dpkg
=> image_import: debian: install sdk with apt

cli_tools/gce_inventory_agent/main.go, cli_tools/instance_inventory/main.go, packages/packages_linux.go
gce_inventory_agent gathers and writes instance inventory to guest attributes.
instance_inventory pretty prints out an instances inventory data, this is mainly meant to be used as a testing tool during the POC phase.
=> Add gce_inventory_agent and instance_inventory binaries.

daisy_workflows/README.md, daisy_workflows/import_userguide.md
Looks like we renamed a file and didn't catch all the links to it.
=> fix broken links

cli_tools/gce_image_publish/main.go, cli_tools/gce_image_publish/main_test.go, daisy/step_deprecate_images.go, daisy/step_deprecate_images_test.go, daisy/step_includeworkflow_test.go, daisy/step_sub_workflow.go, daisy/step_sub_workflow_test.go, daisy/workflow.go, daisy/workflow_test.go
This is a preliminary commit so that I can get feedback on anything I may be missing. From my testing this works as expected for publish and rollback of images (at least the same as our current tool).
Docs and additional unit tests still need to be written.
The idea is you write a publish template json file and point this tool at that, the template contains all the options you need to publish a set of images. Source images can be either a GCS image file or a GCE image, a daisy workflow is generated for the publish task.
=> Initial commit of the gce_image_publish tool

cli_tools/gce_image_publish/main.go, daisy/compute/compute.go, daisy/workflow.go
Make PopulateClients public in order to use the same compute and storage clients from calling code.
=>  Cache image lists per project for publish tool

cli_tools/gce_image_publish/main.go
The publish tool now takes the same -var: flags as daisy
Publish templates are run through text/template with the varMap created from the -var: flags as the data sctructure
=> Add text/template parsing to publish tool

daisy/common_test.go, daisy/disk.go, daisy/disk_test.go, daisy/error_test.go, daisy/image.go, daisy/image_test.go, daisy/instance.go, daisy/instance_test.go, daisy/resource_registry.go, daisy/resource_registry_test.go, daisy/resource_test.go, daisy/step_copy_gcs_objects_test.go, daisy/step_create_disks.go, daisy/step_create_disks_test.go, daisy/step_create_images.go, daisy/step_create_images_test.go, daisy/step_create_instances.go, daisy/step_create_instances_test.go, daisy/step_delete_resources.go, daisy/step_delete_resources_test.go, daisy/step_deprecate_images.go, daisy/step_deprecate_images_test.go, daisy/step_includeworkflow_test.go, daisy/step_wait_for_instances_signal.go, daisy/step_wait_for_instances_signal_test.go, daisy/test_common_test.go, daisy/validate_test.go, daisy/workflow.go, daisy/workflow_test.go
- Moved registries into Workflow.
- Changed the way disk registry's disk attachments are indexed (uses string instead of *Resource now)
- Added depth arg to diff().
- Fixed a couple go vet errors.
=> Daisy: moving resource registries into Workflow struct.

daisy/disk_test.go, daisy/error.go, daisy/image.go, daisy/resource_registry.go, daisy/step_delete_resources.go, daisy/step_delete_resources_test.go, daisy/test_common_test.go
Images in state of OBSOLETE or DELETED still exist and should be added to the registry
This allows DeleteResources to delete images in this state
=> Images in state of OBSOLETE or DELETED still exist, use new typed error

docs/image-import.md
When I view this page, https://googlecloudplatform.github.io/compute-image-tools/image-import.html#compatibility-and-known-limitations , the tables for "Windows" and "Linux" in the "Compatibility and Known Limitations" section are not appearing as tables. They appear as a long string of text, which is difficult to read.
Perhaps it is because "There must be at least 3 dashes separating each header cell" (from https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables).
=> Update tables to make them render properly

daisy_workflows/e2e_tests/README.md, daisy_workflows/e2e_tests/scripts/retrieve-files-from-gcs.sh, daisy_workflows/image_build/debian/debian.wf.json, daisy_workflows/image_build/debian/debian_8.wf.json, daisy_workflows/image_build/debian/debian_9.wf.json
This fixes an issue with how the filesystem is being created on the
resulting image. The e2fs version in Debian 8 does not support
metadata_checksums. If the partition is created from a Debian 9 e2fs
toolset, fsck will fail on Debian 8 boots.
systemd-fsck[121]: /dev/sda1 has unsupported feature(s): metadata_csum
=> Use the same builder image for Debian image builds.

daisy_workflows/image_import/debian/translate_debian_9.wf.json
```
[Daisy] Errors in one or more workflows:
import-and-translate: step "translate" validation error: Dependencies reference non existent step "setup-disk": "translate-disk":["setup-disk"]
```
I missed something when I re-did all the workflows last week.
=> fix Debian 9 translation workflow

daisy_workflows/image_import/import_from_image.wf.json, docs/daisy-workflow-config-spec.md
After redoing all our image_import workflows, all the translation workflows now take a disk rather than an image as a starting point. This breaks image-from-image translation. This workflow acts as a wrapper to enable that behaviour again.
=> Add import from image workflow

cli_tools/daisy/main.go, cli_tools/daisy/main_test.go, daisy/logger.go, daisy/logger_test.go, daisy/sources_test.go, daisy/step.go, daisy/step_attach_disks.go, daisy/step_create_disks.go, daisy/step_create_images.go, daisy/step_create_instances.go, daisy/step_create_instances_test.go, daisy/step_create_networks.go, daisy/step_create_networks_test.go, daisy/step_delete_resources.go, daisy/step_deprecate_images.go, daisy/step_includeworkflow.go, daisy/step_includeworkflow_test.go, daisy/step_sub_workflow.go, daisy/step_wait_for_instances_signal.go, daisy/test_common_test.go, daisy/validate_test.go, daisy/workflow.go, daisy/workflow_test.go
Add Cloud Logging support to daisy.
- Cloud Logging is the default.
- Logs will go to GCS when specified by the flag or when CloudLogging
is unavailable.
- Removes stdout logging unless specified by a flag.
- This was undesirable when running via gcloud.
- Cloud logs are structured JSON logs.
- Stdout and GCS logs are still strings for compatibility. However, the timestamp now contains timezone.
Cloud Logs example
=> Add basic Cloud Logging support.

daisy_workflows/e2e_tests/scripts/run_daisy_and_check_logs.sh, daisy_workflows/e2e_tests/validate_cloud_logging.wf.json, test-infra/prowjobs/daisy-e2e/run/__main__.py
These tests are a new workflow tat checks that logs work when enabled and don't when there is no permission.
The tests work by creating instances with a startup script. The startup script downloads Daisy from Github, compiles it, and executes against `attach_disks.wf.json` which is a simple workflow. One instance service account has logWrite permission and the other does not.
Prow test execution includes Github repo args for the PR to include in the WF so the WF tests the version of Daisy in the PR and not the version in `master`
=> Daisy Cloud Logging integration tests

daisy_workflows/image_test/boot/boot.sh, daisy_workflows/image_test/boot/boot.wf.json
image_test: boot: remove gsutil dependency
Use SOURCE to copy the script to startup-script parameter instead of
relying in gsutil to download the script
image_test: boot: improve portability
Use /bin/sh instead of bash
Remove the use of [[ -f file ]] (it is not supported by csh, causing
problems to FreeBSD)
Use a fix path for the reboot file instead of using relative home path
=> image_test: boot: improve portability

daisy_workflows/image_test/boot/boot.wf.json, daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json, daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
Use default image size instead.
Fix issue when testing FreeBSD images that use a size of 32Gb instead of
10Gb.
=> image_test: remove SizeGb from workflows

daisy/logger.go, daisy/logger_test.go, daisy/step_create_instances.go
- Fixes bug where we would try to send serial logs to the cloud when cloud logging is disabled (985dd16)
- Refactor to move serial logging logic into logger and add basic sanity tests (395b1dc).
=> Fix bug in sending serial logs to Cloud and refactor

daisy_workflows/image_test/linux_common/bootstrap.py, daisy_workflows/image_test/linux_common/utils.py, daisy_workflows/image_test/metadata-ssh/metadata-ssh-tester.py, daisy_workflows/image_test/oslogin-ssh/oslogin-ssh-master-tester.py
There is no /usr/bin/python in FreeBSD,
Without this fix, the configuration test is not executed
=> image_test: fix python shebang for FreeBSD

daisy/compute/compute.go, daisy/compute/compute_test.go, daisy/compute/test_client.go, daisy/compute/test_client_test.go, daisy/instance.go, daisy/resource.go, daisy/resource_registry.go, daisy/resource_registry_test.go, daisy/step.go, daisy/step_stop_instances.go, daisy/step_stop_instances_test.go, daisy/step_test.go, docs/daisy-workflow-config-spec.md
Step to stop an instance without deleting it.
The StopStep is similar to DeleteResources for instances, but allow
adding WaitForInstanceSignal without making it a dependency to the
Delete step.
Depend on #396
=> daisy: Add StopStep

daisy/workflow.go
Fix regressing introduced by #403
Don't check w.Sources before calling uploadSources, this funcions
already deals with empty sources and also upload sources from
subworkflows
=> daisy: fix uploading sources from subworkflows

daisy_workflows/image_test/configuration/configuration.wf.json, daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json, daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
The RealName of a resource is composed by the name of the parent
workflows, but the genName function truncates it if too big, and it
can do a different truncation per resource, which means that using
FULLNAME variable is not reliable to deduce the RealName of the
resources.
It becomes a problem when we have several subworkflows where the
RealName of the resources are bigger, which breaks usages like the
oslogin test, where we need to pass the RealName of an instance
to another using metadata.
=> image_test: replace FULLNAME by RealName

test-infra/prow/config.yaml
Add the following in the image test infrastructure:
* projects/freebsd-org-cloud-dev/global/images/family/freebsd-11-2,\
* projects/freebsd-org-cloud-dev/global/images/family/freebsd-12-0-snap"
=> prow: add FreeBSD 11-2 and 12-0-snap in image test

daisy_workflows/image_test/multi-nic/multi_nic.wf.json
Note: for some reason the internal DNS server (metadata.google.internal)
is not registering the hostname from the secondary NIC so this test only
works if the common subnetwork is setup on the primary NIC.
=> Multi NIC integration test

daisy_workflows/image_test/boot/boot.sh, daisy_workflows/image_test/boot/boot.wf.json, daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json, daisy_workflows/image_test/multi-nic/multi_nic.wf.json, daisy_workflows/image_test/network/network-testee.sh, daisy_workflows/image_test/network/network.wf.json, daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
Use logger instead of writting to /dev/console directly
Also, in the boot test, wait a bit before restarting so logger can flush
the messages.
=> image_test: fix race condition on /dev/console

daisy/step_create_instances.go
When a machine was on "STOPPING" status, the SerialOutput would
eventually throw the warning `googleapi: Error 503: TIMEOUT,
backendError`, which is not really helpful as it's expected that the
SerialOutput will be closed soon.
By considering the "STOPPING" instance status an expected reason for
having the serial output closed, this warning is suppressed.
=> Fix StopInstances serial output log

daisy_workflows/linux_common/utils.py
Wait setMetadata operation to finish and raise an exception in case of
an error in the result.
Some times the operation returns with an error and this was being
ignored. Using the Wait function throws an exception in case of an
error returned in the operation.
Closes #414
=> image_test: utils: wait setMetadata operation

daisy_workflows/image_build/debian/build.py, daisy_workflows/image_build/enterprise_linux/build_installer.py, daisy_workflows/image_build/enterprise_linux/ks_helpers.py, daisy_workflows/image_build/enterprise_linux/save_logs.py, daisy_workflows/image_import/debian/translate.py, daisy_workflows/image_test/disk/disk-tester.py, daisy_workflows/image_test/network/network-tester.py, daisy_workflows/linux_common/bootstrap.py, daisy_workflows/linux_common/utils.py
Standarize logs by setting the formats for every logging level in the
root logger.
As a consequance, this fixes the following bug when calling the
wrappers:
```
Traceback (most recent call last):
File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
msg = self.format(record)
File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
return fmt.format(record)
File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
record.message = record.getMessage()
File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file utils.py, line 51
```
=> daisy_workflows: use logging instead of wrappers

daisy_workflows/image_test/metadata-script/metadata-script-integrity.subwf.json, daisy_workflows/image_test/metadata-script/metadata-script-junk.subwf.json, daisy_workflows/image_test/metadata-script/metadata-script-linux.wf.json, daisy_workflows/image_test/metadata-script/metadata-script-noscript.subwf.json, daisy_workflows/image_test/metadata-script/metadata-script-subwf/sub-create-instance-no-metadata.subwf.json, daisy_workflows/image_test/metadata-script/metadata-script-subwf/sub-create-instance-no-scope.subwf.json, daisy_workflows/image_test/metadata-script/metadata-script-subwf/sub-startup-shutdown-check.subwf.json, daisy_workflows/image_test/metadata-script/metadata-script-test-shutdown-hash.sh, daisy_workflows/image_test/metadata-script/metadata-script-test-startup-hash.sh, daisy_workflows/image_test/metadata-script/metadata-script-windows.wf.json, daisy_workflows/image_test/metadata-script/metadata-script.subwf.json
I improved the architecture in order to allow several startup-script
flavors: GCS download (authenticated and unauthenticated), URL download
and directly from metadata.
Note: Sometimes the shutdown-script messages are not printed. I noticed
it specially when there is no shutdown-script to execute (on this case,
it should print something like "shutdown-script: INFO No shutdown
scripts found in metadata.").
=> metadata-scripts: improve script download testing

daisy_workflows/image_test/boot/boot.bat, daisy_workflows/image_test/boot/boot.sh, daisy_workflows/image_test/boot/boot.wf.json
Fast instances could manage to print the boot message and restart
without daisy noticing it. When that happend, only the "REBOOT" was
caught but before a "BOOT", which led to a test filure by timeout.
This patch used daisy to control the rebooting which should make this
behavior not happening anymore.
=> Avoid rebooting on boot test without catching output

daisy_workflows/image_test/configuration/debian.py, daisy_workflows/image_test/configuration/redhat.py
The repository server is not as reliable as one can assume. For that
reason it worths to retry connecting to it when it doesn't work at the
first time.
=> Configuration test: retry apt/yum network operations

daisy_workflows/image_test/oslogin-ssh/README.md, daisy_workflows/linux_common/utils.py
The old method was stacking a '\n' at the ssh-keys metadata list when it
was removing the last key (it could clear a '\n' at the end at removal,
but only after removing, the new list had a '\n' at the end).
This fix will avoid the project metadata being overwhelmed by empty keys
after several runs and it will even clear them, if it happens again.
=>  oslogin-ssh test: Avoid empty ssh-keys inclusion 

daisy_workflows/image_test/boot/boot.sh, daisy_workflows/image_test/linux_images.test.gotmpl
Boot test could fail as the "BOOTED" message was overwritten by other
boot messages on rsyslog (race condition). Adding a 10s sleep should
avoid this kind of issue
Disk and multi-nic tests uses a lot of a project quota for testing
several images. As the bottle necks for completing the tests are the
oslogin tests, running disk/multi-nic tests one at a time will not
impact total time for the tests run, but will require a lower resource
quota.
=> Reduce boot, disk and multi-nic test conflicts

test-infra/prow/config.yaml
FreeBSD 12.0 is on its release cycle and their alpha releases are being
released under freebsd-12-0 image-family and the freebsd-12-0-snap is
deprecated until the release comes up.
=> prow: Test most recent FreeBSD-12-0 images

image_test/metadata-script/shutdown-script-integrity.wf.json, image_test/metadata-script/shutdown-script-junk.wf.json, image_test/metadata-script/startup-script-integrity.wf.json, image_test/metadata-script/startup-script-junk.wf.json, image_test/metadata-script/sysprep-script-integrity.wf.json, image_test/metadata-script/sysprep-script-junk.wf.json
After moving image_test out of daisy_workflow directory, this URLs
should have been updated.
=> Fix metadata-scripts URLs

image_test/configuration/linux/generic_distro.py
I guess this issue has not been noticed before as all distros that we
currently test have a gcloud/gsutil command (google-cloud-sdk package).
But that's not a requirement so without this patch, it'd as an
unexpected exception would be thrown.
This was possibly not happening before when subprocess.check_call or
subprocess.check_output was being used on utils.Execute.
=> Fix configuration's gcloud test: OSError was raised when not found

test-infra/prow/config.yaml
The Google Compute Agent was updated on FreeBSD 11.2 but prow was only testing
the release image. Tests should be focusing on the latest builds.
=> Use latest FreeBSD 11.2 images on prow tests

cli_tools/osconfig_agent/patch_window.go, cli_tools/osconfig_agent/patch_window_test.go
Add support for RunOnce patch windows. 
If the window has already expired, which it shouldn't have, an error is returned. If the window already started, the start time will be the actual start time and the agent should begin executing the patch when as soon as it is ready.
=> OS Config Patch Window RunOnce support

image_test/metadata-script/metadata-script-inc/shutdown-check.wf.json, image_test/metadata-script/metadata-script-test-shutdown-hash.sh, image_test/metadata-script/shutdown-script-integrity.wf.json, image_test/metadata-script/shutdown-script-junk.wf.json, image_test/metadata-script/shutdown-script-linux.wf.json, image_test/metadata-script/shutdown-script-noscript.wf.json, image_test/metadata-script/shutdown-script-windows.wf.json, image_test/metadata-script/shutdown-script.wf.json, image_test/metadata-script/startup-script-for-shutdown-tests.ps1, image_test/metadata-script/startup-script-for-shutdown-tests.sh
These tests were not reliable because some times the instance powered off
before the logs had been processed. Now, we delayed a bit the instance
shutdown and the tests start to watch the serial output before the
shutdown process starts.
Besides that we add some small fixes related to FreeBSD.
=> Refactor shutdown image tests

image_test/metadata-script/shutdown-script-integrity.wf.json, image_test/metadata-script/shutdown-script-junk.wf.json, image_test/metadata-script/shutdown-script-noscript.wf.json
The startup scripts have the same name in all shutdown tests,
and when they are included in the same workflow we got an error
trying to populate it.
=> Fix source name conflicts in shutdown image tests

daisy_workflows/image_import/debian/translate.py, daisy_workflows/image_import/enterprise_linux/translate.py, daisy_workflows/image_import/suse/translate.py, daisy_workflows/image_import/ubuntu/translate.py, daisy_workflows/linux_common/utils/__init__.py
Fix a regression added by fef17d7d6ca556fbe20ca078f98bbcb2bd5f81e0
In configuration image tests we import utils.py and after this commit,
it also imports diskutils.py. This script is trying to install
python-guestfs using apt in all distributions even in non-Debian based
and leading it to a failure.
You can check these failures in [testgrid](https://k8s-testgrid.appspot.com/google-gce-compute-image-tools#linux-image-tests&width=20).
=> Import diskutils.py only where is needed

daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
Also clarify Windows version vs. Docker version in the script.
Tested:
```
time ~/go/bin/daisy -project <project> -zone us-west1-b \
daisy_workflows/image_build/windows_for_containers/windows-1803-for-containers.wf.json
```
I booted the resulting image and verified:
```
C:\Users\pjh>docker version
Client:
Version:           18.09.0
API version:       1.39
Go version:        go1.10.3
Git commit:        33a45cd0a2
Built:             unknown-buildtime
OS/Arch:           windows/amd64
Experimental:      false
Server:
Engine:
Version:          18.09.0
API version:      1.39 (minimum version 1.24)
Go version:       go1.10.3
Git commit:       33a45cd0a2
Built:            11/07/2018 00:24:12
OS/Arch:          windows/amd64
Experimental:     false
```
=> Install Docker EE 18.09 in windows_for_containers workflow.

daisy_workflows/linux_common/utils/common.py
Add / to the end of blob_path before the concatenation with filename if
the input does not end with it.
Thank Roman Fuentes for the report.
=> utils: improve UploadFile function

image_test/multi-nic/multi-nic-master.sh
This will fix some test failures in the test grid.
=> image_test/multi-nic: install ping in Ubuntu minimal images

image_test/configuration/linux/redhat.py
When verifying if a package is installed or not, the command
'yum --assumeno install package_name' returns 1 insetad of 0 if there is an
update to the package available, even if the package is installed, causing the
test to fail.
This patch replaces this commad by 'yum list installed package_name'.
=> Fix configuration test for centos/rhel

daisy_workflows/linux_common/utils/common.py, image_test/metadata-ssh/metadata-ssh-tester.py
Add a new test case for metadata-ssh, seems that this was an issue in the past.
=> metadata-ssh: test root privileges after re-add ssh key

daisy_workflows/image_import/windows/translate.ps1
OBSERVED
Windows 7 image translate (import) fails, providing the error:
At C:\Windows\TEMP\metadata-scripts128481719\windows-startup-script-url.ps1:30 
char:11
+   $out = & <<<< $executable $arguments 2>&1 | Out-String
TranslateFailed: Hibernation failed with the following error: The request is not supported.
EXPECTED
Translate completes with no errors.
=> image_import: 7 does not support disabling hibernate

daisy_integration_tests/7_translate.wf.json
* Test VM did not have BYOL set in metadata, test failed b/c 7 was not
activated
OBSERVED:
-  7 image translate: step "wait-for-test-instance" run error: WaitForInstancesSignal FailureMatch found for "inst-import-test-windows-7-translate-test-sslvj": "Test Failed: Windows is not activated"
EXPECTED:
Test passes.
=> daisy_integration_tests: 7 translate import

image_test/metadata-script/metadata-script-inc/wait-message.wf.json
Stop the test if we detect an error from the google_metadata_script_runner
=> image_test: catch metadata script runner failure

daisy_workflows/linux_common/utils/common.py
The raise statement without argument only works insice the except block.
If called outside it, we need to save the exception.
This fixes the error message: "No active exception to reraise"
=> linux_common: raise pending exception

image_test/disk/disk-testee.sh
Sending messages to logger might flood the buffer and make it drop some
messages.
Increase the delay before printing again.
=> image_test: disk: don't flood logger

cli_tools/google-osconfig-agent/google-osconfig-agent.conf, cli_tools/google-osconfig-agent/google-osconfig-agent.service, cli_tools/google-osconfig-agent/packaging/debian/control, cli_tools/google-osconfig-agent/packaging/debian/rules, cli_tools/google-osconfig-agent/packaging/google-osconfig-agent.spec, cli_tools/google-osconfig-agent/packaging/setup_deb.sh, cli_tools/google-osconfig-agent/packaging/setup_rpm.sh
OSConfig changes:
* Build RPM packages for CentOS/RHEL 6/7
* Include upstart (CentOS/RHEL 6) and systemd scripts
* Don't enable or start service by default
Debian contents:
```
find /tmp/debpackage/ -iname '*.deb' -ls -exec dpkg-deb -I '{}' \; -exec dpkg-deb -c '{}' \;
2158   2840 -rw-r--r--   1 liamh    liamh     2905346 Jan  3 00:23 /tmp/debpackage/google-osconfig-agent_0.4.1-1_amd64.deb
new debian package, version 2.0.
size 2905346 bytes: control archive=681 bytes.
330 bytes,    11 lines      control              
317 bytes,     4 lines      md5sums              
185 bytes,     7 lines   *  postrm               #!/bin/sh
Package: google-osconfig-agent
Version: 0.4.1-1
Architecture: amd64
Maintainer: Google Cloud Team <gc-team@google.com>
Installed-Size: 10415
Depends: libc6 (>= 2.3.2) …
```
=> OSConfig packaging rpm and init scripts

image_test/metadata-script/shutdown-script-linux.wf.json, image_test/metadata-script/startup-script-linux.wf.json
Using journald a number is added to the log message after the name of
the daemon, and this number varies depending on the order of daemons
execution. So the daemon name was removed from the expected message.
=> image_test/metadata-script: update the expected messages

daisy_workflows/image_build/windows_for_containers/container_image_install.ps1, daisy_workflows/image_build/windows_for_containers/windows-1803-for-containers.wf.json, daisy_workflows/image_build/windows_for_containers/windows-1809-for-containers.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-for-containers.wf.json
Microsoft made several changes to the naming and location of their base
Windows containers with the release of Windows Server 2019 and 1809.
This change adds workflow files for Windows Server 2019 and 1809 and
updates the container image installation script to accommodate the
version differences.
====Tested:====
time ~/go/bin/daisy -project PROJECT -zone us-west1-b daisy_workflows/image_build/windows_for_containers/windows-1709-for-containers.wf.json
time ~/go/bin/daisy -project PROJECT -zone us-west1-b daisy_workflows/image_build/windows_for_containers/windows-1803-for-containers.wf.json
time ~/go/bin/daisy -project PROJECT -zone us-west1-b daisy_workflows/image_build/windows_for_containers/windows-1809-for-containers.wf.json
time ~/go/bin/daisy -project PROJECT -zone us-west1-b …
=> Update container image workflow for Windows Server 2019 and 1809.

cli_tools/google-osconfig-agent/config/config.go, cli_tools/google-osconfig-agent/logger/logger.go, cli_tools/google-osconfig-agent/main.go, cli_tools/google-osconfig-agent/packaging/common.sh, cli_tools/google-osconfig-agent/packaging/debian/changelog, cli_tools/google-osconfig-agent/packaging/debian/control, cli_tools/google-osconfig-agent/packaging/debian/google-osconfig-agent.lintian-overrides, cli_tools/google-osconfig-agent/packaging/debian/rules, cli_tools/google-osconfig-agent/packaging/googet/build.sh, cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec, cli_tools/google-osconfig-agent/packaging/google-osconfig-agent.spec, cli_tools/google-osconfig-agent/packaging/setup_deb.sh, cli_tools/google-osconfig-agent/packaging/setup_goo.sh, cli_tools/google-osconfig-agent/packaging/setup_rpm.sh
Add windows build script
Add version info to build
Don't use cgo (use Go resolver, not cgo)
Move common build commands to common function
=> osconfig_agent: update build scripts, add version info

cli_tools/google-osconfig-agent/service/service.go, osconfig_tests/main.go, osconfig_tests/osconfig_server/osconfig_service_wrapper.go, osconfig_tests/test_suites/package_management/package_management.go
* Add a wrapper for osconfig service
* added a test case to create OsConfig, list and then delete the osconfig. This is just a sample test case to test the setup and osconfig service APIs. Tests around actual customer use cases to follow
=> Add e2e test structure for package management

image_test/metadata-script/metadata-script-inc/create-instance-no-scope.wf.json
Daisy adds default service account which doesn't seem to work well when
no scopes are set.
If no scopes are set but a service account is set, the instance can't
read public gcs files.
Fixes #622
=> image_test: Fix metadata-script with empty ServiceAccount

osconfig_tests/test_suites/package_management/package_management.go
Names must be lowercase and follow RFC 1035 naming convention.
=> Fix invalid name of test OsConfig

osconfig_tests/main.go
As per gubernator documentation, the optional artifacts should be of the format junit_*.xml.
without this, the testgrid dashboard does not show the cells for individual tests.
manually tested in test-grid
=> Fix test grid ui for osconfig tests

cli_tools/google-osconfig-agent/patch/patch_run.go, cli_tools/google-osconfig-agent/patch/watcher.go
- We can't wait on the metadata key since it might not exist
- Watch on the attributes instead of keep track of changes
=> Fix patch notification watcher

test-infra/prow/config.yaml
There are less IPs compared to the number of network tests being run in
parallel.
Increate the number of IPs and fix the following errors:
Code: IP_IN_USE_BY_ANOTHER_RESOURCE, Message: IP '10.128.3.140/31' is already being used by another resource.
=> prow: increase the number of alias ip for network test

osconfig_tests/main.go
we first read the testsuites from the channel to create the junit files
and the we again try to iterate over the channel to check for failures.
During the second loop, the channel is already empty and so the execution never fails.
=> Fix test runner execution

daisy/README.md
Fix some broken links (while poking around the docs)
(you might want to have colored labels :-)  )
=> Fix broken test config/testgrid links in daisy

cli_tools/google-osconfig-agent/main.go, cli_tools/google-osconfig-agent/patch/patch_run.go, cli_tools/google-osconfig-agent/patch/patch_state.go, cli_tools/google-osconfig-agent/patch/patch_state_test.go, cli_tools/google-osconfig-agent/patch/updates_linux.go, cli_tools/google-osconfig-agent/patch/updates_windows.go, cli_tools/google-osconfig-agent/service/service.go
- Patching reports status and stops if the patch job is not active
- Handles restarts across crashes and reboots
- Handles dryruns
- Handles stopping on failure
- Supports running the agent as `ospatch` to facilitate testing.
- Does not *yet* handle retry attempts (that'll be another PR)
- I did a lot of manual testing but this code doesn't lend itself well to unit testing. I need to think more about how to do that in a subsequent PR.
=> Update logic of patch run to report / check status as it goes

osconfig_tests/test_suites/inventory/inventory.go, osconfig_tests/utils/utils.go
Add tests for new windows instances
Add sleep before install in an attempt to deflake 2012 tests
=> osconfig_tests: increase timeout waiting for osconfig install

cli_tools/google-osconfig-agent/inventory/changes.go, cli_tools/google-osconfig-agent/inventory/changes_test.go
This is not yet tied into the actual inventory or package management code. It is just the logic that will be used to determine what updates are needed given the caller already has the `instanceInventory` and the `LookupConfigsResponse`.
The caller is expected to know which package managers they care about and pass the package info for just those packages.
=> Compare current state with desired state

daisy_workflows/image_import/windows/translate.ps1
Reverts GoogleCloudPlatform/compute-image-tools#675
This PR is breaking two tests:
https://gubernator.k8s.io/build/compute-image-tools-test/logs/ci-daisy-e2e/1095834234284675072
daisy-e2e-tests 2008R2 vmware image translate
daisy-e2e-tests 7 image translate
It appears to be related to the installation of vioscsi googet package.
```
2019/02/14 12:05:12 windows-startup-script-url: Running C:\ProgramData\GooGet\googet.exe with arguments -root C:\ProgramData\Go
2019/02/14 12:05:12 windows-startup-script-url: oGet -noconfirm install google-compute-engine-driver-vioscsi.
2019/02/14 12:05:12 windows-startup-script-url: Exception caught in script:
2019/02/14 12:05:12 windows-startup-script-url: 
2019/02/14 12:05:12 windows-startup-script-url: At …
```
=> Revert "Add driver package installation steps."

daisy_workflows/export/export_disk_ext.sh
Currently, qemu error details are not shown in daisy log and console. Let's output it there so user/dev can figure out the root cause easily.
It's tested manually since there isn't fancy new feature added.
=> Expose qemu error for export workflow

daisy_workflows/image_build/windows_for_containers/windows-1709-core-for-containers.wf.json, daisy_workflows/image_build/windows_for_containers/windows-1803-core-for-containers.wf.json, daisy_workflows/image_build/windows_for_containers/windows-1809-core-for-containers.wf.json
* windows-2019-for-containers workflow is based off windows-2019 (server desktop) base
image
* ensure all container images using server core as a base image contain 'core' in
the workflow name
=> Make Windows container workflow names consistent

daisy_workflows/image_build/sqlserver/sql-2016-enterprise-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql_install.ps1
* If Microsoft Update is not enabled, the latest cumulative update(s)
for SQL Server are not installed via automatic updates. Service packs
ARE installed regardless of the setting.
* MSSQL 2016 and 2017 now offered on Windows Server 2019.
=> Enable cumulative updates install, SQL on Server 2019

daisy/compute/compute.go
Error message is passed from utility method which creates a secure connection to
a Google API [doc link](https://godoc.org/google.golang.org/api/transport#NewHTTPClient)
=> Clarify API authentication error, fixes #368

test-infra/prow/config.yaml
I first create the new project without the hyphen and then changed it since it was not readable.
=> Fix new project name for osconfig e2e tests

daisy_workflows/image_build/sqlserver/sqlserver.wf.json
MSSQL builds on Server 2016 reach the 1 hr timeout before finishing. The exact time required for Windows updates to complete varies for each SQL server version, so I am attempting a 30 minute bump.
=> Increase build timeout for Windows updates

daisy_workflows/export/export_disk_ext.sh
This CL changes the way of using qemu-img:
Original: qemu-img output file to GCS by gcsfuse
Now: qemu-img output file to disk, then copy to GCS by gsutil
It achieves 3 purposes:
1. When qemu-img failed due to disk space or network issue, the workflow will fail. Previously it failed silently and the workflow got a success, and thus output a corrupt image.
2. Much higher success rate for large-size image, due that gsutil is much more reliable than gcsfuse, especially when network is not very stable. For a 198GB image, old method success rate is 29% while new method is 100% per my testing.
3. It made the code ready for next improvement: dynamically enlarge disk space to export >200GB image.
Conclusion: this CL resolved problems for <200GB image export, and technically prepared for >200GB …
=> Export: Change "qemu-img" to use disk as buffer, and then copy output to GCS gssutil

osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/package_management/package_management_utils.go
the package removal tests are flaky because soon after the test package is installed, the startup script tries to access package manager database but it is locked by some other process.
I only saw this happening frequently with debian hosts
=> Fix broken and flaky tests

osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/package_management/package_management_test_data.go
Without this, the tests from the subsequent test run fails if the resources
from previous tests are not clean'd up.
=> Add random suffix to resource names

cli_tools/google-osconfig-agent/config/config.go, cli_tools/google-osconfig-agent/config/config_test.go, cli_tools/google-osconfig-agent/inventory/inventory.go, cli_tools/google-osconfig-agent/inventory/inventory_test.go, cli_tools/google-osconfig-agent/main.go, cli_tools/google-osconfig-agent/ospackage/apt.go, cli_tools/google-osconfig-agent/ospackage/googet.go, cli_tools/google-osconfig-agent/ospackage/ospackage.go, cli_tools/google-osconfig-agent/ospackage/yum.go, cli_tools/google-osconfig-agent/ospackage/zypper.go, cli_tools/google-osconfig-agent/ospatch/patch_run.go, cli_tools/google-osconfig-agent/ospatch/watcher.go, cli_tools/google-osconfig-agent/ospatch/watcher_test.go, cli_tools/google-osconfig-agent/tasker/tasker.go, osconfig_tests/test_suites/inventory/inventory.go, osconfig_tests/test_suites/package_management/package_management.go
Rework task logic, attempt to standardize the surface for each component
Patch watcher reworked to allow for cancellation logic. Right now this is just used for disabling of the patch system.
=>  osconfig agent: read config options out of instance metadata

daisy_workflows/export/disk_export_ext.wf.json, daisy_workflows/export/disk_resizing_mon.sh, daisy_workflows/export/export_disk_ext.sh, daisy_workflows/export/image_export_ext.wf.json
Today, a large-enough disk (which means, more than 200GB after compression) can't be exported with format converting. This CL fixed the problem.
Originally: Worker instance use a 200GB for both buffering and OS. Now: It creates a separate buffer disk starting from 200GB and will increase 25GB when there is not enough space during the exporing process.
Detail of the resizing logic:
200GB as initial size.
Check available space every 10s.
If available space is less than 25GB, then add 25GB more.
Unless it has reached the max size. Max size is source disk + 5GB.
Resizing logic is host in a separate shell script "disk_resizing_mon.sh", which runs in background.
OS is hosted in a default size disk, which is 10GB now. It helps to isolate buffer size from OS, because OS size can be different in …
=> Resize buffer disk dynamically

cli_tools/google-osconfig-agent/main.go, cli_tools/google-osconfig-agent/ospackage/ospackage.go, go/packages/apt_deb.go, go/packages/gem.go, go/packages/googet.go, go/packages/packages_linux.go, go/packages/packages_windows.go, go/packages/pip.go, go/packages/yum.go, go/packages/zypper.go
This commit fixes 3 issues
1) 	As per Golang specs, the init functions from different files
in a single package are called in lexicographical order of
the file names.
Because of such order of initialization, some of the values
are not initialized before they are used.
2)	The agentconfig is not initialized for cases where the
users want to only execute a single feature
3)	In ospackage feature, the repo directory might not exist.
=> osconfig-agent: Fix initialization of global values

osconfig_tests/osconfig_server/osconfig_data_builder.go, osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/package_management/package_management_test_data.go, osconfig_tests/test_suites/package_management/package_management_utils.go
- As a osconfig user, user should be able to add a new repository
and install packages from the new one. For our case, we have create
new rapture repository 'osconfig-agent-test-repository'.
I have only added test for debian based system. Tests for yum based systems
are yet to follow.
- Removed the panics since it does not make sense to crash the test runner as
these configurations are owned by the test runner itself. There will be no situation
where the a package-manager is missing unknowingly
=> Add integration tests for installation from new repo

cli_tools/google-osconfig-agent/lock_linux.go, cli_tools/google-osconfig-agent/lock_windows.go, cli_tools/google-osconfig-agent/logger/logger.go, cli_tools/google-osconfig-agent/main.go, cli_tools/google-osconfig-agent/ospatch/patch_run.go, cli_tools/google-osconfig-agent/packaging/googet/install.ps1
Use a lock file to ensure only one osconfig process is running at any one time. This is a simple solution to this issue and should be expanded upon or replaced later with a more robust solution.
=> osconfig agent: use a lock file

cli_tools/gce_image_publish/publish/publish.go, cli_tools/gce_image_publish/publish/publish_test.go
Currently with prefix `image-foo` and empty version, the publish name will become `image-foo-` and fails daisy validation :-(
=> When version is empty, don't append the dash in image name

Dockerfile.gce_ovf_import
Adding missing OVF importer Dockerfile which should have been part of the big OVF importer pull request
=> OVF importer Dockerfile

cli_tools/gce_ovf_import/main.go
OVF importer: fix docker image autobuilds failure  due to osconfig_test package being imported into OVF importer main
=> OVF importer: fix docker image autobuilds failure 

cli_tools/google-osconfig-agent/config/config.go, cli_tools/google-osconfig-agent/config/config_test.go
Currently, there is no way to increase verbosity of agent logging. Until now, for debugging purpose I had to restart the agent on the test vm with the debug flag. This was already a painful process, and with introduction of agent locking, even this option was no more feasible.
=> Allow increase log verbosity through instance metadata

daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Turns out CentOS ships their UEFI boot shim in a different path than redhat, and this can cause boot failures in some scenarios. This PR simply amends the path in the kickstart script that generates GSetup/boot.
=> Correct CentOS7 GSetup path

osconfig_tests/osconfig_server/osconfig_client.go
Ensure we load the configs before using them to create the client. This was broken the other day when we changed how we load the `SvcEndpoint`.
=> Fix PackageManagement tests

cli_tools/google-osconfig-agent/config/config.go, cli_tools/google-osconfig-agent/config/config_test.go
- Only supports instance metadata since we don't want this done very often.
- Handy for testing and demos.
=> OS Config - Make service poll interval overridable from metadata

daisy_workflows/image_import/windows/run_startup_scripts.cmd
Fix potential time issues with Windows import: set UTC time zone before re-syncing clock.
=> Fix potential time issues with Windows import: set UTC time zone

cli_tools/google-osconfig-agent/config/config.go, cli_tools/google-osconfig-agent/config/config_test.go
If the osconfigpollinterval is not set in the metadata(like in case of our end to end tests), the code path generates nil pointer exception.
[Fail test](https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/osconfig-tests/1116435195327680512)
=> Fix nil pointer failure and add unit test

go/packages/packages.go
Wrapping the error looses the exit code of the exec command. The exit
code is used by callers to take specific decisions. [Specific example](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/go/packages/yum.go#L84)
=> Don't wrap error returned from exec

go/packages/yum.go
when a new yum repository is added by the user, we add the repo
details in the yum database, but do not import the gpg keys.
When we check for updates, yum will first try to add the gpg keys
for the newly added repo. Yum prompts for confirmation to add
the gpg keys.
Without this change, yum update check fails.
=> [OsConfig Agent] answer yes to all questions

osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/package_management/package_management_test_data.go
This change is built on top of PR:https://github.com/GoogleCloudPlatform/compute-image-tools/pull/738
Out of the 2 commits in this PR, the other one is already being reviewed in the above mentioned PR.
=> [OsConfig Agent] Add other supported images for different platforms

test-infra/prow/Makefile, test-infra/prow/cluster/tide_deployment.yaml, test-infra/prow/config.yaml
This should enable tide to merge PRs targeting the named branch (and bc of the confusion around this feature[1], I've also enabled dry run mode). The tide component has already been set up and deployed, this config will enable it.
Following merge I will generate and upload the modified configmap using the relevant Makefile target e.g. `make update-config`. 
[1]: https://github.com/kubernetes/test-infra/issues/12304
=> Add testing tide config

test-infra/prow/Makefile, test-infra/prow/cluster/tide_deployment.yaml
* After running with dry-run enabled for a day, we see tide does honor the branch restriction. Running now with dry-run disabled for further testing.
* Updated container image to latest (as of today)
To be entirely clear, this change is already live and the PR is just to commit this config.
=> Update tide image, disable dry-run

cli_tools/common/utils/storage/storage_client.go, cli_tools/gce_vm_image_import/main.go
Currently, scratch bucket name can't be processed correctly since regex doesn't match. Fix by changing to correct regex.
=> fix bucket split logic

cli_tools/google-osconfig-agent/ospatch/patch_run.go, cli_tools/google-osconfig-agent/ospatch/patch_state_test.go, cli_tools/google-osconfig-agent/ospatch/updates_linux.go, cli_tools/google-osconfig-agent/ospatch/updates_windows.go
I simplified the states the agent can be in but should still allow for all the same workflows. Machines should now be able to reboot as much as needed while still allowing for a forced reboot (only once), or no reboots at all.
reportPatchDetails now tries to report patch details for about 30min
=> osconfig agent: rework patch step logic

cli_tools/common/utils/daisy/resource_labeler.go, cli_tools/common/utils/daisy/resource_labeler_test.go, cli_tools/gce_image_publish/publish/publish.go, cli_tools/gce_image_publish/publish/publish_test.go, cli_tools/gce_vm_image_import/README.md, cli_tools/gce_vm_image_import/main.go, cli_tools/gce_vm_image_import/main_test.go, daisy/compute/compute.go, daisy/compute/compute_test.go, daisy/compute/test_client.go, daisy/compute/test_client_test.go, daisy/image.go, daisy/image_test.go, daisy/step_create_images_test.go, daisy/test_common_test.go, daisy/workflow_test.go, daisy_image_locality_cloudbuild.yaml, mocks/mock_compute_client.go
This change adds support for image locality property by utilizing compute alpha API.
This change is not expected to be merged into master in full once compute prod API is updated to have image locality property (only resource_labeler and gce_vm_image_import/main will need to be updated for prod).
=> Image import locality support for development purposes

cli_tools/gce_image_publish/publish/publish.go, cli_tools/gce_image_publish/publish/publish_test.go
When copying over images from prod to staging, it will try to deprecate all images when family is not set, which feels is a wrong behavior for me.
=> don't deprecate images if family is empty

cli_tools/google-osconfig-agent/config/config.go, cli_tools/google-osconfig-agent/config/config_test.go, cli_tools/google-osconfig-agent/ospackage/ospackage.go
os-config-enabled-prerelease-features is a metadata key that can be used to enable the ospatch and ospackage features
Exact feature naming may change in the future
=> osconfig agent: use os-config-enabled-prerelease-features

cli_tools/google-osconfig-agent/inventory/inventory.go, cli_tools/google-osconfig-agent/logger/logger.go
Inventory Timestamp entry changed to LastUpdated
Rejiggered string log lines
Logs will now be written to all outputs ignoring errors
=> osconfig agent: rename inventory timestamp, fix string logging

cli_tools/google-osconfig-agent/config/config.go, cli_tools/google-osconfig-agent/ospatch/patch_run.go, cli_tools/google-osconfig-agent/ospatch/patch_state.go, cli_tools/google-osconfig-agent/ospatch/patch_state_test.go, cli_tools/google-osconfig-agent/ospatch/updates_linux.go, cli_tools/google-osconfig-agent/ospatch/updates_windows.go, cli_tools/google-osconfig-agent/ospatch/watcher.go, cli_tools/google-osconfig-agent/ospatch/watcher_test.go
A global patch state is now kept in memory and saved to disk after each edit
All current patch runs are recorded in the order that they were received, after agent restart they will be enqueued in the same order
The last 10 completed PatchJob names are also recorded
A patch job will not be acked if it exists in the either the current list of PatchRuns or past list of completed jobs
=> osconfig agent: update how agent state is saved

osconfig_tests/config/config.go, osconfig_tests/gcp_clients/gcp_clients.go, osconfig_tests/main.go, osconfig_tests/test_suites/patch/patch.go
- Runs a PatchJob on all supported distros (even though some of those fail today).
- Includes a little bit of cleanup.
- Does not verify that agent did anything but report success. That will be done in subsequent PRs.
=> Basic PatchJob e2e tests

osconfig_tests/test_suites/patch/patch.go
Including the patch name in the error message will help track failures from the test dashboard.
=> OS Config - Patch: minor improvement to patch error messages

cli_tools/gce_ovf_import/main.go, cli_tools/gce_ovf_import/main_test.go, cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params.go, cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator.go, cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator_test.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go, daisy_workflows/ovf_import/import_ovf.wf.json, gce_ovf_import_tests/compute/instance.go, gce_ovf_import_tests/junitxml/junitxml.go, gce_ovf_import_tests/main.go, gce_ovf_import_tests/scripts/ovf_import_test_ubuntu_3_disks.sh, gce_ovf_import_tests/test_config/project_config.go, gce_ovf_import_tests/test_suites/ovf_import_test_suite.go, test-infra/README.md, test-infra/prow/config.yaml, test-infra/prowjobs/cloudbuild.yaml, test-infra/prowjobs/gce-ovf-import-tests/Dockerfile
Notes to make the review easier:
- this change includes refactoring gce_ovf_import/main.go by extracting most of the logic to ovf_importer.go and ovf_import_params_validator.go (including tests). Most of this code was already reviewed. This was necessary to make e2e tests easier to write.
- Code in gce_ovf_import_tests/ is based on osconfig_tests/
- gce_ovf_import_tests/scripts/ovf_import_test_ubuntu_3_disks.sh is based on daisy_integration_tests/scripts/post_translate_test.sh with extra check for mounted disks added
Docker image build was not tested yet. The test did run successfully when executed directly on dev box.
The test suite currently includes only one (fairly complex) scenario. Once we verify Prow is configured correctly to run this test, more test cases will follow.
=> OVF import e2e tests

osconfig_tests/compute/instance.go, osconfig_tests/main.go, osconfig_tests/test_config/project_config.go, osconfig_tests/test_suites/inventory/inventory.go, osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/patch/patch.go, test-infra/prow/config.yaml
- Avoids sporadic stock out issues.
- Test runner flags also supports JSON map of zones to quota.
- Increases frequency of E2e test runs.
- Updates prow test runner to run tests in multiple zones.
- Simply chooses a random zone that still has quota to run the test.
Additional, more complex ways of breaking these tests up will be added when needed.
=> OS Config - run tests across multiple zones

test-infra/prowjobs/gce-ovf-import-tests/Dockerfile
Fix OVF import e2e test docker to include Daisy workflows (necessary for running OVF import)
=> Fix OVF import e2e test docker to include Daisy workflows

daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json, daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json, daisy_workflows/image_import/debian/translate_debian.wf.json, daisy_workflows/image_import/enterprise_linux/translate.py, daisy_workflows/image_import/enterprise_linux/translate_centos_6.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_7.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_licensed.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json, daisy_workflows/image_import/suse/translate_suse.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
- Will make these faster and more reliable.
- Also use newer RHEL compute engine repo.
=> Update translation workflows to use debian-9 worker image.

cli_tools/gce_ovf_import/main.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
OVF import: logging errors in OVF importer instead of main as they are otherwise not logged to GCS preventing users from seeing the error in gcloud command output.
=> OVF import: fixed error handling

daisy_integration_tests/image_export_vmdk_latest.wf.json
Increased timeout for VMDK export e2e latest test as it occasionally times out after 10 minutes. Match the 20 minute timeout from the equivalent test for release worker image.
=> Increased timeout for VMDK export e2e latest test

gce_image_import_export_tests/test_suites/export/image_export_test_suite.go, gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
Add more image import/export cli tool e2e tests for rich params.
Some params are hard to test and is not critical to our main scenario, so we skipped them for now:
-oauth, -compute_endpoint_override, and -scratch_bucket_gcs_path,
and all KMS-related params.
=> [import/export cli] add more image import/export cli tool e2e tests for rich params

osconfig_tests/compute/instance.go, osconfig_tests/test_suites/inventory/inventory.go, osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/patch/patch.go, osconfig_tests/utils/utils.go
Don't use variableKey when requesting guest attributes, that was a legacy option.
=> osconfig_test: fix many of the flakes

osconfig_tests/compute/instance.go, osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/package_management/package_management_test_data.go, osconfig_tests/test_suites/package_management/package_management_utils.go, osconfig_tests/test_suites/patch/patch.go, osconfig_tests/test_suites/patch/test_setup.go
Move setting of WSUS server to sysprep startup script so we don't get hung up on the reboot.
=> osconfig_tests: attempt to deflake Windows patch tests

cli_tools/gce_vm_image_export/README.md, cli_tools/gce_vm_image_export/main.go, cli_tools/gce_vm_image_export/main_test.go, gce_image_import_export_tests/test_suites/export/image_export_test_suite.go, gce_image_import_export_tests/test_suites/import/image_import_test_suite.go, gce_image_import_export_tests/test_suites/test_suite_utils.go
There are changes:
1. Changed format of "source_image" to be align with daisy input. The purpose is to be compatible with 2 forms of input:
- "global/images/anImage"
- "projects/myproject/global/images/anImage"
2. Changed e2e test error handling to avoid exiting process unexpected.
=> [export cli tool] modify "source_image" param and fix e2e tests

daisy_workflows/image_import/windows/translate_windows_2003.wf.json
Fix Windows 2003 translate failing due to usage of a deprecated windows 1709 core image for bootstrap step.
=> Fix Windows 2003 import translate failing

cli_tools/gce_export/README.md, cli_tools/gce_export/file_writer.go, cli_tools/gce_export/main.go, daisy_workflows/export/disk_export_ext.wf.json
A new param "local_path" is added. Now it's a either-or between "local_path" and "gcs_path".
The reason to add this is because we plan to change the way of exporting raw. This PR is the 1st half of the change. The 2nd half would be: change export workflow to use "local_path" and then do "gsutil cp" to gcs. Between 1st half and 2nd half, we need to release a new debian-9-worker image to adopt the new gce_export.
The purpose is to avoid long TCP connection with GCS. Currently, when directly writing .tar.gz file to GCS, a super long TCP connection to write the whole file (by io.CopyN) has to be established. However, it's not as stable as before (tcp connection reset happens a lot), and it's anyways unstable while writing a large image.
Per my testing, the performance of new implementation is …
=> [gce_export] Export raw: support exporting to local disk

docs/daisy-workflow-config-spec.md
The actual field name is `DeviceName`, not `Name`.
https://github.com/GoogleCloudPlatform/compute-image-tools/blob/def68e87dd9e05dba74e1b9aff49d8199922f420/daisy/step_detach_disks.go#L26-L32
=> Correct DetachDisks[].DeviceName field in the spec

daisy/instance.go
Daisy: removed the check for network being in the same project to support shared VPC use-case.
=> Daisy: removed the check for network being in the same project

cli_tools/gce_vm_image_export/main.go, cli_tools/gce_vm_image_import/main.go, gce_image_import_export_tests/test_suites/export/image_export_test_suite.go, gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
Currently there is a logic lost in import/export wrapper: when subnet is specified and network is not, we should set network to empty string to avoid falling back to default network.
This logic exists in gcloud GA. However, since gcloud is going to call wrapper, this logic should be hosted in this repo. There are 2 reasons to do it:
1. Rich logic should be handled by wrapper layer as much as possible.
2. For a cli tool, there is no way to distinguish network=none v.s. network='', due that param is not nullable.
Added e2e test correspondingly.
This fix is required to fix the behavior of gcloud calling wrapper.
=> fix param network/subnet logic for import/export wrapper

cli_tools/gce_export/README.md, cli_tools/gce_export/main.go
gce_export responses for exporting raw format. A couple of improvements aree done by this PR.
1. Reliability: chunk size
Removed chunkSize=0, which means, using default setting instead. By testing, without this change, while exporting by a non-gcp computer, for a 2GB OS disk, it's 33% chance to fail; for a full-filled 10GB disk, it's 100% to fail. It's very fragile because it's very hard to finish sending a huge single request (256MB) via public network. Theoretically, even for a gcp computer, it is not super stable as well. So I changed it to default chunk size. With this change, it's 100% success. The perf is almost not impacted: 2s slower for a 10GB disk, which is, 1m44s v.s. 1m42s.
2. Reliability: retry logic
Moved "defer os.Remove(in)" to the correct place. Without this change retry …
=> A couple of improvements for gce_export

daisy_release_cloudbuild.yaml, export_release_cloudbuild.yaml
Move export related images out of the main Daisy Cloud Build config due to reliability reset so we can continue building images not related to export.
=> Move export related images out of the main Daisy Cloud Build config

gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Fix OVF e2e test that is failing due to the introduction of a new machine type family today (N2 - https://cloud.google.com/blog/products/compute/expanding-virtual-machine-types-to-drive-performance-and-efficiency)
=> Fix OVF e2e test

gce_image_import_export_tests/main.go, gce_image_import_export_tests/test_suites/export/image_export_test_suite.go, gce_image_import_export_tests/test_suites/import/image_import_test_suite.go, gce_image_import_export_tests/test_suites/test_suite_utils.go, go/e2e_test_utils/launcher.go, test-infra/prow/config.yaml, test-infra/prowjobs/cloudbuild.yaml, test-infra/prowjobs/gce-image-import-export-tests/Dockerfile, test-infra/prowjobs/wrapper/DockerfileWithGcloud
Originally we only have e2e test for wrapper. Now we added for gcloud, and there are 3 test types now:
"1 wrapper"
"2 gcloud-prod wrapper-latest"
"3 gcloud-latest wrapper-latest"
For each test scenario, we will run above 3 types of tests.
To support the new test type, some other changes are required:
1. Added a base docker image which contains gcloud pre-installed.
2. Before test run, install corresponding gcloud version and auth. The "latest" gcloud sdk is hosted in by gcloud team, and we just need to ref to it.
3. Moved test zone from us-central1-c to us-central1-b to balance the test load.
=> e2e test for gcloud images import/export

daisy_workflows/image_import/import_disk.wf.json, daisy_workflows/image_import/import_image.sh
This is a small refactor that prepares for an upcoming change that
removes usage of gcsfuse in import_disk.sh.
To test the change, I downloaded an Ubuntu 18.04 vmdk from Canonical and then ran daisy with the update workflow below. Here are the logs:
```bash
% daisy -var:source_disk_file=gs://<bkt>/images/ubuntu-18.04-server-cloudimg-amd64.vmdk \
-var:image_name=ubuntu18 \
-zone=us-central1-a \
-project=$PROJECT \
daisy_workflows/image_import/import_image.wf.json
[Daisy] Running workflow "import-image" (id=jl8b5)
[import-image]: 2019-08-19T14:17:53-07:00 Validating workflow
[import-image]: 2019-08-19T14:17:53-07:00 Validating step "import-disk"
[import-image.import-disk]: 2019-08-19T14:17:53-07:00 Validating step "setup-disks"
[import-image.import-disk]: 2019-08-19T14:17:53-07:00 …
```
=> Image-import: Preattach destination disk prior to running import_disk.sh

gce_image_import_export_tests/main.go, test-infra/prowjobs/cloudbuild.yaml
It doesn't impact any actual test result, but will give a wrong exit code on cmd line
=> fix exit code for e2e test

test-infra/prowjobs/cloudbuild.yaml
15min is not enough anymore since more images were added
=> extend test cloudbuild timeout to 30min

daisy/disk_test.go, daisy/step_includeworkflow.go, daisy/step_includeworkflow_test.go, daisy/step_wait_for_instances_signal.go, daisy/workflow.go
WaitForInstancesSignal failure match list should be public
IncludeWorkflow needs to set parent during populate
=> Daisy bugs in non-JSON workflow creation paths.

daisy_workflows/image_import/import_disk.wf.json, daisy_workflows/image_import/import_image.sh
This was prompted by failures in integration tests, where the previous
behavior was expected. The typical failure message in those tests
was:
```
Ubuntu 1604 import and translate: step "import-and-translate-image" validation error: step "translate" validation error: step "translate-disk" validation error: step "translate-disk-inst" validation error: step "translate-disk-inst" cannot attach disk "temp-translation-disk-lv8zb" to instance "inst-translator": concurrent RW attachment of disk "temp-translation-disk-lv8zb" between instances "inst-translator" (READ_WRITE) and "inst-importer" (READ_WRITE)
```
To confirm the fix, I ran `daisy -zone=us-central1-a -project=edens-test daisy_integration_tests/ubuntu_1604_import_and_translate.wf.json` and observed that the message 'cannot attach disk' …
=> import_image.sh: Bring back manual disk attachment.

daisy_workflows/image_import/debian/translate.py
Fix Debian 9 import failing if gnupg is not installed with "gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation" error.
=> Fix Debian 9 import failing if gnupg is not installed

cli_tools/common/utils/daisy/resource_labeler_test.go, cli_tools/gce_ovf_import/main.go, cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
Fix OVF import failure when location restrictions are on due to images being created in multi-regions. Since this change is internal to the importer, added releaseTrack flag to indicate which Compute API release track is allowed to be used. Image location is only in Beta and we shouldn't use Beta API in GA release.
=> Fix OVF import failure when location restrictions are on

daisy/step_wait_for_instances_signal.go, daisy/step_wait_for_instances_signal_test.go, daisy/workflow.go, daisy_workflows/export/export_disk.sh, daisy_workflows/export/export_disk_ext.sh, daisy_workflows/image_import/import_image.sh
We want to log target/source disk/image/file size for import/export for usage/perf analysis.
We need to expose the value from .sh script. Thus, using a string pattern is almost the only way. I defined this pattern: <serial-output key:'(.*)' value:'(.*)'>
key-value pair in this pattern will be catched and recorded in workflow, and thus can be stored to logging.
=> [Logging] return disk/image/file size from import/export script

cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_import/importer/importer.go
Log Cloud Build ID in import/export wrappers to help with debugging: log using Daisy logger to log to GCS
For a proper solution, wrappers should initialize Logger and inject it into workflow. For the time being, this workaround is fine.
=> Log Cloud Build ID in import/export wrappers to help with debugging

cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go
This fixes an error in the OVF tests:
```
- "[OVFImportTests] [OVFImport] Windows 2012 R2 two disks": error while performing OVF import: step "wait-for-data-disk-1-signal" run error: WaitForInstancesSignal FailureMatch found for "data-disk-importer-1-import-ovf-33v2j": "ImportFailed: Failed to prepare scratch disk.'"
```
To confirm the fix, I ran:
```
go run gce_ovf_import_tests/main.go -test_project_id edens-test -test_zone us-central1-a
```
=> Allocate a scratch disk when importing OVFs.

daisy_workflows/image_import/import_image.sh
Prior to this change, large image files would exceed the scratch disk, and cause the `gsutil cp` command to fail.
An additional fix is included to ensure that we don't exceed the logging daemon's buffer with the progress meter for `gsutil cp`.
For testing, I ran these integration tests:
- image_export_vmdk_given_size_1024gb.wf.json
- image_export_vmdk_given_size_210gb.wf.json
=> Increase scratch disk to account for EXT4 overhead.

daisy/compute/compute.go, daisy/compute/compute_test.go
Currently, Daisy only retries when a GCE API error returns a
googleapi.Error. However, errors that are not googleapi.Errors are most
likely transport errors, which should always be retried. Lets retry for
errors that are not googleapi.Errors as well.
=> daisy: compute: Retry on transport-level failures

cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go, gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
OVF import E2E tests: override Build ID (which is used for temp GCS path) as it appears OVF importer has been picking up "BUILD_ID" env variable (which works in Cloud Build) from Kubernetes environment resulting in shared temporary GCS path for extracted OVFs and overwritten OVF resources between different tests.
=> OVF import E2E tests: override Build ID

daisy_workflows/image_import/import_image.sh
We've seen intermittent disk-full failures when using /dev/sdb and /dev/sdc in import_image.sh. These debug logs will help to diagnose the issue.
=> Add debug logs prior to using dynamically-sized disks.

cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go, cli_tools/gce_ovf_import/ovf_utils/testdata/from-virtualbox.ovf, gce_ovf_import_tests/test_suites/ovf_import_test_suite.go, vendor/github.com/vmware/govmomi/ovf/cim.go, vendor/github.com/vmware/govmomi/ovf/envelope.go
Two changes were required here, and each has its own commit:
1. Update the govmomi schema to support `StorageItem`, which is the node where virtualbox defines to which controller a disk is attached. (vmware puts that info in an `Item` node)
2. Update `ovf_utils` to use the new node.
Testing:
- `go test ./...`
- `gofmt -d $(find . -type f -name "*.go")`
- `go run gce_ovf_import_tests/main.go -test_project_id edens-test -test_zone us-central1-a`
=> Support VirtualBox ovfs

gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Disable startup script e2e test validation for Debian 9 for the time being. This image has SSH disabled which might be causing the issue. Added support for no startup script in the test runner.
=> Disable startup script e2e test validation for Debian 9

gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
I exported the image from AWS using [these docs](https://docs.aws.amazon.com/vm-import/latest/userguide/vmexport.html).
For testing, I ran `go run gce_ovf_import_tests/main.go` and confirmed that the new AWS test is passing.
=> Add OVF test for image exported by AWS.

cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/importer_test.go
Fix is_windows variable name causing E2E test failures: `unknown workflow Var "isWindows" passed to Workflow "import-from-image"`
=> Fix is_windows variable name causing E2E test failures

cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_export/exporter/exporter_test.go, gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
[export wrapper] support simple image name.
Before: only support format like "global/images/anImage"
Now: support "anImage" as well, which will be extended to "global/images/anImage" automatically
=> [export wrapper] support simple image name

cli_tools/common/utils/logging/service/logger.go
Remove the use of Time.Milliseconds() until we figure out why Go Cloud Builder is out of date.
=> Remove the use of Time.Milliseconds() 

daisy/step_wait_for_instances_signal.go
Added explanation that info about FailureMatch is not an error. This has confused engineers who are not working on Daisy directly so it must be confusing to customers.
=> Added explanation that info about FailureMatch is not an error. 

test-infra/prow/config.yaml
Ubuntu 1810 is not available anymore in project `ubuntu-os-cloud`
=> prow: Remove deprecated Ubuntu 1810 from linux image list

daisy_integration_tests/scripts/post_translate_test.sh, gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Testing: Ran `go run gce_ovf_import_tests/main.go -test_project_id edens-test -test_zone us-central1-a`
=> CentOS 6: Wait until network is ready.

daisy_workflows/image_build/enterprise_linux/kickstart/el6-post.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/el8-options.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/el8-uefi-options.cfg, daisy_workflows/image_import/debian/translate.py, daisy_workflows/image_import/enterprise_linux/translate.py, daisy_workflows/image_import/suse/translate.py
* set IO scheduler to `noop` on older kernels (EL6,7)
* use blk-mq on newer kernels (Debian9,10,SLES12,15)
* update sed command to use matches instead of capture groups
Currently we don't set a consistent value for the IO scheduler, and we set the incompatible `elevator` and `scsi_mod.use_blk_mq` parameters on some distros. This PR updates the image creation and import workflows to set appropriate kernel command line parameters. Instance setup must be updated to set the scheduler to none, as there's currently no option to set this on the command line.
=> Update IO scheduler settings

daisy_integration_tests/scripts/post_translate_test.sh
The daisy_integration_tests/centos_6_qcow2_translate.wf.json test also uses post_translate_test.sh, but its base CentOS6 image doesn't have NetworkManager. I haven't observed any of its tests failing due to network race conditions; if we see that, then we can tweak this network detection.
- Ran `daisy_integration_tests/centos_6_qcow2_translate.wf.json `
- Ran `go run gce_ovf_import_tests/main.go -test_project_id edens-test -test_zone us-central1-a`
=> Only check for CentOS6 network readiness if NetworkManager is available.

daisy_workflows/image_import/import_image.sh
I added this check as part of #946 as a lower-priority check. It's breaking a large test that uses a disk of size 1024 GB; lsblk returns a size of 1T rather than 1024G, and hence the check is failing.
So, I'm reverting this check for now since it would break all imports of size greater than 1T.
=> Resize post-check: Support terabyte-sized disks

daisy_workflows/image_build/debian/build.py, daisy_workflows/image_build/debian/debian.wf.json, daisy_workflows/image_build/debian/debian_9.wf.json
This goes with https://github.com/zmarano/bootstrap-vz/commit/9b81ff0858fceb9ec2b635ddcc7b79f6d5af650c to install the OS Config agent.
The upstream project is locked and no longer accepting changes.
=> Update Debian 9 build to pull from branched bootstrap-vz.

cli_tools/import_precheck/check_sha2.go
Updates the precheck tool to mach the guidance on our [help page](https://cloud.google.com/compute/docs/instances/windows/bring-your-own-license/), which links to KB4474419.
1. Starting from a vanilla install, confirmed that the image fails to import (hangs while attempting to boot for translation)
2. Added KB4474419, and confirmed that the image can be imported.
3. Ran the precheck tool against (1) and confirmed that it failed, and ran the tool against (2) and confirmed that it passed.
=> Update Windows SHA2 precheck to look at KB4474419.

daisy_integration_tests/scripts/post_translate_test.ps1, gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
The test confirms that we're adding the WINDOWS GuestOsFeature during import. I confirmed that it fails when #961 isn't applied.
Additionally, this adds retries for checking Windows activation, which I noticed was flaky.
=> Add e2e test for multiple-NIC win2008r2.

cli_tools/common/utils/logging/service/log_entry.go, cli_tools/common/utils/logging/service/logger.go
It guards "logParams". The "logParams" has a chance to be updated while another thread is trying to send it to log server.
=> [logging] fix log race condition

daisy_integration_tests/daisy_e2e.test.gotmpl, daisy_integration_tests/image_import_allow_spaces_in_disk_filename.wf.json, daisy_workflows/image_import/import_image.sh
This change allows the filename of a disk to have a space in it, and includes an integration test. 
Prior to this fix, import if you tried to import an image with spaces in its name, you'd see an error from qemu-img of "Could not read image for determining its format: File too large "
=> Image Import: Allow spaces in disk's filename.

cli_tools/daisycommon/io.go, cli_tools/daisycommon/io_test.go, cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/importer_test.go
We've seen some errors lately where an import was run against an empty file. This will help to catch the error earlier, and to give more helpful debug information.
=> Don't allow empty disk images to be imported.

cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_import/importer/importer.go
This prefix is required because gcloud filters log based on prefix. Without this prefix, the final error msg won't show up in gcloud console.
=> [error log] add log prefix to pass gcloud filter

daisy/disk.go, daisy/step_create_disks.go, daisy/step_create_disks_test.go, daisy_integration_tests/daisy_e2e_quota_exceeded.test.gotmpl, daisy_integration_tests/image_export_ssd_quota_exceeded.wf.json, daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/disk_export_ext.wf.json, daisy_workflows/image_import/debian/translate_debian.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_6.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_7.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_licensed.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json, daisy_workflows/image_import/freebsd/translate_freebsd.wf.json, daisy_workflows/image_import/import_disk.wf.json, daisy_workflows/image_import/import_from_image.wf.json, daisy_workflows/image_import/suse/translate_suse.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json, daisy_workflows/image_import/windows/translate_windows_wf.json, daisy_workflows/ovf_import/import_ovf.wf.json, test-infra/prow/config.yaml
Fallback to pd-standard for import/export when failed to create disk
It resolved the problem that import/export failed due to quota exceeded error.
This PR includes:
1. code change to handle fallback logic
2. workflow change to enable FallbackToPdStandard flag
3. unit test
4. e2e test
=> fallback to pd-standard for import/export when failed to create disk

daisy/step_copy_gcs_objects_test.go
This fixes the presubmit errors that we started seeing yesterday such as [this one](https://k8s-gubernator.appspot.com/build/compute-image-tools-test/pr-logs/pull/GoogleCloudPlatform_compute-image-tools/984/presubmit-unittests/1189191560273596416/).
According to https://cloud.google.com/storage/docs/json_api/v1/ both
URL formats are valid for object insertion.
=> Support both POST URLs for object insert.

cli_tools/common/utils/logging/service/log_entry.go, cli_tools/common/utils/logging/service/logger.go, cli_tools/daisy_test_runner/main.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go, daisy/logger.go, daisy/logger_test.go
Notes:
- I've piggy-backed on Daisy's `DisableCloudLogging` flag; if the user specifies that flag, then we won't keep the serial output.
- Logs are only retained if there's a workflow error.
Testing:
- In addition to unit tests, I ran OVF's import integration tests.
=> Save serial logs if there's an import failure.

cli_tools/diagnostics/main_windows.go, cli_tools/diagnostics/main_windows_test.go
Evtx file is compressed binary xml format, not readable on Linux/Mac without any tools. 
If transformed all evtx files, it would take around 20mins.
So just transfrom Application,System which are most valuable logs, to plain text files.
=> Transfrom Application & System event logs from evtx files to plain text files

daisy/step_create_instances.go, daisy/workflow.go
waitForInstanceSignal is able to kill an instance depending on its serial output, while createInstance is responsible for archiving serial output. Typically these steps run in parallel, leading to situations where an instance is killed prior to archiving the latest batch of logs. 
This commit adds a couple of mitigations:
1. Always get the latest batch of logs when a workflow is canceled.
2. Delay the return of createInstance by 20 seconds.
Testing:
- Ran the OVF import integ tests.
=> Mitigate race condition between createInstance and waitForInstanceSignal

daisy_workflows/image_import/windows/translate_bootstrap.ps1
This reverts commit 89fc62638f6db687f7e13fbad29382beeaf7721d.
A syntax error is causing image imports to fail.
=> Revert "[Import] Skip bootloader mod when importing GPT boot disk."

daisy_workflows/image_import/import_disk.wf.json
Prior to this, if the default GCE service account didn't have access to GCS, then the user would see "WARNING Failed to download metadata script". With this change, they'll start seeing the customized error messages that we're creating, such as that in #996.
Testing:
1. Disabled GCS access, ran an instance of `import_and_translate.wf.json` with Daisy, and observed that the startup script executed. The import failed at the point of resizing the disk.
2. Re-enabled GCS and confirmed that the import worked as before.
3. Ran OVF import integration tests.
=> Allow import to initiate when worker instance doesn't have access to cloud storage.

daisy_workflows/image_build/sqlserver/configs/sql_server_2019.ini, daisy_workflows/image_build/sqlserver/sql-2019-enterprise-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2019-standard-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2019-web-windows-2019-dc.wf.json
- Enterprise, Standard, and Web versions, all on Windows Server 2019.
- Attempt to match the SQL Server config for our 2017 builds.
=> Add SQL Server 2019 builds.

daisy_workflows/image_import/import_disk.wf.json
Default for import_license to avoid create disk API failures if empty string is provided for a license.
=> Default for import_license 

cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go, cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater_test.go, daisy/step.go
OVF Import: data disk steps to use workflow default timeout instead of timeout being hardcoded to 1hr
=> OVF Import: data disk steps to use workflow default timeout

daisy_workflows/image_import/import_disk.wf.json
Importing images depends on worker instances that run with user's GCP project. If the instance is shutdown, then currently then the import workflow fails with 'WaitForInstancesSignal: instance %q: error getting serial port'.
This is a two-fold problem: First, it's a confusing message to users. Second, it adds noise to our metrics.
Use `shutdown-script` to send a sentinel message. If this message is detected before `ImportSuccess|ImportFailed`, then we know the worker instance is being terminated prior to the end of the import workflow.
1. For OVF and VMDK import, started an import, killed the worker, and observed that daisy correctly identified the shutdown worker and started the cleanup process.
2. Running `gce_ovf_import_tests`; I'll wait for these to finish prior to pushing.
=> Image import: Detect and fail if import worker is terminated.

cli_tools/import_precheck/README.md
Current `.md` page shows raw content.
=> Change import documentation link to .html

cli_tools/common/utils/validation/validation_utils.go, cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go, cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater_test.go, daisy_workflows/ovf_import/import_ovf.wf.json
OVF Import: limit disk names to 63 characters to prevent failures when long instance name is provided.
=> OVF Import: limit disk names to 63 characters

daisy/logger_test.go, daisy/workflow_test.go
[daisy] fix unit test
Some tests failed in specific time zones. The "expect" regex expect a GMT-x time zone, but, for example, China is in GMT+8, which doesn't match the regex.
Some failed without default credential. So, especially on a new setup machine, the test will fail without a meaningful hint message. I added the output for the error so developer can hae an idea what's going on.
=> [daisy] fix unit test: some tests failed in specific time zones; some failed without default credential

daisy/step_create_instances.go
Quit silently if we were able to read *some* data from the instance,
since there's a race condition where an instance can shut down
fast enough that the call to InstanceStatus will return a 404.
=> Don't emit error if we've previously read data from a serial log.

cli_tools/common/utils/storage/scratch_bucket_creator.go, cli_tools/common/utils/storage/storage_client.go, cli_tools/common/utils/storage/storage_client_test.go, cli_tools/common/utils/storage/tar_gcs_extractor.go, cli_tools/gce_export/main.go, cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator.go, cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator_test.go, cli_tools/gce_vm_image_import/importer/importer.go, daisy_workflows/image_import/windows/run_startup_scripts.cmd
Fixes for handling GCS paths where existing code was rejecting valid paths. E.g. gs://bucket-name/ was being rejected from OVF import as it didn't have object name portion, even though it's a valid path to an OVF package if files are directly in the bucket (no folders). Added GetGCSObjectPathElements func to be used when an actual file path is needed
=> Fixes for handling GCS paths

daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Turns out google-osconfig-agentgoogle-cloud-sdk is not a real package.
Fixes installed packages test.
=> fix typo in ks_helpers

gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Changed CentOS 6 OVF import e2e test to cover importing directly from a bucket (no sub-directories) as customers are performing this type of import from time to time.
=> OVF import e2e test directly from a bucket

daisy_workflows/image_build/debian/build.py, daisy_workflows/image_build/debian/build_fai.py, daisy_workflows/image_build/debian/debian_10_fai.wf.json, daisy_workflows/image_build/debian/debian_9.wf.json, daisy_workflows/image_build/debian/debian_fai.wf.json, daisy_workflows/image_build/debian/fai_config/packages/GCE_SPECIFIC_NGE
Debian 9:
* Update bootstrap-bz parameter to full path, rather than hash only.
* Add install_nge flag that updates bvz path (could be changed to update bvz manifest and keep using zmarano fork, but I don't have access to it)
Debian 10:
* Add NGE class and flag to enable it
=> Debian workflow changes for NGE

daisy_workflows/image_import/windows/translate.ps1
Fix windows translate script to print "Translate complete" when sysprep is run. Also mark the image as BYOL if sysprep is run and BYOL licensing was selected.
=> Fix windows translate script to print "Translate complete" when sysprep is run

daisy_integration_tests/image_export_vmdk_given_size.subwf.json
The image export tests create terabyte-sized files, which are costly for storage, and are not required when the test was successful. This change deletes the image files if the test passed. 
- Ran `daisy_integration_tests/image_export_vmdk_given_size_10gb.wf.json` and verified that the two image files were removed. (created-by-export-test-given-size.vmdk and the image in outs)
=> Test cleanup: Delete exported disk image if export is successful.

daisy_workflows/image_import/enterprise_linux/translate.py
This improves error messaging for two failure modes, where the user currently sees an error such as 
1. Incorrect `--os` such that EL's translate.py gets executed. Current error message is `TranslateFailed: error: command:`.
2. Correct `--os` using BYOL, but importing a VM that doesn't have a subscription. Current error message is `TranslateFailed: error: command: Importing GPG key 0xA7317B0F`.
Testing
- Ran:
- daisy_integration_tests/centos_6_qcow2_translate.wf.json
- daisy_integration_tests/centos_7_qcow2_translate.wf.json
- Verified error message by importing a RHEL 6 image that didn't have a subscription as BYOL.
- Successfully imported same image without using BYOL.
=> Improve error message for failed EL translation.

gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Dup instance name lead to test conflict. Fix it.
It potentially can be the reason of deleted subnet. Will keep digging that.
=> [ovf e2e] fix dup ovf test name

daisy_integration_tests/daisy_e2e.test.gotmpl, daisy_integration_tests/image_import_and_translate_ova_with_spaces_in_vmdk.wf.json, daisy_integration_tests/image_import_and_translate_ova_with_spaces_in_vmdk_filename.wf.json, daisy_workflows/image_import/import_image.sh
Prior to this fix, if a user imported an OVA that contained "The Image Name.vmdk", they'd see the following logs and errors:
```
Import: Unpacking VMDK files from ova.
tar: The: Not found in archive
tar: Image: Not found in archive
tar: Name.vmdk: Not found in archive
tar: Exiting with failure status due to previous errors
Import: New source file is The Image Name.vmdk
...
Could not open '/daisy-scratch/The Image Name.vmdk': No such file or directory
```
- Ran the new integration test
=> Image import: Support OVAs where enclosed vmdk has spaces.

daisy/image.go, daisy/resource.go, daisy/resource_registry.go, daisy/resource_registry_test.go, daisy/step_create_disks.go, daisy/step_create_firewall_rule.go, daisy/step_create_forwarding_rule.go, daisy/step_create_images.go, daisy/step_create_instances.go, daisy/step_create_machine_images.go, daisy/step_create_networks.go, daisy/step_create_subnetworks.go, daisy/step_create_target_instance.go
A resource should be deleted by cleanup only when it's created by the workflow.
Now, there are 2 bugs which can lead to undesired deletion:
1. ovf import: ovf import set "forceCleanup" to "True". It conflicts with original design of "NoCleanup", which is used by regURL to mark placeholder resource as skipping cleanup. The problem: when ovf import failed, it will try deleting all used resources, including subnet, network, etc. We need to avoid this by distinguish whether the resource is a placeholder resource. The correct way is to check "resource.creator == nil".
2. daisy: for any daisy workflow, the create_resource step (for example, CreateDisks) will delete the created resource when the workflow failed on it. The problem is, when multiple workflows run in parallel to create a resource …
=> [ovf import / daisy] avoid undesired deletion

gce_image_import_export_tests.Dockerfile
e2e now is failing. Error:
Error running cmd: fork/exec ./gce_vm_image_export: permission denied
WORKDIR should be "/" in this docker build file. Fixing it.
=> fix gce_image_import_export_test docker permission

daisy_workflows/image_import/import_image.sh
The message is intended to help with two common failures in VMDK decoding:
1. The user uploads the descriptor file, but not the image itself
2. The user uploads one VMDK from a set of split VMDKs
=> Image import: Add hint for when VMDK decoding fails.

daisy_workflows/image_build/enterprise_linux/kickstart/el6-post.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg, daisy_workflows/image_build/enterprise_linux/ks_helpers.py
these files are already being used as templates, so might as well declare packages there to be obvious. keep the replacement for packages that vary, but don't vary based on distro.
after removing legacy guest we find that python packages need to be explicitly installed. start doing that now.
=> Python rhel8

cli_tools/common/utils/validation/validation_utils.go, cli_tools/gce_ovf_import/main.go, cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator.go, cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator_test.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
The original PR that introduced the hostname flag somehow failed to call validateFqnd on params.Hostname in ovf_import_params_validator
=> OVF import: validate hostname flag

daisy_workflows/export/image_export.wf.json, daisy_workflows/export/image_export_ext.wf.json
We allowed fallback for worker disk and buffer disk. However, we didn't do that for source disk. Let's add this setting to avoid more ssd quota issues.
=> [export ssd quota] allow fallback to pd-standard for source disk

daisy_workflows/image_import/import_from_image.wf.json
Added missing default timeout for import from image workflow, the same as other import workflows.
=> Added missing default timeout for import from image workflow

cli_tools/common/utils/daisy/daisy_utils.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go, daisy_integration_tests/centos_8_translate.wf.json, daisy_integration_tests/daisy_e2e.test.gotmpl, daisy_integration_tests/scripts/post_translate_test.sh, daisy_workflows/image_import/enterprise_linux/translate.py, daisy_workflows/image_import/enterprise_linux/translate_centos_8.wf.json
Adds a workflow for importing CentOS-8, and wires the workflow through the OVF wrapper and the image import wrapper. 
* Created a VM using vmware, and imported as a VMDK and OVF.
* Ran the new integration test.
* Ran the existing CentOS tests: centos_6_qcow2_translate.wf.json and centos_7_qcow2_translate.wf.json
=> Add support for importing CentOS-8.

daisy_workflows/image_import/ubuntu/translate.py
Currently, if `cloud-init init` fails, the user sees "error: "sh: Traceback (most recent call last):". 
I'm currently running the following test and will ensure that it passes before I push the change:
`daisy -zone=us-central1-b -project=compute-image-tools-test daisy_integration_tests/ubuntu_1604_import_and_translate.wf.json`
=> Improve error message when 'cloud-init init' fails.

cli_tools/common/utils/storage/resource_location_retriever.go, cli_tools/common/utils/storage/resource_location_retriever_test.go
Fix occasional flakiness for image storage location retrieving where dual regions (NAM4/EUR4) are returned instead of multi-regions (US/EU) for regions belonging to both.
=> Fix flakiness for image storage location retrieving

cli_tools/gce_vm_image_import/importer/importer.go
Currently we tell users how to import a file that was exported from GCP. This adds a hint for gzip files that contain disk images from other systems.
=> Clarify how to import a disk image that is contained within a gzip compressed file.

daisy_integration_tests/scripts/post_translate_test.sh
The Linux post-translate test assumes that cloud-init has already run (and finished) by the time the test runs, which isn't always true. 
1. Ran `daisy_integration_tests/centos_6_qcow2_translate.wf.json`, which passed.
2. Created an instance using the translated cent6 image as the boot disk, and `post_translate_test.sh` as the startup script
3. Cycled the instance about 20 times and verified that the test passed each time.
=> Allow post-translate test to wait until cloud-init finishes its startup work.

daisy_integration_tests/scripts/post_translate_test.sh, daisy_workflows/image_import/enterprise_linux/translate.py
Two fixes:
1. Tune the `ping` test to allow longer for the response.
2. Add retries when installing packages using yum.
Testing:
1. Ran `daisy_integration_tests/centos_6_qcow2_translate.wf.json`
2. Ran `daisy_integration_tests/ubuntu_1404_img_translate.wf.json`
=> Improve stability of import integ tests and enterprise linux installs.

cli_tools/gce_ovf_import/main.go, cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, gce_ovf_import_tests/test_suites/ovf_instance_import/ovf_import_test_suite.go
Fixed OVF import e2e tests failing due to multiple tests sharing single Cloud Build and temporary resources getting cleaned up by shorter running tests thus failing longer running tests. The fix was to provide buildID override that can be utilized by E2E tests.
=> Fixed OVF import e2e tests failing

daisy_workflows/image_import/suse/translate.py
SLES image import: use 'sle-module-public-cloud/12/x86_64' subscription for any SLES 12.x, not only 12.5.
=> SLES 12.x image import fix, not only 12.5

daisy_integration_tests/scripts/run_daisy_and_check_logs.sh
Fix Daisy cloud logging E2E test by using an embedded workflow due to git repo not being cloned anymore on the worker instance.
=> Fix Daisy cloud logging E2E test by using an embedded workflow 

gce_ovf_import_tests/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, gce_ovf_import_tests/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Fixed OVF instance import E2E tests not being reported in the test grid due to machine image import overwriting the test results (due to the shared testSuiteName)
=> Fixed OVF instance import E2E tests not being reported

daisy_workflows/image_import/windows/run_startup_scripts.cmd, daisy_workflows/image_import/windows/run_startup_scripts_x86.cmd
When installing google-compute-engine-metadata-scripts, script "run_startup_scripts.cmd" will be replaced.
Enforce a verify & reinstall to prevent skipping installing it. That bug happened when google-compute-engine-metadata-scripts exists.
The bug leads to a infinite loop of calling old run_startup_scripts.cmd.
=> [image-import] windows translation: reinstall google-compute-engine-metadata-scripts to prevent dead loop

daisy_integration_tests/daisy_e2e.test.gotmpl, daisy_integration_tests/el_import_dont_use_proxy.wf.json, daisy_workflows/image_import/enterprise_linux/translate.py
The test image `cent-7-http-proxy` specifies HTTP proxies in two ways:
1. Sets an HTTP proxy using the environment variable `http_proxy` in `/etc/profile`
2. Sets an HTTP proxy within `/etc/yum.conf`.
Testing:
- Ran new integration test
- Ran `centos_8_translate.wf.json` integration test
=> Allow EL import to continue if image's HTTP proxy is unreachable.

daisy_workflows/image_import/windows/translate_bootstrap.ps1
Second attemot to detect and refrain from modifying BCD store if the
imported disk is GPT partitioned. Original PR:
https://github.com/GoogleCloudPlatform/compute-image-tools/pull/976
Tested on WS 2019 UEFI/GPT and MBR disks, including booting and sysprepping the resulting image.
=> [image_import] Skip BCD rewrite for GPT disks

daisy_workflows/image_import/windows/translate.ps1
Creation of a GCP VM from an imported Windows image results in two devices
that do not have default drivers included in Windows. These are the balloon
device and pvpanic device.
Addition of 32-bit Windows Client import workflows resulted in misnaming
the Install-Packages function to Install-32bitPackages. This has been
corrected.
https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1020
=> [image_import] Include default device drivers

daisy_workflows/image_import/windows/translate.ps1
- balloon and pvpanic driver installs fail for WS 2008R2 and W 7
- although Windows does not include default drivers for these devices,
not including them does not substantially impact functionality on GCP
- we are investigating this error, and plan to fix
=> [image_import] Suppress nonessential install errors

daisy_workflows/image_import/suse/translate.py, daisy_workflows/linux_common/utils/diskutils.py
When importing SLES, we need to install the public cloud module to get access to the GCE packages. Prior to this change, if the import failed here, the user would see a failure message such as `Command failed: SUSEConnect -p sle-module-public-cloud/12/x86_64: command: `
This change adds failure detection for three failure modes:
1. The worker instance does not have internet connectivity (SUSEConnect makes an RPC to the SLES central entitlement server.)
2. There is a valid subscription, but the subscription doesn't allow access to the sle-module-public-cloud product.
3. There is not a valid subscription.
=> Improve error messaging when SUSEConnect fails.

cli_tools/common/utils/daisy/daisy_utils.go, cli_tools/go.mod, cli_tools/go.sum, daisy/common.go, daisy/instance.go, daisy/step_create_instances.go, daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/disk_export_ext.wf.json
It's reported by b/149243707 [p1]
Failed to export because org policy denied all external IPs.
There is actually no need to access externals for export. So, just simply retry without external IP when the failure code matches.
This mechanism works for import as well. Will test for import later, and then change the workflow accordingly.
=> [export] auto retry CreateInstances when external IP is denied by organization policy

cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_export/exporter/exporter_test.go, cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/importer_test.go
This was motivated by imports that failed when the subnetwork paramater
reached daisy still having a leading space character.
In addition, this updates the usage of assert.Equal, which expects the first parameter to the be the expected value.
=> Trim import parameters of leading and trailing whitespace before sending to Daisy.

cli_tools/common/utils/compute/zone_validator.go
Wrap Compute API error in Daisy error to prevent exposing PII data. Also, check if it's Compute Engine API disabled and report it as such.
=> Wrap Compute API error in Daisy error to prevent exposing PII data

daisy_workflows/image_import/suse/translate.py
Here's the output when I ran an import with opensuse-15:
`TranslateFailed: error: Import of opensuse-15.0 is not supported. The following versions are supported: [opensuse-15.1, sles-15.1, sles-12.5]`
=> Add clarifying message if SUSE version is not supported.

daisy_workflows/image_import/suse/translate.py
This reverts commit 9a5cb7b7d72d4f74d65a48e96c9be2ea1d8e3def.
Reverting this while we continue to test versions of SLES 12 below 12.5.
=> Revert "SLES image import: use 'sle-module-public-cloud/12/x86_64' subscription for any SLES 12.x, not only 12.5. (#1108)"

daisy_workflows/image_import/enterprise_linux/translate.py
Fixes #1143.
When there's a command error, pyguestfs surfaces the first line of stderr.  Since `dracut` is set to verbose logging, the information surfaced to the user is not necessarily relevant to the underlying error.
This change reduces dracut's logging from verbose to fatal-only. In doing so, it ensures that the surfaced error message is relevant to the actual failure.
```
TranslateFailed: error: command: No '/dev/log' or 'logger' included for syslog logging
```
```
TranslateFailed: error: command: /lib/modules/3.10.0-1062.el7.x86_64//modules.dep is missing. Did you run depmod?
```
- The error message [comes from dracut](https://github.com/dracutdevs/dracut/blob/master/dracut.sh#L1074) 
- The modules.dep error isn't reproducible on EL6, and the signature of `dracut` doesn't have the …
=> Ensure that pyguestf surfaces dracut's error message.

daisy_workflows/export/export_disk.sh
Problem: gce_export failure was not detected in an e2e test because "$?" was used twice in script.
Resolve: Store it in a var to use twice.
=> [export] fix gce_export result usage

daisy_workflows/image_import/windows/translate_bootstrap.ps1
This happened when importing a non-uefi windows-2019 image: the secondary disk was offline, so it failed.
Just simply bring all offlined disk online to fix. Manually tested and it passed.
=> [image-import] windows: bring disks online before translate

daisy_integration_tests/scripts/post_translate_test.sh
Failing to ping google.com has caused some tests to fail intermittently lately. 
Testing:
* Ran `daisy_integration_tests/centos_7_qcow2_translate.wf.json`
=> Add retries for pinging google.com and metadata.google.internal.

daisy_integration_tests/opensuse_15_1.wf.json, daisy_integration_tests/sles_12_5_byol.wf.json, daisy_integration_tests/sles_15_1_byol.wf.json
This PR sets the timeout to 30 minutes (which I think was my intent in the first place, since I put a timeout of 30 minutes on `WaitForInstancesSignal`)
The SUSE/SLES tests are a bit different, in the `CreateInstance` step starts with the translated image, rather than the intermediate PD. As such, it takes a bit longer than the other integration tests, since we have to create the PD, and hence we're occasionally running into the 10 minute default step limit.
*In draft mode while the three tests run*
=> Allow time for SLES integ tests to create PD from image.

daisy_workflows/image_import/suse/translate.py
We've had some recent errors in tests where `SuseConnect -p` was failing without a message, even though `SUSEConnect --status` says the registration is active.
=> Add small retry for installing products using SuseConnect.

cli_tools/diagnostics/google-compute-engine-diagnostics.goospec, cli_tools/diagnostics/main_windows.go, cli_tools/diagnostics/main_windows_test.go
There's test failure on [testgrid](https://testgrid.corp.google.com/windows-image#win-prod), seems due to surfacing the trivial errors, so change it to log.Printf instead of log.Fatalf.
Also Ning found the dumping RDP setting is not working, so figured out that GCE Agent was not running diagnostics.exe inside the `C:\Program Files\Google\Compute Engine\diagnostics\`  folder, so need to get the diagnostics.exe runtime directory path and pass it.
=> Fixes for dumping RDP settings and Testgrid failure

cli_tools/diagnostics/main_windows.go
In the `gatherLogs()` function, it expects each log collector put either logFilePaths in logFolder channel or errors in errCh channel. So shouldn't have done nothing and return, as it caused the goroutines sleeping and failing the [tests](https://g3c.corp.google.com/results/invocations/0f83dcc3-3b68-4893-9b5d-d052b448b92b/targets/%2F%2Fcloud%2Fcluster%2Ftesting%2Fwindows:export_logs_test/tests;group=__main__.ExtractLogsTest;test=testGatherLogsCorrectly_WithOrWithoutKubernetesLog;row=3).
=> Fix the all goroutines asleep - deadlock

cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/importer_test.go, cli_tools/gce_vm_image_import/main.go, daisy_workflows/image_import/debian/translate_debian_8.wf.json, daisy_workflows/image_import/debian/translate_debian_9.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_6.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_7.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_8.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_licensed.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json, daisy_workflows/image_import/freebsd/translate_freebsd.wf.json, daisy_workflows/image_import/import_and_translate.wf.json, daisy_workflows/image_import/import_from_image.wf.json, daisy_workflows/image_import/suse/translate_opensuse_15.wf.json, daisy_workflows/image_import/suse/translate_sles_12_byol.wf.json, daisy_workflows/image_import/suse/translate_sles_15_byol.wf.json, daisy_workflows/image_import/suse/translate_sles_sap_12_byol.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu_1404.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu_1604.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu_1804.wf.json
Testing:
Ran four imports, and confirmed that sysprep ran on (1).
1. Windows 2019, `-sysprep_windows=true`
2. Windows 2019, no `-sysprep_windows` specified
3. Ubuntu 16.04, `-sysprep_windows=true`
4. Ubuntu 16.04, no `-sysprep_windows` specified
=> Add sysprep_windows param to image import wrapper.

daisy/compute/compute.go
We observed a recent failure of `APIError: step "wait-for-translate" run error: APIError: unexpected instance status "REPAIRING"`. Based on GCE's [instance lifecycle](https://cloud.google.com/compute/docs/instances/instance-life-cycle), an instance is able to recover from the repairing step.
=> Allow instances to attempt repair.

daisy/common.go, daisy/compute/compute.go, daisy/compute/test_client.go, daisy/disk.go, daisy/firewall_rule.go, daisy/forwarding_rule.go, daisy/image.go, daisy/instance.go, daisy/instance_test.go, daisy/license.go, daisy/machineimage.go, daisy/machinetype.go, daisy/network.go, daisy/region.go, daisy/resource.go, daisy/resource_registry.go, daisy/step_deprecate_images_test.go, daisy/subnetwork.go, daisy/target_instance.go, daisy/test_common_test.go, daisy/validate.go, daisy/workflow.go, daisy/zone.go, mocks/mock_compute_client.go
Put resource cache inside workflow to avoid race condition.
This problem breaks tests which run workflows in parallel.
If somebody run workflow in parallel in one program, it can also happen, even though there isn't a case so far.
=> [daisy] Put resource cache inside workflow to avoid race condition

daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg
=> Remove epel from EL7 builds. It is no longer needed for the base image

daisy/cli/main.go, daisy/daisy_test_runner/main.go, daisy/step_includeworkflow.go, daisy/step_sub_workflow.go, daisy/test_data/test.wf.json, daisy/workflow.go, daisy/workflow_test.go
Reverts GoogleCloudPlatform/compute-image-tools#1177
It's not the best solution for windows-upgrade "rollback" workflow. Revert it to avoid publishing unnecessary functionalities.
=> Revert "[daisy] populate daisy input vars early to support non-string types"

cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/importer_test.go, cli_tools/gce_vm_image_import/importer/source.go, cli_tools/gce_vm_image_import/importer/source_test.go
This consolidates the validations for sourceImage and sourceFile and provides a consistent API for dealing with them.
Additionally, this performs syntactic validation of sourceImage.
=> Don't allow sourceImage to be a GCS path.

daisy/disk_test.go, daisy/snapshot.go, daisy/snapshot_test.go, daisy/step_create_snapshots.go, daisy_integration_tests/step_create_snapshots.wf.json
Added unit tests and integration tests for snaphosts.
Logic change: link needs to be adjusted before creating the snapshot. Otherwise, the link can be wrong because its project must be the same as corresponding disk, no matter whether user customized "Project" property.
=> [daisy] snapshots: add tests; adjust populate logic

daisy/step_create_snapshots.go
This is a fix. Originally we get project from disk.Project, however it can be unavailable in some corner cases, for example the disk is not populated in test env
=> [daisy] step_create_snapshot: extract project name from source disk's URI

daisy_workflows/image_import/debian/translate.py, daisy_workflows/image_import/ubuntu/translate.py, daisy_workflows/linux_common/utils/common.py
In addition, consolidates series of apt requests into a single batch operation.
Running import integration tests in process:
* Debian 8, 9
* Ubuntu 16.04, 18.04
=> Use Python guest agent for Debian 8.

prowjobs_cloudbuild.yaml
The latest release of kaniko-project/executor broke our builds due to permission check issues. Using debug/fix release to verify this is the actual cause. Only for compute-image-tools-test for now
=> Use kaniko-project/executor:debug-edge for builds

cli_tools_e2e_test/go.mod, gce_image_import_export_tests.Dockerfile, gce_ovf_import_tests.Dockerfile
A couple of changes:
1. update cli_e2e_test_tools to use the latest modules.
2. update e2e's docker files to contain the future's common lib.
3. removed redundant "go get" from docker files.
It optimized the build and fixed the latest dependencies
=> update cli_e2e_test_tools to use the latest modules

cli_tools/common/distro/distro.go, cli_tools/common/distro/distro_test.go, cli_tools/gce_vm_image_import/importer/errors.go, cli_tools/gce_vm_image_import/importer/importer.go, daisy_workflows/image_import/debian/translate_debian.wf.json, daisy_workflows/image_import/enterprise_linux/translate_el.wf.json, daisy_workflows/image_import/freebsd/translate_freebsd.wf.json, daisy_workflows/image_import/suse/translate_opensuse_15.wf.json, daisy_workflows/image_import/suse/translate_sles_12_byol.wf.json, daisy_workflows/image_import/suse/translate_sles_15_byol.wf.json, daisy_workflows/image_import/suse/translate_sles_sap_12_byol.wf.json, daisy_workflows/image_import/suse/translate_suse.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json, daisy_workflows/linux_common/utils/diskutils.py
This adds a new module, `cli_tools/common/distro`, that is used to determine whether the detection result matches the user's input. This will get used in the upcoming OS detection project.
Notably, the module doesn't (yet) support Windows. That's a tactical choice, since currently we only perform detection on Linux, and unlike Linux, in Windows the user-facing version strings are different than the internal version strings [1]. So, I'm leaving implementation of Windows for when it's needed, as that will help define the interface.
Lastly, if the detection result doesn't match the user's input, then we replace the current error with a new one. I like this approach, since it improves the signal-to-noise ratio, and since the Daisy error is logged a few lines before. 
Here are the last few log …
=> If translation fails, alert user of what was detected on disk.

prowjobs_cloudbuild.yaml
Revert: Using debug/fix release of kaniko-project/executor that broke our build pipeline (latest is now fixed)
=> Using v0.22.0 release of kaniko-project/executor

daisy_workflows/image_import/windows/translate.ps1
Fix firewall rule for RDP not being added for Japanese (and probably any other non-English) variant of Windows.
=> Fix firewall rule for RDP not being added for non-English Windows

cli_tools_cloudbuild.yaml
Using v0.22.0 release of kaniko executor in compute-image-tools to lock in this version instead of risking using latest in the future.
=> Using v0.22.0 release of kaniko executor in compute-image-tools

cli_tools/common/utils/logging/service/daisy_loggable.go, cli_tools/common/utils/logging/service/daisy_loggable_test.go, cli_tools/gce_ovf_import/main.go, cli_tools/gce_vm_image_export/main.go, cli_tools/gce_vm_image_import/main.go
This was prompted by a failed OVF integration test. The import failed while copying a VMDK to GCS. A workflow was never created, and a subsequent call to workflowLoggable.wf caused a seg fault.
=> Only create workflowLoggable if workflow is non-nil.

daisy_integration_tests/scripts/post_translate_test.sh, daisy_workflows/image_import/suse/translate.py
This was motivated by failed SUSE 15.1 integ tests. The root cause was that cloud-init was marked as optional, and when it wasn't installed, the iputils transitive dependency wasn't added. The integration test expected that `ping` was available, so when cloud-init isn't installed, `ping` wasn't available (assuming the original image didn't have it).
Key changes:
* Install all packages in a single zypper operation.
* Increase retry time for `SUSEConnect -p` from 60 seconds to 5 minutes; I've observed that invocations (failing and passing) were exceeding 60 seconds for a single invocation.
* Remove the concept of optional packages, since this causes non-deterministic behavior.
* Remove cloud-init
* Remove google-cloud-sdk -- the package isn't available in SUSE repos.
=> SUSE import: Don't install cloud-init; require iputils.

daisy_workflows/image_build/sqlserver/sql-2012-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2012-standard-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2012-web-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2014-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2014-enterprise-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2014-standard-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2014-web-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-enterprise-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-enterprise-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2019-enterprise-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2019-standard-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2019-web-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql_install.ps1
- Install SQL Server Management studio on all Windows Server base images, except Core
- Update description and Guest OS features to expect UEFI firmware
- Test that images build and run successfully on UEFI firmware
=> Build SQL Server on Windows Server UEFI

cli_tools/gce_windows_upgrade/upgrader/workflows.go
There is a bug when executing windows upgrade from docker image: since "current path" is uncertain, it failed to find "./xxxx.ps1". We have to use "currentExecutablePath" to identify the script's path.
=> [windows upgrade] use executable path to generate script path

daisy_workflows/image_import/enterprise_linux/translate.py
As a result of [setuptools sunsetting Python 2.7](https://github.com/pypa/setuptools/issues/1458), we need to ensure that pip is at least version 9. When python27 is installed in CentOS 6.10, pip is at 8.1.2.
=> EL6 import: Ensure pip is updated.

daisy_workflows/image_import/windows/translate.ps1
- The GCEStartup task does not run at startup on Windows 10 32-bit. Reinstall the package to recreate the task.
=> Avoid import failures by recreating GCEStartup task

daisy_workflows/image_build/debian/fai_config/scripts/10-gce-clean
debian 10 images don't have /etc/machine-id populated on boot. create an empty file to trigger its population at boot time.
after this change, the following lines are in the serial console:
```
[    5.101277] systemd[1]: Initializing machine ID from KVM UUID.
[    5.103367] systemd[1]: Installed transient /etc/machine-id file.
```
=> leave empty machine-id file for autogen

cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
Fixed nil pointer dereference breaking OVF import if OperatingSystem.OSType is not defined in OVF descriptor.
Fixes #1235
=> Fixed nil pointer dereference breaking OVF import

daisy_workflows/image_import/import_disk.wf.json, daisy_workflows/image_import/import_image.sh
When an image file contains square brackets ([]), we've observed the error:
`Destination (/daisy-scratch/file-name[stuff-in-brackets].vmdk) must match exactly 1 URL`
The error is thrown from our call to gsutil cp[1], and is a result of gsutil cp's wildcard feature[2]. The following four characters are interpreted as wildcard characters: []?*.
This change utilizes the copy of the image that daisy creates [3], which has a sanitized name.
1. ⁠https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy_workflows/image_import/import_image.sh#L125
⁠2. https://cloud.google.com/storage/docs/gsutil/addlhelp/WildcardNames
3. https://github.com/GoogleCloudPlatform/compute-image-tools/blob/115ddd50514d903cfc2b2c96b0bad39c369f60f0/daisy_workflows/image_import/import_disk.wf.json#L37 …
=> Use disk file from daisy's scratch path.

daisy_workflows/image_import/import_disk.wf.json, daisy_workflows/image_import/import_image.sh
This caused a regression for OVA support in import_image.sh, which
depends on inspecting the original filename's extension.
=> Revert "Use disk file from daisy's scratch path."

daisy/step.go, daisy/workflow.go, daisy/workflow_test.go
Added custom cancel reason to Daisy workflow. This will allow us to provide different error messages when workflows are canceled for different reasons. For example, timed out vs. canceled by users.
=> Added custom cancel reason to Daisy workflow. 

daisy_workflows/image_import/import_image.sh, daisy_workflows/image_import/inflate_file.wf.json
gsutil supports control characters, such as wildcards, that can't be escaped [1]. This change does the following:
1. Ignore the original filename (on the worker's disk, it will appear as `source_disk_file`)
2. Make OVA checking more robust:
* Use magic numbers to check for a tar archive
* Check contents for an ovf and vmdk file
Testing:
* Ran one of the OVA tests that was failing prior to the fixes described in (2).
1. https://cloud.google.com/storage/docs/gsutil/addlhelp/WildcardNames
=> Sanitize control characters from image filename.

test-infra/prow/config.yaml
Remove obsolete FreeBSD images and replace by the more recent ones.
This fix prow boot tests.
=> test-infra: update FreeBSD images

cli_tools/gce_windows_upgrade/upgrade_script_2008r2_to_2012r2.ps1, cli_tools/gce_windows_upgrade/upgrader/workflows.go
fix 2 problems:
1. Adjust the startup script to launch post-upgrade step. "upgrade.ps1" needs to be executed again after setup.exe is done, so we move the output of "windows_upgrade_current_version" to the last line.
2. To ensure log privacy, we need to set log process hook for all the workflows.
=> [windows upgrade] post-upgrade step; log privacy

cli_tools/gce_vm_image_import/importer/data_disk_processor.go, cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/importer_test.go, cli_tools/gce_vm_image_import/importer/processor.go, cli_tools/gce_vm_image_import/importer/validator.go, cli_tools/gce_vm_image_import/importer/validator_test.go
Prior to the #1227, import failed early when an image name was already used. Following #1227, the failure occurred after inflation, which introduces a significant delay.
Example invocation:
```
➜   ./main -image_name ubuntu  \
-data_disk -client_id  edens-test \
-source_image projects/compute-image-tools-test/global/images/debian-8-translate \
-project=edens-test
[import-image] 2020/06/16 12:07:40 the image "ubuntu" already exists. Please remove it, or pick a name that isn't already used
```
The failure message appears instantly (at least to my eyes!).
=> Ensure destination image doesn't exist prior to running import.

daisy_workflows/image_import/import_image.sh, daisy_workflows/image_import/inflate_file.wf.json
This change breaks multi-disk OVF imports.
=> Revert "Sanitize control characters from image filename. (#1244)"

cli_tools/common/utils/logging/service/log_entry.go, cli_tools/gce_windows_upgrade/main.go
1. adjust field sequence
2. remov "project" and "obfuscatedProject"
to be align with compute_image_tools_log.proto.
If not align, the log will be thrown.
=> [windows upgrade] firelog: adjust field sequence

daisy_workflows/image_import/inflate_file.wf.json
This change allows organizations that [disable external IPs](https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address#disableexternalip) to run image import.
=> Don't allocate an external IP during inflation.

cli_tools/gce_image_publish/publish/publish.go, cli_tools/gce_image_publish/publish/publish_test.go
long overdue, since we do not save the initial config into the image tarball, aka, if you export an image and re-publish that, the VM won't be able to boot up properly.
(bug 143374751 if you want more context)
/assign @rkolchmeyer @hopkiw @adjackura 
fixes https://github.com/GoogleCloudPlatform/compute-image-tools/issues/1148
=> Support ShieldedInstanceInitialState in the publish workflow

cli_tools/diagnostics/main.go
As per our discussions with customers, need to improve the output status / progress to the serial port the following, e.g.:
- $DATE-TIME$ Diagnostics: logs uploading to [[bucket URI]].
- $DATE-TIME$ Diagnostics: logs export completed.
=> Improve the logging of diagnostics

cli_tools/gce_vm_image_import/importer/inflater.go, cli_tools/gce_vm_image_import/importer/inflater_test.go, daisy_workflows/image_import/inflate_file.wf.json
Following #1262, two tests that used custom subnetworks failed. Since tests didn't enable privateIpGoogleAccess on their subnetwork [1], the inflation instance failed when calling GCP APIs.
This PR ensures that we create external IPs *unless* the user enables NoExternalIP.
1. https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks/insert
=> During inflate, allocate external IP unless NoExternalIP is set.

daisy/workflow.go
when building this with bazel I got
```
compilepkg: nogo: errors found by nogo during build-time code analysis:
/private/var/tmp/_bazel_senlu/1693ea471a90a355976fdb5d7dafa66b/sandbox/darwin-sandbox/1278/execroot/__main__/external/com_github_googlecloudplatform_compute_image_tools_daisy/workflow.go:496:9: impossible condition: nil != nil
```
=> fix err typo, otherwise it won't be built in bazel

cli_tools/gce_windows_upgrade/upgrader/upgrader.go, cli_tools/gce_windows_upgrade/upgrader/upgrader_test.go, cli_tools/gce_windows_upgrade/upgrader/utils.go, cli_tools/gce_windows_upgrade/upgrader/validators.go, cli_tools/gce_windows_upgrade/upgrader/validators_test.go
This is requested by tech writer. Google standard term is boot disk other than OS disk.
=> [windows upgrade] rename 'OS disk' to 'boot disk' on user interface

cli_tools_e2e_test/common/utils/utils.go, cli_tools_e2e_test/gce_windows_upgrade/test_suites/windows_upgrade/windows_upgrade_test_suite.go
CPU resource will be exhausted if we don't delete the test instance proactively. Even the cleanup tool will do the cleanup, the garbage is still too much and it has caused the quota problem yesterday.
=> [windows upgrade e2e] delete instance after test

daisy_workflows/export/export_disk_ext.sh
out=$(blabla) works in most of the cases, and it also worked for gsutil before. However, starting from 1 week ago, it's not working anymore. The reason is that "2>&1" caused gsutil blocked. Maybe the new version of gsutil have something to do with the stderr/stdout pipe.
So we use a gsutil_err.txt to hold the stderr output instead.
=> fix export

daisy_workflows/export/export_disk_ext.sh
The ImageExport for large image is still blocked. Even we 'cat' the output with some special chars, it still stuck.
Move the 'cat' to be after the 'export success' so the "waitForInstanceSignal" can recognize the export has finished.
Manually test 3 time and they passed.
=> [export] adjust 'echo' sequence

daisy/step_resize_disks.go
Currently, the resize-disk commmand can only take integer input and
cannot parse variables in a workflow. In order to allow variables in
this command, a new field "SizeGbVar string" is added, and then its
value is converted into int64 and stored in the original "SizeGb int64"
field. In this way, everything else except the ResizeDisk struct fields and
populate function remains untouched.
=> daisy/: added variable parsing to resize-disk.

cli_tools_e2e_test/common/logging/logging.go, cli_tools_e2e_test/gce_image_import_export/main.go, cli_tools_e2e_test/gce_image_import_export/test_suites/import/cli_tests.go, cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go, cli_tools_e2e_test/gce_image_import_export/test_suites/import/post_translate_test.sh, cli_tools_e2e_test/gce_image_import_export/test_suites/import/post_translate_test.wf.json, gce_image_import_export_tests.Dockerfile
Historically, the majority of import tests are run as daisy integration tests, and therefore bypass the wrapper logic. This change adds a suite to the cli_tools_e2e_test framework that focuses on import logic. The existing e2e suite is recharacterized as "CLI tests", since it focuses on the API contracts of the CLI tools.
Key features, compared to existing solutions for image import tests:
1. Support for negative tests, which verify the output of error messages
1. Efficient test representation (compared to an entire JSON document)
To keep the PR simple, I added two tests to illustrate how the system works. I'll do a subsequent PR that migrates the existing integ tests in `daisy_integration_tests` to here.
Lastly, this adds some utilities to convert between daisy logs, standard library …
=> An image import suite focused on translation logic.

cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go, daisy_workflows/image_import/import_image.sh
#1283 caused a regression for OVF imports that contain multiple disks. When performing a multi-disk import, a user would see: "ImportFailed: Failed to resize disk. The Compute Engine default service account needs the role: roles/compute.storageAdmin"
This PR fixes the regression by:
1. Update import_image.sh to validate its required parameters.
2. Update OVF import to include the sizes of the disks that its passing to import_image.sh.
=> Pass inflation disk sizes during OVF data disk import.

cli_tools/common/disk/inspect.go, cli_tools/daisycommon/daisy_utils.go, cli_tools/gce_vm_image_import/importer/args.go, cli_tools/gce_vm_image_import/importer/args_test.go, cli_tools/gce_vm_image_import/importer/bootable_disk_processor.go, cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go, cli_tools/gce_vm_image_import/importer/inflater.go, cli_tools/gce_vm_image_import/importer/inflater_test.go
The `gcr.io/compute-image-tools/gce_vm_image_import:latest` docker image was at runtime with an error of:
```
[import-image]: 2020-07-20T19:15:30.92Z open daisy_workflows/image_import/inspection/inspect-disk.wf.json: no such file or directory
```
This occurred since loading of `daisy_workflows/image_import/inspection/inspect-disk.wf.json` assumed that the directory `daisy_workflows` was available in the process's working directory. This isn't true for the  `gcr.io/compute-image-tools/gce_vm_image_import:latest`  image. It has a directory layout of:
```
/gce_vm_image_import
/daisy_workflows
/workspace
...
```
When Cloud Build invokes `gce_vm_image_import`, it sets the working directory to  `/workspace`, and the daisy_workflows directory is not a child of the current working directory. [1] …
=> Load disk inspection workflow relative to daisy_workflows directory.

gce_vm_image_import.Dockerfile
Prior to this change, executing `gce_vm_image_import` would yield errors such as:
```
[import-image]: 2020-07-20T21:41:30.558Z failed to read GCS file when validating resource file: unable to open file from bucket "edens-images", file "win2008r2-all-updates-disk1.vmdk": Get "https://storage.googleapis.com/edens-images/win2008r2-all-updates-disk1.vmdk": x509: certificate signed by unknown authority
```
1. Built gce_vm_image_import.Dockerfile: `docker build -f gce_vm_image_import.Dockerfile . -t gcr.io/edens-test/dir`
2. Pushed image: `gcr.io/edens-test/dir`
3. Ran a cloud build invocation using:
```
timeout: 7200s
tags: gce-daisy
steps:
- name: gcr.io/edens-test/dir:latest
args:
- -project=edens-test
- -client_id=api
- -image_name=certs
- …
```
=> Ensure gce_vm_image_import.Dockerfile has CA certs.

daisy_integration_tests/scripts/post_translate_test.sh, daisy_workflows/image_import/debian/translate.py
The Cloud SDK is currently broken for Debian 8 imports; the SDK dropped support for Python 3.4, which is Debian 8's version.
This change skips installing the Cloud SDK for Debian 8, and skips testing for it.
Ran the following:
1. daisy -project edens-test -zone=us-central1-b daisy_integration_tests/debian_8_translate.wf.json
2. daisy -project edens-test -zone=us-central1-b daisy_integration_tests/debian_9_translate.wf.json
=> Don't install Cloud SDK when importing Debian 8.

daisy_integration_tests/el_import_dont_use_proxy.wf.json
This change increases the timeout of el_import_dont_use_proxy.wf.json from 30 minutes to 60 minutes, since we've been seeing intermittent timeouts recently.
=> Increase timeout for el_import_dont_use_proxy.wf.json

gce_vm_image_import.Dockerfile
Our build is currently failing with 
```ERRO[0000] Error while retrieving image from cache: marketplace.gcr.io/google/debian9 GET https://marketplace.gcr.io/v2/google/debian9/manifests/latest: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication ```
Based on https://github.com/GoogleContainerTools/kaniko/issues/659, one solution is to switch to an endpoint that doesn't require authentication. This endpoint that I'm using comes from the docs for managed images: https://github.com/GoogleContainerTools/base-images-docker/tree/master/debian
I reproduced the issue locally by [invoking kaniko …
=> Switch to gcr.io endpoint that doesn't require auth.

cli_tools/gce_vm_image_import/importer/bootable_disk_processor.go, cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go, cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/inflater.go, cli_tools/gce_vm_image_import/importer/inflater_test.go, cli_tools/gce_vm_image_import/main.go
Since #1227, we've been using modularized daisy workflows in image import. A side effect is that gcloud isn't showing all of the log lines to users. This was caused by:
1. gcloud is configured to show lines that start with `[image` (or one of  a few other prefixes)
2. daisy emits log lines using the workflow's name as a prefix
3. Some of the modularized workflow names don't start with `image`.
This PR is a quick fix that dynamically renames the workflows to have a name that matches the prefix. I have b/161567644 to track a longer-term fix where gcloud output isn't coupled to workflow names.
```
./main -image_name img -os debian-8 -client_id  edens-test -source_image projects/compute-image-tools-test/global/images/debian-8-translate -project=edens-test
```
```
[import-from-image]: …
```
=> Ensure that gcloud shows image import translation logs.

test-infra/prow/config.yaml
Switch OVF import tests to a 12hrs schedule as the 24hrs schedule is often delaying releases and not providing timely failure notifications. Decided to keep the name as is, even though it's a bit misleading as I don't find it worth the effort of renaming and potentially causing issues.
=> Switch OVF import tests to a 12hrs schedule

cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_utils/ovf_loader_test.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
OVF import: no OS Type specified in OVF descriptoris currently the highest rate error for instance import.
To solve this, use OS ID from OVF descriptor in addition to OS Type to support a wider range of OVFs that might not have OS Type set (or use OS Type from a different name space, like vbox).
=> OVF import: use OS ID from OVF descriptor in addition to OS Type

daisy_integration_tests/2008r2_vmware_translate.wf.json, daisy_integration_tests/debian_8_translate.wf.json, daisy_integration_tests/opensuse_15_1.wf.json, daisy_integration_tests/scripts/post_translate_test.ps1, daisy_integration_tests/scripts/post_translate_test.sh, daisy_integration_tests/sles_12_4_byol.wf.json, daisy_integration_tests/sles_12_5_byol.wf.json, daisy_integration_tests/sles_15_1_byol.wf.json, daisy_integration_tests/sles_sap_12_4_byol.wf.json, daisy_integration_tests/ubuntu_1404_img_translate.wf.json, daisy_integration_tests/ubuntu_1604_vmware_translate.wf.json, daisy_integration_tests/ubuntu_1804_aws.wf.json, daisy_integration_tests/ubuntu_1804_azure.wf.json, daisy_integration_tests/ubuntu_1804_vmware.wf.json, daisy_integration_tests/windows_10_x86_byol.wf.json, daisy_integration_tests/windows_7_x86_byol.wf.json, daisy_integration_tests/windows_8_x86_byol.wf.json, daisy_workflows/image_import/debian/translate.py, daisy_workflows/image_import/enterprise_linux/translate.py, daisy_workflows/image_import/suse/translate.py, daisy_workflows/image_import/ubuntu/translate.py, daisy_workflows/image_import/windows/translate.ps1
This PR includes the [OS Config agent](https://cloud.google.com/compute/docs/manage-os) for imported images, instances, and machine images. To disable installation of the agent, users can specify the existing  `no-guest-environment` flag.
All distro versions [supported by the OS Config agent](https://cloud.google.com/compute/docs/manage-os) will now include the OS config agent, if the agent is vended in GCE's official images. Specifically:
* Windows:
* ISA: 64-bit only
* Versions: All versions *after* Windows 2008r2
* Debian:
* 9 (10 is not currently supported by image import)
* EL:
* All importable versions
Ubuntu, SLES, and OpenSUSE will be added once the OS config agent is adopted by their upstream maintainers.
The e2e tests are updated to verify the agent using the [suggested steps on …
=> Install OS config agent during import.

cli_tools/gce_vm_image_import/importer/api_inflater.go, cli_tools/gce_vm_image_import/importer/api_inflater_test.go, cli_tools/gce_vm_image_import/importer/inflater.go, cli_tools/gce_vm_image_import/importer/inflater_test.go, cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go, cli_tools_e2e_test/gce_image_import_export/test_suites/import/post_translate_test.wf.json, daisy_integration_tests/scripts/post_translate_test.ps1, gce_image_import_export_tests.Dockerfile
Since Window's translation requires booting the instance, we need to add the UEFI_COMPATIBLE guest OS feature during inflation. Prior to this change, it was only added to the final GCP image.
- Unit tests 
- Two new e2e tests (Windows and RHEL) where the source image requires UEFI for booting.
=> Image import: Include UEFI guest OS feature during inflation, if requested.

daisy_integration_tests/image_import_and_translate_ova_with_spaces_in_vmdk_filename.wf.json
The test `image_import_and_translate_ova_with_spaces_in_vmdk_filename.wf.json` is failing with the message "TestFailed: google-osconfig-agent not running.". This started after #1289 was pushed, and is occurring since the OS config agent is currently not supported on Ubuntu.
=> Don't check for OSConfig agent in Ubuntu e2e test.

cli_tools_e2e_test/common/compute/instance.go, cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
#1289 added the OS config agent to import. This PR skips OS config checking for tests that:
- Import Ubuntu or Windows 2008r2 and use `post_translate_test.ps1` or `post_translate_test.sh`.
- Ran the ovf e2e import suite
=> OVF e2e: Whitelist platforms not supporting osconfig agent

daisy_integration_tests/scripts/post_translate_test.ps1
The test was added in #1289, but not enabled.
Ran the following tests:
- daisy_integration_tests/2019_translate.wf.json
- daisy_integration_tests/2008r2_vmware_translate.wf.json
=> Check for OS config agent in Windows e2e

daisy_workflows/image_import/enterprise_linux/translate.py
Recently a CentOS 6 import failed with the message "/etc/yum.repos.d/google-cloud.repo: No such file or directory". The most likely cause is that `/etc/yum.repos.d` didn't exist on the image prior to this invocation:
https://github.com/GoogleCloudPlatform/compute-image-tools/blob/b0739e9975072ae34031121608e6d4f2c3023e3f/daisy_workflows/image_import/enterprise_linux/translate.py#L116
This change creates the directory if it is missing.
I found no other instances where we assume that a drop-in directory exists prior to writing a file to it.
Testing:
- Ran `daisy_integration_tests/centos_6_qcow2_translate.wf.json` to ensure there weren't regressions.
=> EL import: Ensure /etc/yum.repos.d exists.

test-infra/prow/config.yaml
Prow jobs did not capture changes in test args in ci-images-import-export-cli-e2e-tests. Thus, we need move the position of the entire section.
=> [Onestep Import] Move sections in prow config to trigger args update

daisy_integration_tests/windows_7_x64_byol.wf.json
OS Config agent is only supported for Windows greater than 2008r2. Windows 7 and Windows 2008r2 are both NT 6.1.
=> Disable OS config test on windows_7_x64_byol.wf.json

cli_tools/gce_onestep_image_import/onestep_importer/aws_importer.go, cli_tools/gce_onestep_image_import/onestep_importer/aws_importer_test.go, cli_tools/go.mod
Since we want to upload to GCS with optimal performance, we need to make some changes to the HTTP transport fields. Previously, we were using the `withHTTPClient` option to pass in a HTTP client with custom transport setting. However, as discussed in https://github.com/googleapis/google-api-go-client/issues/404, the `withHTTPClient` option is incompatible with `withCredentialsFile` option.  So instead, will add the `withCredentialsFile` option when new transport is called. We also need to add the default scope for Cloud Storage client, since this step is skipped when we create Cloud Storage client with custom HTTP client.
=> [Onestep Image Import] Remove adding HTTP client option to gcs client

cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go, cli_tools_e2e_test/gce_image_import_export/test_suites/onestep_import/aws_test_utils.go, cli_tools_e2e_test/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go, cli_tools_e2e_test/gce_image_import_export/test_suites/scripts/post_translate_test.wf.json
#1289 added the OS config agent to import. This PR change ensures that we do not check for OS config agent on E2E tests using Ubuntu images, since OS config agent is currently not supported on Ubuntu.
=> [Onestep Image Import E2E] Skip os-config-agent check for ubuntu

cli_tools/gce_onestep_image_import/onestep_importer/utils.go
Originally, the onestep import calls a binary of image import with the relative path of the executable. This approach will fail the E2E test if we don't specify "./" in the path to indicate the binary is in the current directory. However, the gcr.io/compute-image-tools/gce_vm_image_import has a different directory layout as the E2E tests. The image import binary is not under the current working directory. To solve the error, this PR will change the image import executable path to an absolute path.
=> [Onestep Import] Change image import exec path

daisy_integration_tests/scripts/run_daisy_and_check_logs.sh
The test `validate_cloud_logging.wf.json` has recently been failing with "BuildFailed: Expected Cloud Logs.". This increases the wait period prior to checking for logs.
The alternative is to use a retry mechanism. I opted against that since one of the cases *doesn't* want logs, and therefore need to wait until the logs would have propagated and become available.
Testing:
* Ran validate_cloud_logging test and verified that it passed.
=> Daisy e2e: Increase wait period prior to checking logs

cli_tools/common/disk/inspect.go
The workflow was renamed in #1326; this updates the hardcoded reference to it.
- Ran the `ubuntu-1804` test that was failing.
- Ensured this was the only stale reference.
=> Update Go inspection clients workflow reference

cli_tools_cloudbuild.yaml
Deploying image import wrappers to Artifact registry (two zones to start with for POC purposes, all zones and all wrappers to follow) to allow for regional wrapper deployment for reliability purposes.
=> Deploying image import wrappers to Artifact registry

cli_tools_cloudbuild.yaml
Deploying image import wrappers to Artifact registry: fixed the path to published Docker images by adding repository name (wrappers)
=> Deploying image import wrappers to Artifact registry fixe

daisy/compute/compute.go, daisy/workflow_test.go
This is the prep for the new VMDK API adoption beta shadow test: make the API ready to use in Daisy lib.
=> DaisyCompute client: support CreatDisk from beta api

cli_tools_cloudbuild.yaml
Kaniko executor has a bug where publishing to multiple repos in a single step causes auth error for all but the first repo. Splitting into separate steps until this is fixed in kaniko executor. Also upgraded kaniko executor to support Artifact registry authentication.
=> Split publishing to different repos in separate steps. Upgrade kaniko executor version.

cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
This includes images for EL 7.8 and EL 8.2 to ensure that the centos-7, centos-8, rhel-7, and rhel-8 `--os` flags work with the new minor versions.
Ran all of the EL tests, and they pass.
=> Add tests for EL 7.8 and EL 8.2

daisy_integration_tests/rhel_8_translate.wf.json
The rhel-8-import image was created with a GUI, and the GUI's initialization is causing the tests to occasionally timeout. This replaces the image with a minimal server, which better matches what we're expecting to be imported.
=> Use a non-GUI image to avoid flaky RHEL8 test.

daisy_workflows/image_import/import_image.sh
Testing:
- Ran `import_image.wf.json` with a disk that would need to be resized, confirmed that it was successful.
- Logs:
```
Sep  2 00:47:25 localhost GCEMetadataScripts[809]: 2020/09/02 00:47:25 GCEMetadataScripts: startup-script: Resizing result: Updated [https://www.googleapis.com/compute/v1/projects/compute-image-test-pool-001/zones/us-central1-c/disks/disk-import-disk-scratch-xqs4y]. --- creationTimestamp: '2020-09-01T17:46:56.560-07:00' description: Disk created by Daisy in workflow "import-disk" on behalf of ericedens. id: '2828647025030157679' kind: compute#disk labelFingerprint: 42WmSpB8rSM= lastAttachTimestamp: '2020-09-01T17:46:59.443-07:00' name: disk-import-disk-scratch-xqs4y physicalBlockSizeBytes: '4096' selfLink: …
```
=> Increase verbosity of disk resizing.

cli_tools_e2e_test/common/compute/instance.go, cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go, cli_tools_e2e_test/gce_windows_upgrade/test_suites/windows_upgrade/windows_upgrade_test_suite.go
Introduced failureMatches for OVF import and Windows upgrade E2E tests. Windows upgrade still needs to be updated to have failure match strings actually set.
=> Introduced failureMatches for OVF import and Windows upgrade E2E tests

daisy_workflows/ovf_import/import_ovf_to_machine_image.wf.json
GMI import: stop imported instances before creating GMIs to avoid any consistency issues.
=> GMI import: stop imported instances before creating GMIs

cli_tools/common/utils/storage/resource_location_retriever.go
Update multi-regional mapping in import/export wrappers when determining the best zone to run import in when multi-regional storage is used: add new regions and sort based on VM cost.
=> Update multi-regional mapping in import/export wrappers

cli_tools_e2e_test/common/compute/instance.go, cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
* Don't check for OS config in OVF import E2E test verification as OS config is currently not supported on imported Ubuntu instances/GMIs.
* Removed an unused GMI import E2E test func
=> Don't check for OS config in OVF import E2E test verification

cli_tools/gce_vm_image_import/importer/api_inflater_test.go, cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go, cli_tools/gce_vm_image_import/importer/inflater_test.go, cli_tools/gce_vm_image_import/importer/testdata/image_import
The symlink existed so that import unit tests could reference workflows. This caused IDEs to double index the files in daisy_workflows. This change removes the symlink, replacing its usage with a relative path.
=> Import unit tests: remove testdata symlink

cli_tools/common/disk/inspect.go, cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
Mute the UEFI detection results for now. Restore it till we got the reason of b/168671324
=> mute has_efi_partition

cli_tools_e2e_test/common/utils/utils.go, cli_tools_e2e_test/gce_image_import_export/test_suites/import/cli_tests.go
We're preparing to add `ubuntu-2004` as an option for `--os` in gcloud. This PR creates an e2e test that imports an `ubuntu-2004`, which we will use to track the deployment of the new flag value.
- Ran the  "ubuntu-2004 should be an option for --os" suite, and confirmed that the `gce_vm_image_import` case passes, while the gcloud cases fail. Prior to failing, they emit: "argument --os: Invalid choice: 'ubuntu-2004'. Did you mean 'ubuntu-1804'?"
=> Add e2e test to validate rollout of ubuntu-2004 to gcloud.

cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go, daisy_workflows/image_import/enterprise_linux/translate.py
Prior to this, if a user had extra directories in /lib/modules, the import would fail. In EL6:  'modules must be specified using absolute paths.'  In EL8: 'depmod: ERROR: Bad version passed'
Root cause: Although each directory in /lib/modules typically corresponds to a kernel version, that may not always be true. kernel-abi-whitelists, for example, creates extra directories in /lib/modules. Prior to this change, each directory was blindly passed to depmod. 
- Added a new e2e test that repro'd  the issue, and passes after the fix.
=> EL import: Don't fail when unexpected directory in /lib/modules

cli_tools/common/utils/param/param_utils.go, cli_tools/common/utils/param/populator_test.go, cli_tools/gce_vm_image_import/main.go
If `scratchBucketCreator.IsBucketInProject` returns false, delete `sourceFile` if it's in the scratch bucket.
Use 'hide whitespace' to see the relevant changes to the test.
=> Remove resources when bucket owned by different project

cli_tools/gce_vm_image_import/importer/processor.go, cli_tools/gce_vm_image_import/importer/processor_test.go
Starting at #1338, any inspection failure causes import workflows to fail.
- Prior to #1338:
- https://github.com/GoogleCloudPlatform/compute-image-tools/blob/v20200922/cli_tools/gce_vm_image_import/importer/processor.go#L50
- After #1338:
- https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/cli_tools/gce_vm_image_import/importer/disk_inspection_processor.go#L53
This PR disables all inspection unless the `-inspect` flag is present.
=> Image import: Only run inspection when -inspect flag is specified

cli_tools_e2e_test/gce_image_import_export/test_suites/import/cli_tests.go
Soon we'll have eight `--os` targets for SLES. This adds gcloud tests for all, similar to #1362 that added a test for Ubuntu 20.04. 
- Tested using #1368 as a base. Confirmed that all 'wrapper' tests passed, and all 'gcloud' tests failed. This is expected, since we haven't added the gcloud flags yet.
=> Image import: e2e tests to validate rollout of new SLES targets to gcloud

cli_tools/gce_windows_upgrade/upgrade_script_2008r2_to_2012r2.ps1
A internal user failed to upgrade because the instance have a super old powershell version (<=2), which doesn't allow "-ErrorAction IgnoreError". Changed to "-ErrorAction SilientlyContinue" which has the same effect for our usage.
Verified from local manually.
=> [windows upgrade] be compatible with powershell <=2

cli_tools_cloudbuild.yaml
Building OVF import wrapper and windows upgrader into all repos. Switched to kaniko executor:v1.1.0 which is the official latest version
=> Building OVF import wrapper and windows upgrader into all repos. 

daisy_workflows/export_metadata/export-metadata.py, daisy_workflows/export_metadata/export_metadata.wf.json, daisy_workflows/export_metadata/export_metadata.workflow.json
The independent export-metadata workflow which use a gce image as source. the output is a metadata.file in gcs.
Update:
-  Use linux_common to retrieve metadata and upload file.
-  Remove project level variable
-  make some variable as not required. 
Testing:
Debian:
https://pantheon.corp.google.com/storage/browser/_details/hanga-testing-daisy-bkt/daisy/hanga/daisy-export-metadata-20201001-22:34:06-1qb9x/logs/inst-exporter-export-metadata-1qb9x-serial-port1.log?organizationId=433637338589&project=hanga-testing
RHEL:
https://pantheon.corp.google.com/storage/browser/_details/hanga-testing-daisy-bkt/daisy/hanga/daisy-export-metadata-20201001-22:34:06-1qb9x/logs/inst-exporter-export-metadata-1qb9x-serial-port1.log?organizationId=433637338589&project=hanga-testing
Daisy Output. …
=> export-metadata v2 design

cli_tools/common/domain/interfaces.go, cli_tools/common/utils/param/param_utils.go, cli_tools/common/utils/param/populator.go, cli_tools/common/utils/param/populator_test.go, cli_tools/common/utils/storage/storage_client.go, cli_tools/common/utils/storage/storage_client_test.go, cli_tools/gce_onestep_image_import/onestep_importer/aws_args.go, cli_tools/gce_onestep_image_import/onestep_importer/test_utils_test.go, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_import/cli/cli.go, cli_tools/gce_vm_image_import/importer/args.go, cli_tools/gce_vm_image_import/importer/args_test.go, cli_tools/gce_vm_image_import/main.go, cli_tools/mocks/mock_storage_client.go, cli_tools_tests/module/import/scratch_ownership_test.go
In #1373 we added deletion of the source file when the source file is contained in a scratch bucket that is contained in a different project.
This PR adds the following:
- Validate that the source file is a single file. If there are other files that have the same prefix, don't perform deletion.
- Module tests
=> Image import: When scratch is shared, ensure file deletion isn't recursive

daisy_workflows/image_import/import_image.sh
When resize fails on the the inflation worker, we try to disambiguate the failure. The current regex masks quota issues.
To test this change, I modified my project to introduce a quota failure.
Before this PR:
```
ImportFailed: Failed to resize disk. The Compute Engine default service account needs the role: roles/compute.storageAdmin
```
After this PR:
```
ImportFailed: Failed to resize disk. ERROR: (gcloud.compute.disks.resize) Could not fetch resource:  - Quota 'SSD_TOTAL_GB' exceeded.  Limit: 40960.0 in region us-central1.
```
Here are the error messages returned by gsutil:
- Permissions message: ` (gcloud.compute.disks.resize) Could not fetch resource:  - Required '\''compute.disks.resize'\'' permission for '\''projects/edens-test/zones/us-central1-c/disks/disk-bqrn4'\''  '`
- Quota …
=> Disk inflation: Surface quota errors

cli_tools/common/disk/inspect.go, cli_tools/gce_vm_image_import/importer/importer.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go, cli_tools_tests/module/diskinspect/disk_inspect_test.go, daisy_workflows/image_import/inspection/boot-inspect.wf.json, test-infra/prow/config.yaml
Prior to this, when the project lacks the default network, disk inspection fails with:
```
Disk inspection error=networkResourceDoesNotExist: step "run-inspection" 
validation error: networkResourceDoesNotExist: projects/project-name/global/networks/default does not exist
```
This occurred since disk inspection didn't use `--network` and `--subnet` that was passed from the user's CLI invocation.
- Added tests in `cli_tools_e2e_test/diskinspect/disk_inspect_test.go` that fail prior to the fix, but pass after. To achieve this, I added a new project "compute-image-test-custom-vpc" that has the default network removed.
- Added `-inspect` to tests in `cli_tools_e2e_test/gce_image_import_export/test_suites/import/cli_tests.go`. This wouldn't have caught the original error, since …
=> Disk inspection: Respect custom network and subnet

cli_tools/gce_windows_upgrade/upgrade_script_2008r2_to_2012r2.ps1
The grammar that won't work as expected with powershell < v2.0. Thus it will fail to find the install media.
Tested with a image provided by internal team, which installs v2 only: projects/emea-gcve-lab/zones/us-east4-a/disks/w2k8-vlst-3-boot-disk-6ixd
Previous test was via a simulated v2 so didn't expose this problem.
=> [windows upgrade] modify powershell grammar that is incompatible on old versions

cli_tools/common/utils/logging/service/literal_loggable.go, cli_tools/common/utils/logging/service/literal_loggable_test.go, cli_tools/gce_vm_image_import/importer/disk_inspection_processor.go, cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/processor.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
Enable UEFI detection.
Notice: it will enable the shared workflow for OS inspection & UEFIinspection, but the actual OS inspection logic (in python) won't be executed.
Tested by UEFI e2e tests.
=> [uefi support] enable uefi detection

cli_tools_tests/module/diskinspect/disk_inspect_test.go, daisy_workflows/image_import/inspection/src/boot_inspect/inspectors/os/windows.py, daisy_workflows/image_import/inspection/src/boot_inspect/model.py, daisy_workflows/image_import/inspection/tests/test_model.py, daisy_workflows/image_import/inspection/tests/test_windows.py
Prior to this, boot-inspect returned NT versions for Windows' major and minor versions. There are a couple of problems with this:
1. Desktop and server use the same NT versions (server 2012r2 and desktop 8.1 have the same NT version)
2. NT versions are sometimes reused. Server 2016 and Server 2019 use the same NT version
NT versions 6.0 and newer are included. Version mappings from https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions
=> Windows inspection: Use marketing versions

daisy_workflows/image_import/inspection/src/boot_inspect/inspection.py, daisy_workflows/image_import/inspection/src/boot_inspect/inspectors/os/linux.py
This PR refactors Linux inspection to support differentiation between SLES and SLES for SAP. SLES for SAP is identified by a sentinel file in /etc/products.d [1]. Prior to this PR, sentinel file matching was coupled to version extraction. This coupling blocks matching SLES for SAP, since SLES for SAP uses /etc/os-release for its version (and therefore doesn't have a custom version file).
SLES for SAP detection will come in a follow-up PR.
1. https://www.suse.com/support/kb/doc/?id=000019341
=> Boot inspect: Refactor linux matching to allow SLES for SAP detection

daisy_workflows/image_import/enterprise_linux/translate.py
Audited ten recent failures, and none were related to the incorrect OS  being specified. This makes sense, since the newer change [1] would have overwritten this error message with correct OS if it were indeed mispecified. After this change, the actual error will be more prominent to the user (rather than logged as the second-to-last line).
Failures from audit: 
1. Repositories unreachable (local file, uncreachable URL)
2. Corrupt rpm database
3. Package conflicts
__
1. https://github.com/GoogleCloudPlatform/compute-image-tools/blob/f5a91c65376c26d14c93854a42d408fc2da41a81/cli_tools/gce_vm_image_import/importer/errors.go#L28-L27
=> EL import: Surface yum_install errors

cli_tools/gce_vm_image_import/importer/api_inflater.go, cli_tools/gce_vm_image_import/importer/api_inflater_test.go, cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/importer_test.go, cli_tools/gce_vm_image_import/importer/inflater.go, cli_tools/gce_vm_image_import/importer/inflater_test.go, cli_tools_tests/go.mod, cli_tools_tests/go.sum, cli_tools_tests/module/import/file_inflation_test.go, cli_tools_tests/module/import/inflater_test.go, cli_tools_tests/module/import/pkg_test.go, cli_tools_tests/module/import/scratch_ownership_test.go, daisy_workflows/image_import/import_image.sh
Includes the following changes:
* import_image.sh: Prior to resizing a disk, check its size to determine whether it needs resizing.
* module tests: Added a test for `gce_vm_image_import/importer/inflater.go`
* This required reverting the `Inflater.inflate(loggableBuilder *service.SingleImageImportLoggableBuilder)` prototype back to `Inflater.inflate()`; the loggable builder is only used in the facade implementation.
* Create a file `cli_tools_tests/module/import/pkg_test.go` to contain `zone` and `project` variables that are shared within the package.
=> Inflation: Verify disk size prior to resizing

cli_tools/common/utils/logging/service/log_entry.go
The json field name of "InspectionResults" was missed from log entry in the previous version. Add them.
=> [log metrics] fix the json name

cli_tools/common/utils/logging/service/log_entry.go
fields order matters for log json sicne firelog is sensitive to it.
please don't merge now since I am still verifying
=> [log] switch fields order

cli_tools/common/utils/logging/service/log_entry.go, cli_tools/common/utils/logging/service/logger.go
Tested from local, verified that db received the log & parsed correctly
=> [log] move the loc of inspection_results due to the inconsistency of proto v.s. design

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
Now that the new `ubuntu` and `sles` targets have been launched, we can remove these tests.
=> Remove temporary tests confirming gcloud update

cli_tools/gce_vm_image_import/importer/api_inflater.go, cli_tools/gce_vm_image_import/importer/api_inflater_test.go, cli_tools/gce_vm_image_import/importer/args.go, cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/inflater.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go, cli_tools_tests/e2e/utils.go
Fix b/169073057
Original design:
1. when main inflater finished later than shadow (which is 99% cases), no problem.
2. when main inflater finished earlier than shadow with an error, the main thread got terminated and shadow inflater missed the chance to cleanup shadow PD.
New design:
1. when main inflater finished later than shadow (which is 99% cases), still no problem.
2. when main inflater finished earlier than shadow, the main thread needs to call "shadowInfalter.cancel()" in order to:
* cancel the shadowInfalter.Infalte(). The inflate() will try to return early, but needs to guarantee the cleanup is done
* wait for shadowInfalter.Infalte() to finish, in order to guarantee cleanup won't be interrupted before main thread exits.
=> [VMDK API Adoption] cleanup shadow disk when error happens

daisy_workflows/linux_common/utils/common.py
A derivative of Ubuntu 18.04 failed import with the message: `rm_f: /etc/udev/rules.d/70-persistent-net.rules: Is a directory"`
- Confirmed that affected image imported
- Ran the ubuntu tests in `cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go`
=> Don't fail import when 70-persistent-net.rules is a directory

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_workflows/image_import/suse/suse_import/setup.py, daisy_workflows/image_import/suse/suse_import/translate.py, daisy_workflows/linux_common/utils/common.py
When no operating system is detected during SLES import, the user currently sees: `TranslateFailed: error: exits with return code 1`
The cause was:
```
ValueError: Import of unknown-0.0 is not supported. The following versions are supported: [opensuse-15.1|2, sles-15.1|2, sles-12.4|5]
```
Which appears in the logs, but is not surfaced to the user.
Two items are fixed:
1. Recognize that a distro of 'unknown' means that no operating system was found.
2. Fix surfacing of the actual error message.
=> SLES import: Improve error messaging when SUSE not found on disk

cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/importer_test.go
Fixed an edge case in image importer run step that can cause deadlock to occur on timeout due to WaitGroup being added to before checking for context expiration/timeout. This can cause wg.Wait() in the cancellation handler below to wait forever.
=> Fixed an edge case in image importer run step that can cause a deadlock on timeout

daisy_workflows/image_import/windows/translate.ps1
If the time service is in a pending state (PendingState or PendingStop) the import will currently fail due to the Stop-Service or Start-Service cmdlets returning an error.
This checks the W32Time service status and if it includes pending it will wait and recheck every second. For the instance having this issue, it took 13 seconds until it was not in a pending state. This delay allowed the Stop-Service cmdlet to succeed.
=> Wait if W32Time is in a pending state

daisy_workflows/export_metadata/export-metadata.py
failed to get image metadata: failure unmarshal file to json parsing time "["2020-11-06T19:06:05.138104+00:00"]" as ""2006-01-02T15:04:05Z07:00"": cannot parse "["2020-11-06T19:06:05.138104+00:00"]" as """
The comma will make build_date to an array when parsing.
=> bugfix: remove comma

daisy_workflows/linux_common/tests/test_guestfsprocess.py, daisy_workflows/linux_common/utils/guestfsprocess.py
While debugging recent yum-related failures, half had not-helpful failure messages.
Examples:
* `sh:"""`
* `sh: Error: Nothing to do."""`
* `sh: Traceback (most recent call last):"""`
The problem is guestfs.GuestFS's shell methods. They discard either stdout or stderr, depending on whether the command fails or is successful (respectfully). 
This library is motivated by subprocess.run, which returns an object containing stdout, stderr, and the return code of the process.
=> Ensure shell output from guest is retained

daisy_workflows/image_import/windows/translate.ps1
When --syspre-windows flag is used, Enable-RemoteDesktop is not called so that an instance from the imported image can't be accessed unless RDP was enabled before importing.
=> Enable-RemoteDesktop move up further

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_workflows/image_import/enterprise_linux/translate.py, daisy_workflows/linux_common/utils/common.py
Import fails when `ca-certificates`  is stale such that a yum repo cannot by verified. A concrete example occurs when `epel` is added to an older version of EL 6, as described in https://stackoverflow.com/questions/26734777 .
After this PR, all EL imports will have `ca-certificates` upgraded, _if_ `ca-certificates` is installed.  
* Create a CentOS 6 image that reproduces the issue.
* Ran all EL tests in `import_tests.go`
=> EL import: Update ca-certificates when translation starts

cli_tools/gce_image_publish/main.go, cli_tools/gce_image_publish/publish/publish.go, cli_tools/gce_image_publish/publish/publish_test.go
Some tools don't support this file layout scheme, so add a flag to support naming the tarball directly.
With `noRoot`:
$sourceGCSPath/$imagePrefix[-$sourceVersion].tar.gz
Without `noRoot` (default behavior):
$sourceGCSPath/$imagePrefix[-$sourceVersion]/root.tar.gz
=> gce_image_publish: add noRoot option

daisy_workflows/image_import/windows/translate.ps1
This is to correct an issue where the script continued after the restart-computer cmdlet was called. This caused the build to fail prior to the reboot completing so the script didn't get the second attempt which is the intention.
=> Adding exit after Restart-Computer, to prevent the script from continuing.

daisy_workflows/image_import/enterprise_linux/translate.py, daisy_workflows/image_import/enterprise_linux/translate_el.wf.json
In #1417 we updated EL import to update ca-certificates. This PR makes two improvements, both found by reading testgrid translation logs:
* Avoid unnecessary latency by updating ca-certificates only when translating EL6 guests that use the epel repo. In the EL6 test [1], the previous PR added about 80 seconds. In the RHEL7 [2] test, it added about 15 minutes. In the current version, the time penalty only occurs when:
* The guest is EL6
* It uses the epel repo
* It uses an old version of ca-certificates 
* Improve debugability of the feature by using the library added in #1418.
1. https://github.com/GoogleCloudPlatform/compute-image-tools/blob/5a2d47d1138373d1ee2a2152eb3a96dffee7ccfd/cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go#L288
2. …
=> EL import: Tune upgrading of ca-certificates

cli_tools/common/utils/param/param_utils.go, cli_tools/common/utils/param/populator_test.go
Ensure that anonymized error is used as the first argument to `daisy.Errf`.
=> Use anonymized errors in populateScratchBucketGcsPath

cli_tools/common/disk/inspect.go, cli_tools/common/disk/inspect_test.go, cli_tools_tests/module/diskinspect/disk_inspect_test.go, daisy_workflows/image_import/inspection/src/boot_inspect/inspection.py
Prior to this, a panic occurred at [1] when there was a bootable partition, but we didn't recognize the distro in it. Two changes:
1. Fixed the root cause in inspection.py
2. Added a nil check so  that an error is returned rather than a panic
The issue was identified in the testcase "el-yum-not-found" [2], which uses a disk image with manjaro in it. 
Testing:
- Added test that reproduced the issue and confirms the fix
- Ran `daisy/cli_tools_tests/e2e/gce_image_import_export/test_suites/import`
1. https://github.com/GoogleCloudPlatform/compute-image-tools/blob/93b6de86409bc966e4cabdff93c2e852c469ab4a/cli_tools/common/disk/inspect.go#L181-L180
2. https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1327973760887689216
=> Disk inspection: Don't panic when disk has unsupported distro

cli_tools/gce_vm_image_import/importer/api_inflater.go
The previous logic will print an misleading log field to shadow test result:
"Shadow inflater failed while main inflater succeeded: [Failed to calculate checksum: <nil>]"
It's actually a success. It doesn't impact our analysis (just treat it as success when doing statistics) but is misleading to other engineers.
=> [VMDK shadow test] minor: fix error construction logic

cli_tools/common/disk/inspect.go, cli_tools/common/disk/inspect_test.go, cli_tools/common/disk/mocks/mock.go, cli_tools/common/utils/logging/service/daisy_loggable.go, cli_tools/common/utils/logging/service/literal_loggable.go, cli_tools/common/utils/logging/service/log_entry.go, cli_tools/common/utils/logging/service/logger.go, cli_tools/gce_vm_image_import/importer/args.go, cli_tools/gce_vm_image_import/importer/disk_inspection_processor.go, cli_tools/gce_vm_image_import/importer/disk_inspection_processor_test.go, cli_tools_tests/module/diskinspect/disk_inspect_test.go
Following this PR:
- All image imports will have OS inspection run.
- The OS inspection results will be logged
Testing:
- Ran `cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go` and verified that logs were created (start and finish logs)
=> Image import: Inspect OS and log results

cli_tools/common/utils/daisy/daisy_utils_test.go, cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go, cli_tools/gce_vm_image_import/importer/api_inflater.go, daisy_workflows/image_import/debian/translate_debian.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_6.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_7.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_8.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_licensed.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json, daisy_workflows/image_import/import_image.wf.json, daisy_workflows/image_import/inflate_file.wf.json, daisy_workflows/image_import/inspection/boot-inspect.wf.json, daisy_workflows/image_import/suse/translate_opensuse_15.wf.json, daisy_workflows/image_import/suse/translate_suse.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
Rollback of #1431 and #1432, which caused a regression for EL and SLES imports: 
- https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1328876340400623616
- https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-daisy-e2e/1328882631923732480
=> cli-tools: Switch back to Debian 9 worker

daisy_workflows/image_import/debian/translate_debian.wf.json, daisy_workflows/image_import/enterprise_linux/translate_el.wf.json, daisy_workflows/image_import/suse/translate_opensuse_15.wf.json, daisy_workflows/image_import/suse/translate_suse.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json, daisy_workflows/linux_common/bootstrap.sh, daisy_workflows/linux_common/utils/common.py
At the end of Linux translation, statuses are double printed, once by Python and once by Bash. If Python reports a failure, but fails to flush its logs, then the incorrect status can be read by Daisy.
This was observed recently in the "Incorrect OS specified" test: 
```
startup-script-url: TranslateStatus: <serial-output key:'detected_distro' value:'debian'>
startup-script-url: TranslateStatus: <serial-output key:'detected_major_version' value:'9'>
startup-script-url: TranslateStatus: <serial-output key:'detected_minor_version' value:'12'>
startup-script-url: TranslateDebug: Traceback (most recent call last):
startup-script-url:   File "/usr/local/lib/python3.7/dist-packages/utils/common.py", line 246, in RunTranslate
startup-script-url:     translate_func()
startup-script-url:   File …
```
=> Linux translate: Print status once

daisy_workflows/image_import/suse/translate_opensuse_15.wf.json
In https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1438 I accidentally switched the translator for OpenSUSE 15 to run in Debian 9. Translation of OpenSUSE 15 needs the newest version of libguestfs, and has been using it since it was originally implemented. 
Using Debian 9 causes the failure  "No SUSE operating systems found", and occurs since the version of libguestfs on Debian9 does not support detection of OpenSUSE 15.
1. https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-daisy-e2e/1329200730476646400
- Ran `daisy_workflows/image_import/suse/translate_opensuse_15.wf.json`
=> OpenSUSE 15 translate: Use Debian 10 worker

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_workflows/image_import/enterprise_linux/translate.py
An EL 6.4 import recently failed with: "TranslateFailed: error: Ensure all configured repos are reachable. Failed to install ('centos-release-scl',). Details: sh: Error: Nothing to do."
A couple of issues, fixed in this PR:
1. Only run `yum updateinfo` if the command is available. (It's not in EL 6.4 doesn't have `yum updateinfo` by default, but it is in later versions)
2. Include stderr and stdout if the yum command fails. 
3. Chain exceptions to retain the entire stack trace
4. Tweak log message of updating ca-certificates to clarify when we expect the operation to pass
* Ran all EL tests in cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
=> EL import: Improve error messages for 6.4

daisy_workflows/image_import/windows/run_startup_scripts_x86.cmd, daisy_workflows/image_import/windows/translate_windows_x86_wf.json
Reverting Revert "Replace 1 minute wait with network connectivity checks and reboot remediation in run_startup_script.cmd. (#1434) so we can release while investigate flakiness with Win7 tests after this change.
=> Revert "Replace 1 minute wait with network connectivity checks and reboot remediation in run_startup_script.cmd. (#1434)

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, cli_tools_tests/module/import/inflater_test.go
#1451 updated the test runner to allow verification of licenses after import, but not all cases had the expected license. This updates the runner to only verify licenses when an expected license is provided.
Example of recent failures: https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1336636901204955136
Additionally, updates `cli_tools_tests/module/import/inflater_test.go` to use the new logger interface that was removed in #1444. It was found here since the corresponding check only runs when a file in cli_tools_tests is run:
https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml#L161
=> Import e2e: Only check licenses when provided expected value

daisy_integration_tests/daisy_e2e.test.gotmpl
Currently this is causing a failure in the daisy integration tests:
`test case creation error: open daisy_integration_tests/centos_6_qcow2_translate.wf.json: no such file or directory`
- https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-daisy-e2e/1338944694658273280
This file was removed in #1458, but I missed this reference to it.
=> Daisy integ: Remove missing reference to centos 6 test

cli_tools/common/imagefile/qemu_img.go, cli_tools/common/imagefile/qemu_img_test.go
Prior to this, if the context is cancelled, there was a type assertion panic when `err.(*exec.ExitError).Stderr` is evaluated, since the type of the error wouldn't be `exec.ExitError`.
=> File inspection: Don't panic when context cancelled

cli_tools/common/utils/files/files.go, cli_tools/common/utils/files/files_test.go
The `gce_vm_image_import` tests are currently failing with this stack trace:
```
goroutine 1 [running]:
github.com/GoogleCloudPlatform/compute-image-tools/cli_tools/common/utils/files.MakeAbsolute(0xc0003c4b10, 0x10, 0xc0000dcbd0, 0x7fe8b3a64158)
/workspace/cli_tools/common/utils/files/files.go:44 +0x199
github.com/GoogleCloudPlatform/compute-image-tools/cli_tools/gce_vm_image_import/cli.Main(0xc0000300c0, 0xa, 0xa, 0x1c33440, 0xc0000dcbd0, 0xc0003c4b10, 0x10, 0x13, 0x0)
/workspace/cli_tools/gce_vm_image_import/cli/cli.go:42 +0xe5
main.main()
/workspace/cli_tools/gce_vm_image_import/main.go:33 +0x2ec
```
This occurred since the daisy workflow directory for `gce_vm_image_import` is configured as an absolute link, and should not be interpreted as relative to the process's current working …
=> When resolving paths, leave absolute paths unchanged.

daisy_workflows/image_import/windows/translate.ps1
An import with Windows 2008r2 is failing at the step `Run-Command powercfg /hibernate off`. This PR is landing on a separate branch to unblock the customer.
=> Windows import: Don't disable hibernation.

cli_tools/gce_vm_image_import/cli/cli.go, cli_tools/gce_vm_image_import/main.go
Show a more user friendly error when external IP addresses are prohibitedited by org policy with a link to image import docs.
Currently, the error shown to users is:
`googleapi: Error 412: Constraint constraints/compute.vmExternalIpAccess violated for project 111111111111. Add instance projects/a-project/zones/europe-west3-c/instances/inst-importer-import-image-87wd3 to the constraint to use external IP with it., conditionNotMet`
This is not useful as the recommendation to add importer VM to an exclusion list won't work because importer VM names change for each import.
After this change, error will be:
`constraint constraints/compute.vmExternalIpAccess violated for project a-project. For more information about importing disks using networks that don't allow external IP addresses, see …
=> Show a more user friendly error when external IP addresses are prohibited

daisy_workflows/image_import/windows/translate.ps1
Configuring WinRM on Windows clients. This is to provide the same WinRM management capability to clients that is present in Windows Server images.
=> Configuring WinRM on Windows clients

cli_tools/common/utils/string/string_utils_test.go, daisy/common_test.go
The SECURE_BOOT flag (when creating a new VM instance) has been deprecated and has no effect.
The only usages were in tests for merging slices.
=> Reflect deprecation of SECURE_BOOT

daisy_integration_tests/scripts/post_translate_test.ps1
Updating to use a cmdlet that is in earlier versions of PowerShell.
- This will fix the failing integration tests for Win7/8/2008/2012 where PowerShell 5 is not installed.
=> Updating hibernation registry check

cli_tools/gce_vm_image_import/importer/request.go, cli_tools/gce_vm_image_import/importer/request_test.go
Tests where subnet is specified, but network is omitted, are [failing now.]( https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1348836025501224960) This is a result of #1481, that assumed an empty network is populated by `gce_vm_image_import`. That's true, *except* when subnet is specified; in this case, the GCE backend infers the network.
`if the network is not specified but the subnetwork is specified, the network is inferred.` - [instances.insert](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert)
=> Import module: Allow network to be empty

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
@Quintonamore -- Here's an example of adding a test that will run in prow. 
1. Once pushed, it'll automatically be integrated into the test runner, and you'll see a row on [our testgrid](https://k8s-testgrid.appspot.com/google-gce-compute-image-tools#ci-images-import-export-cli-e2e-tests&grid=old).
2. Testgrid shows `caseName` in each row.
3. `osConfigNotSupported` is required since we don't currently install the OS config agent on Ubuntu. (When I'm adding a test, I search for an existing row that corresponds to the OS on the disk and copy it  ;)  )
=> Image import: Add e2e test case for VHD

daisy_workflows/image_import/windows/translate.ps1, daisy_workflows/image_import/windows/translate_bootstrap.ps1
- If imported system volume has less than 1GB disk space free, output warning to TranslateBootstrap.
- Output system volume utilization and amount of free space to detailed log.
=> Add disk space warning for Windows imports

cli_tools_cloudbuild.yaml, prowjobs_cloudbuild.yaml
Increasing Cloud Build jobs timeout from 30m to 1hr due to recent timeouts.
=> Increasing Cloud Build jobs timeout from 30m to 1hr

cli_tools/gce_ovf_import/main.go
The README for OVF import says that the default timeout is 2 hours, but the parser wasn't configured with that value.
This was surfaced after  #1497 where the e2e tests started failing with "Error parsing timeout ``". Prior to that PR, the tests succeeded since the timeout was parsed in a goroutine, rather than the main thread. An invalid timeout would kill that goroutine, but allow the main thread to continue.
https://github.com/GoogleCloudPlatform/compute-image-tools/blob/df208b7437289a35aff067d9f8539c670d4af9e2/cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go#L414
https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-ovf-import-e2e-tests-daily/1355045772277583872
=> OVF import: Specify default timeout

daisy_workflows/image_import/windows/run_startup_scripts.cmd, daisy_workflows/image_import/windows/run_startup_scripts_x86.cmd, daisy_workflows/image_import/windows/translate.ps1
- Added scheduled restart to the run_startup_scripts/run_startup_scripts_x86.cmd that is cancelled by translate.ps1. If translate.ps1 does not start the restart has generally been shown to address the underlying OS networking issue.
- Adding logging to run_startup_scripts.cmd to help identify what operation a system stops at.
=> Adding restart in the startup scripts that is cancelled by translate.ps1

cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
This bug was caused by #1512, and was observed in the e2e tests:
`cannot create instance: bad InitializeParams.DiskName: "-1"; * cannot create disk "-1"; resource lookup error: unknown resource type: "projects/compute-image-test-pool-001/zones/us-central1-c/disks/-1"`
https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-ovf-import-e2e-tests-daily/1357763952053850112
It occurred since the instance name was being used as a prefix for data disk names; in GMI import, the use doesn't specify an instance name.
=> GMI import worker: Use alphabetic prefix on data disks

cli_tools_cloudbuild.yaml
onestep importer needs to be everywhere original importer located because gcloud use the same finding logic.
=> [importer] build onestep importer

daisy/compute/compute.go, daisy/instance.go, daisy/instance_test.go, daisy/step_create_instances.go
When using the WaitForInstancesSignal with a port other than 1:
"WaitForInstancesSignal": [{
"Name": "builder",
"SerialOutput": {
"Port": 3,
"SuccessMatch": "BuilderSuccess:",
"FailureMatch": "BuilderFailure:",
"StatusMatch": "BuilderStatus:"
}
}]
It is not possible to see the entire serial port logs in GCS due to the
fact that the logging is actually an attribute of the CreateInstances
and the port number there is hardcoded to 1.
Introduce SerialPortToLog parameter for instance base to configure which
serial port is being logged for the given instance.
=> Add SerialPortToLog parameter to InstanceBase

cli_tools/common/distro/distro.go, cli_tools/common/distro/distro_test.go, cli_tools/import_precheck/check_osversion.go, cli_tools/import_precheck/check_osversion_test.go, cli_tools/import_precheck/check_sha2.go, cli_tools/import_precheck/main.go
This updates the precheck tool to remove its hardcoded list of supported operating systems. 
```
##############################
##############################
* FATAL: debian-10 is not supported for import. For supported versions, see https://cloud.google.com/sdk/gcloud/reference/compute/images/import
```
```
###############################
###############################
* INFO: Unrecognized distro `fedora`
* INFO: Unable to determine whether your system is supported for import. For supported versions, see https://cloud.google.com/sdk/gcloud/reference/compute/images/import
```
```
##############################
##############################
* INFO: Detected system: debian-9
```
```
##############################
##############################
* INFO: Detected Windows version number: NT …
```
=> Precheck tool: Use common OS list

daisy_workflows/export_metadata/export_metadata.wf.json, daisy_workflows/image_build/debian/debian.wf.json, daisy_workflows/image_build/debian/debian_fai.wf.json, daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json, daisy_workflows/image_import/debian/translate.py, daisy_workflows/image_import/debian/translate_debian.wf.json, daisy_workflows/image_import/enterprise_linux/translate.py, daisy_workflows/image_import/enterprise_linux/translate_el.wf.json, daisy_workflows/image_import/freebsd/translate_freebsd.wf.json, daisy_workflows/image_import/ubuntu/translate.py, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json, daisy_workflows/linux_common/tests/test_guestfsprocess.py, daisy_workflows/linux_common/utils/common.py, daisy_workflows/linux_common/utils/guestfsprocess.py
Recently we had test failures that said "Unable to correct problems, you have held broken packages", but did not include any useful debug information. This occurred since guestfs's `g.sh` and `g.command` hides stdout when a command fails.
https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1359454353202614272
This PR does the following:
1. Replaces usages of  `g.sh` and `g.command` with `guestfsprocess.run` throughout import
2. Adds an optional parameter `check` to `guestfsprocess.run`. It  follows the semantics of [subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run), which this module is emulating.
- Ran e2e tests for image import
- Ran image builds for workflows that were modified by this PR
=> Image import: Increase debug support when translation fails

cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
Enable onestep-import gcloud e2e due that we will land gcloud surface soon.
It needs to be merged earlier than gcloud cl submitting so that the gcloud code can be tested before it's TUE publishing.
=> Enable onestep-import gcloud e2e

cli_tools/common/image/importer/api_inflater.go, cli_tools/common/image/importer/api_inflater_test.go, cli_tools/common/image/importer/daisy_inflater.go, cli_tools/common/image/importer/daisy_inflater_test.go, cli_tools/common/image/importer/inflater.go, cli_tools/common/image/importer/inflater_test.go, cli_tools/go.mod, cli_tools/go.sum, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go, cli_tools_tests/module/import/inflater_test.go
This PR will start using API inflater as the main inflater.
Shadow test mode: daisy inflater as main inflater; API inflater as shadow test.
Fallback mode: api inflater as main inflater; daisy inflater as fallback inflater (expect to be used by non-vmdk).
Changes:
1. api_inflater: use a flag "isShadowTest" to determine whether to run shadow-test-only logic (calculate checksum for example).
2. Split "inflater.go" to "daisy_inflater.go" and "inflater.go"; "inflater_test.go" is split accordingly.
3. Renamed original "inflaterFacade" to "shadowTestInflaterFacade", which handles shadow-test mode; added a new "inflaterFacade" to handle fallback mode. Added tests accordingly.
New logic is only in api_inflater.go and inflater.go. Others are only code movement or trivial changes.
=> [vmdk api adoption] Switch from shadow-test mode to fallback mode

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
The reason of this change: when switched to API inflater from the daisy infalter, the inflation step won't fail on service account permission. Instead, it will fail on the inspection step. Thus, we need to modify the expected error message.
=> [e2e fix] adjust err msg for disabled-account-service testcase

daisy_workflows/image_build/windows/windows-server-2016-dc-bios-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-bios-byol.wf.json
* Add 'cloudsdk' variable to let users specify a custom
URL to the Cloud SDK installer. This fixes the problem
that the default GCS path is not publicly accessible.
* Pass 'pwsh' to 'windows-build' step. This fixes an infinite
loop in the SetupComplete stage.
=> Add missing variables to Windows image build workflow

cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Applies fix from #1107 to machine image e2e tests.
Test failure:
```
[debug]: 2021-02-23T09:18:42Z osID candidates: from-user="ubuntu-1604", ovf-descriptor=""
[import-ovf]: 2021-02-23T09:18:42Z Will create instance of `n1-standard-4` machine type.
[import-ovf]: 2021-02-23T09:18:45Z Failed to create disk by api inflater: googleapi: Error 409: The resource 'projects/compute-image-test-pool-001/zones/us-central1-c/disks/disk-ovf-1364105833373241344-1' already exists, alreadyExists
[import-ovf]: 2021-02-23T09:18:45Z Cleaning up.
[import-ovf]: 2021-02-23T09:18:46Z Failed to create disk by api inflater: googleapi: Error 409: The resource 'projects/compute-image-test-pool-001/zones/us-central1-c/disks/disk-ovf-1364105833373241344-1' already exists, alreadyExists
[OVFMachineImageImportTests] …
```
=> Fixed OVF machine image e2e tests failing due to multiple tests sharing single Cloud Build

cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
To reduce the e2e test time, we only test windows scenario for wrapper.
It's fine since the aws-related code for windows and for linux is the same.
=> [onestep-import e2e] only test windows for wrapper

daisy_workflows/image_build/debian/build.py
python3-yaml is needed for the subsequent 'import yaml' line in build.py
python-requests is needed for bootstrap-vz (although not declared in their documentation)
=> add debian 9 build deps

cli_tools/gce_ovf_import/domain/ovf_import_params.go, cli_tools/gce_ovf_import/main.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go, cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go, common/gcp/instance.go
OVF Import: added -scope flag to allow custom instance access scopes. This is needed as the resulting instance/GMI will have custom service account set. Without the ability to set scopes as well, instance will be set with no scopes, potentially restricting what can be accessed from instance. 
Also added the check for service account in GMI E2E import test, since service accounts are preserved preserved by GMIs and transfered to any VMs screated from them.
=> OVF Import: added -scope flag to allow custom instance access scopes

cli_tools/common/image/importer/request.go, cli_tools/common/image/importer/request_test.go, cli_tools/gce_ovf_import/README.md, cli_tools/gce_ovf_import/domain/ovf_import_params.go, cli_tools/gce_ovf_import/main.go, cli_tools/gce_ovf_import/multi_image_importer/request_builder.go, cli_tools/gce_ovf_import/multi_image_importer/request_builder_test.go, cli_tools/gce_vm_image_import/README.md, cli_tools/gce_vm_image_import/cli/args.go, cli_tools/gce_vm_image_import/cli/args_test.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
The `-byol` flag allows users to import systems with existing licenses when OS detection is enabled.
In addition to adding the flag, this adds logic to interpret when a user specifies both `-os` and `-byol`.
=> Add -byol flag to OVF import

daisy_workflows/export_metadata/export-metadata.ps1, daisy_workflows/export_metadata/export-metadata.py, daisy_workflows/export_metadata/export_metadata_windows.wf.json
This workflow is compare to linux export-metadata. 
Create a windows instance:
Using startup script run export-metadata powershell script
export image/package information as a json file and upload to GCS
Test: 
```daisy -gcs_path=gs://hanga-testing-daisy-bkt/daisy/hanga -project=hanga-testing \
-var:metadata_dest=gs://metadata-test-hanga \
-var:image_id=test-id \
-var:image_name=test-name \
-var:image_family=test-family \
-var:source_image="projects/windows-cloud/global/images/windows-server-1909-dc-core-v20210212" \
-var:uefi=true \
${HOME}/IdeaProjects/compute-image-tools/daisy_workflows/export_metadata/export_metadata_windows.wf.json
```
daisy log
https://storage.cloud.google.com/hanga-testing-daisy-bkt/daisy/hanga/daisy-export-metadata-20210223-20%3A17%3A52-3mxzr/logs/inst-exporter-exp …
=> add export metadata for windows

daisy_workflows/image_import/windows/translate.ps1, daisy_workflows/image_import/windows/translate_bootstrap.ps1
Adding a 5 second delay prior to dismounting a registry hive when the registry has been modified to allow updates to complete.
This is to address Access Denied issues when attempting to dismount the registry.
- I initially adding retries by changing run-command to use Process objects and that introduced unexpected issues with long arguments strings.
- I attempted to use cmdlets to update the registry entries and found they cannot be used on mounted registry hives.
=> Windows: Wait 5 seconds before dismounting registry files

cli_tools/gce_ovf_import/domain/ovf_import_params.go, cli_tools/gce_ovf_import/main.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go, cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go, cli_tools_tests/e2e/variables.go, daisy_workflows/ovf_import/create_gmi.wf.json, daisy_workflows/ovf_import/create_instance.wf.json, test-infra/prow/config.yaml
OVF Import: introduced instance service account (applied on imported VMs/GMIs), separate from compute service account used for worker instances. This is to allow users to specify more restrictive service accounts on imported instances than needed for worker instances.
=> OVF Import: introduced instance service account flag

cli_tools/common/image/importer/inflater.go
This adds a new filed `ImageImportRequest.FormatsWithParallelInflation` which controls which disk file formats are processed in parallel using the PD API. Currently the map is empty, therefore calling the PD API is disabled.
Ran an OVF import using the three-disk OVA that was failing with deadlock.  When run with this PR and https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1561, the import failed as expected rather than deadlocking.
=> Image import: Disable calling PD API.

cli_tools/common/utils/daisy/daisy_utils.go, cli_tools/gce_image_publish/main.go, daisy/cli/main.go, daisy/daisy_test_runner/main.go, daisy/step_create_instances.go, daisy/workflow.go, daisy/workflow_test.go
This PR adds a method called `daisy.Workflow.CancelWorkflow()` that is idempotent, and protects against closing an already-closed channel.
Background: Image import has had panics when manually closing workflows, since we (currently) close a workflow by closing its `Cancel` channel.
Here's an example scenario that would cause a panic:
1. Daisy fails here: https://github.com/GoogleCloudPlatform/compute-image-tools/blob/423907b63e7430a8e9dbe5edb296e4811f73797a/daisy/workflow.go#L302
2. The shadow inflater reaches here: https://github.com/GoogleCloudPlatform/compute-image-tools/blob/b5310952cee40f215182002d869188396582b0c6/cli_tools/common/image/importer/inflater.go#L188
=> Daisy: Don't panic when workflow is canceled twice

cli_tools/gce_image_publish/main.go, cli_tools/gce_image_publish/publish/publish.go
For https://github.com/GoogleCloudPlatform/compute-image-tools/issues/1576
For my use case my workflow is per-image based, and I will need to manage the imagesCache after we finish executing the deletion workflow.
This should make the usage more flexible.
=> Make imagesCache usage optional.

daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-10-20h2-ent-x86-bios-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-sac-1909-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-sac-2004-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-sac-20h2-dc-core-uefi-payg.wf.json
The current 3h timeout is often not enough to complete a build.
=> Increase build timeout to 4h

test-infra/prow/config.yaml
Added compute-image-test-pool-001-1 and compute-image-test-pool-001-2 projects to cleanerupper config after noticing stale disks from the past 3 months in these two projects.
=> Added compute-image-test-pool-001-1 and compute-image-test-pool-001-2 projects to cleanerupper config

cli_tools/import_precheck/check_disks_linux.go, cli_tools/import_precheck/check_disks_linux_test.go, cli_tools/import_precheck/testdata/lsblk-efi.json, cli_tools/import_precheck/testdata/lsblk-multi-disk-lvm.json, cli_tools/import_precheck/testdata/lsblk-one-partition.json, cli_tools/import_precheck/testdata/lsblk-single-disk-lvm.json
Prior to this, the precheck tool falsely reported that a system was importable when the root device spanned multiple physical disks (typically due to usage of LVM). 
- Created a multi-disk LVM system that reproduced the original issue, and confirmed that this PR solves it.
- Added unit tests that run against `lsblk` output from four representative disk layouts (single disk, EFI, multiple disks that should pass, multiple disks that should fail).
=> import_precheck: Fail when root device spans multiple physical disks

daisy_workflows/image_import/enterprise_linux/translate.py
The CentOS 8 import tests occasionally fail during post-translate-boot with an XFS corruption: `XFS (dm-1): Internal error XFS_WANT_CORRUPTED_RETURN at line 1526 of file fs/xfs/libxfs/xfs_ialloc.c.  Caller xfs_dialloc_ag+0x189/0x280`
https://prow.k8s.io/view/gs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1376882538995257344
Looking at translation logs for failing and successful test runs, there's a failure when unmounting the guest's filesystem:
```
Mar 30 15:37:47 inst-translator-translate-translate-disk-zzpg1 GCEMetadataScripts[824]: 2021/03/30 15:37:47 GCEMetadataScripts: startup-script-url: TranslateDebug: umount_all: umount: /sysroot/dev: umount: /sysroot/dev: target is busy
Mar 30 15:37:47 inst-translator-translate-translate-disk-zzpg1 …
```
=> EL import: Retry GuestFS cleanup on failure

cli_tools/common/image/importer/bootable_disk_processor.go
Before this, if there was an error during import (such as a timeout), the user would still see `Finished making disk bootable`.
=> Image import: Don't log success on timeout

cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
OVF import E2E tests: moved service-account/scopes tests to test gcloud (instead of wrapper); merged instance import network e2e tests with existing OS based tests to reduce the number of total tests run.
=> OVF import E2E test changes

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, daisy_integration_tests/ubuntu_1604_vmware_translate.wf.json, daisy_integration_tests/ubuntu_1804_aws.wf.json, daisy_integration_tests/ubuntu_1804_azure.wf.json, daisy_integration_tests/ubuntu_1804_vmware.wf.json, daisy_workflows/image_import/ubuntu/translate.py
Following this PR, when an Ubuntu import includes the guest environment, the OS Config agent will be installed.
There are some caveats:
- The agent is only available in 16.04 and newer: https://packages.ubuntu.com/search?keywords=google-osconfig-agent
- The package is available in Ubuntu's `updates` repo, which is an optional repo. If installation fails, we write a log with manual install instructions.
=> Image import: Install OS Config agent in Ubuntu

cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/export/image_export_test_suite.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
OVF import fixes to support Oracle provided Oracle Linux OVAs: 
* disks that are not attached to any controllers in OVF descriptor
* another format for disk host resource prefix (`ovf:disk/`)
* added E2E test for Oracle Linux as CentOS
* E2E test naming cleanup 
Run the new E2E test and tested manually with https://yum.oracle.com/templates/OracleLinux/OL7/u9/x86_64/OL7U9_x86_64-olvm-b77.ova
=> OVF import fixes to support Oracle provided Oracle Linux OVAs

cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go
OVF export e2e test: use latest wrapper when re-importing OVF to ensure fixes to OVF importer are reflected in OVF export tests
=> OVF export e2e test: use latest wrapper when re-importing OVF

daisy_workflows/export_metadata/export-metadata.py, daisy_workflows/export_metadata/export_metadata.wf.json
* continue on per-package errors, allowing empty package metadata
* move final copy to daisy workflow for cleaner soc and permissions
* capture all exceptions during upload to give better error messages
=> publish empty metadata

cli_tools/common/utils/storage/scratch_bucket_creator.go, cli_tools/common/utils/storage/scratch_bucket_creator_test.go
Cloud Bucket policy prevents the use of 'google.com' in the name. Replace it with the friendlier 'google_com' so we don't also chop off the front of the scratch bucket name.
=> Replace 'google.com' with 'google_com' in bucket names.

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_integration_tests/daisy_e2e.test.gotmpl
Reverts GoogleCloudPlatform/compute-image-tools#1616
=> Revert "Disabling CentOS image import tests"

daisy/compute/compute.go
- Adding "server sent GOAWAY" as a response that should be retried.
- Sleeping 5 seconds instead of 1 second, when a "PENDING", "RUNNING" operation status is received.
=> Adding "server sent GOAWAY" as a response that should be retried.

cli_tools_tests/e2e/gce_ovf_import/scripts/ovf_import_test_ubuntu_3_disks.sh, daisy_integration_tests/scripts/post_translate_test.sh
This updates the Linux post-translate tests to verify that the root account and non-system accounts have locked passwords.
I've done a mass update to lock these passwords in the images in `compute-image-tools-test` and the test OVAs, and have created backups in case we see a regression.
=> Ensure Linux test images have locked passwords

daisy_workflows/image_import/suse/suse_import/translate.py
This adds support for importing SLES 15.0 (we currently have support for SLES 15 SP1 and SP2). Manually tested (see below). E2E tests will come in a PR tomorrow; submitting this now to unblock a user.
- Manually tested importing the following:
- SLES  for SAP 15.0  BYOL
-  SLES 15.0 on-demand  
- SLES for SAP 15.0 on-demand
=> Image import: Add support for SLES 15.0

daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg
`dnf clean all` do not clean everything stored in dnf cache.
At least it keeps fastestmirror dnf plugin cache that enabled on AlmaLinux by default.
So I propose to delete dnf cache completely during image build.
=> Clean up dnf cache completely on el8

daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-byol.wf.json
This PR changes the licensing string for Windows Server 2019 Core BYOL workflow (`windows-server-2019-dc-core-uefi-byol.wf.json`) from SPLA to BYOL.
=> Add -byol string to avoid building SPLA image

daisy/step_deprecate_images.go, daisy/step_deprecate_images_test.go
- Adding ACTIVE to the deprecated status, to make the possible values in the API https://pkg.go.dev/google.golang.org/api/compute/v0.alpha#DeprecationStatus
- Fixing bug to error when "not in list"
- Adding DeprecationStatus tests for Alpha API
=> Updating DeprecationStatus in Daisy Alpha API

cli_tools/go.mod
Updating Daisy dependency for CLI tools, so GCE_Image_Publish can get the update in PR #1650
=> Updating Daisy dependency for CLI tools

cli_tools/gce_ovf_import/domain/ovf_import_params.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go, cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_import_e2e_common.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
During OVF import, the user can provide tags using the `--tags` flag. A user reported this feature wasn't working. It's unclear where this functionality was lost. Running an import prior to the recent refactoring doesn't yield an instance with tags applied; eg:
```
gcloud beta compute instances import  tagtest \
--source-uri=gs://<yourbucket>/ubuntu-ova/ \
--zone=us-central1-c \
--tags=tag1,tag2,tag3  \
--docker-image-tag=8f8fff9d757e70b8a09257e038ed7ecf51ab606f  \
--os ubuntu-1604
```
* Added e2e tests for instance import and GMI import that verify tags were applied
* Manually imported an instance and a GMI and verified that tags were applied
=> OVF import: Apply user-provided tags to final instance

cli_tools_tests/e2e/gce_image_import_export/test_suites/export/image_export_test_suite.go
Run image export E2E tests in a couple of different regions to perform a sanity check on regional Cloud Builds. Use regional buckets for eu/asia to avoid copying across multiregions (expensive)
=> Run image export E2E tests in a couple of different regions

cli_tools/common/distro/distro.go, cli_tools/common/distro/distro_test.go, cli_tools/common/image/importer/bootable_disk_processor.go, cli_tools/common/image/importer/bootable_disk_processor_test.go, cli_tools/common/image/importer/errors.go, cli_tools/common/image/importer/errors_test.go, cli_tools/common/image/importer/process_planner.go, cli_tools/common/image/importer/process_planner_test.go, cli_tools/common/image/importer/processor.go, daisy_workflows/linux_common/utils/diskutils.py
When Linux import fails, and the detected OS doesn't match the specified OS, we show a customized error message (added in https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1206). 
This PR provides the following improvements:
1. Support Windows in addition to Linux
2. Differentiate between flavors of SLES
To achieve this, we use the [new OS detection module](https://github.com/GoogleCloudPlatform/compute-image-tools/tree/master/daisy_workflows/image_import/inspection) that is run against all bootable disks, rather than the quick detection that was used in #1206 which ran only for Linux.
=> Improve error message when detected OS doesn't match specified OS.

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
Image import E2E test to run in different zones. This will help verify regional Cloud builds.
=> Image import E2E test to run in different zones. 

cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_export/exporter/exporter_test.go
This is a follow-up to #1666, which introduced a regression such that exports are blocked when the user specifies the source images as a URI. This PR limits validation to obvious image names. This avoids false negatives where the user specifies a source image that Daisy understands, but hasn't been implemented here. 
Failure message: https://github.com/GoogleCloudPlatform/compute-image-tools/commit/58a99dea0dd1703c93a1b8a7f04a658401528f10#commitcomment-52286130
=> Image export: Only validate non-URI images

cli_tools_tests/e2e/gce_image_import_export/test_suites/export/image_export_test_suite.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Image export and OVF import regional E2E tests to use asia-northeast1 due to stockouts in asia-east1 and due to inability to run Google workloads in asia-east2.
Also, use multiregional images for export tests to avoid cross-multiregion transfers.
=> Image export and OVF import regional E2E tests to use asia-northeast1

cli_tools/common/image/importer/api_inflater.go, daisy_workflows/export/export_disk.sh, daisy_workflows/export/export_disk_ext.sh, daisy_workflows/image_import/import_image.sh
Add "stdbuf -oL" to "echo" for serial-output key so the format won't be broken.
ref to b/167607270.
Tested by running export locally.
=> avoid interleaved output

cli_tools/common/utils/storage/scratch_bucket_creator.go, cli_tools/common/utils/storage/scratch_bucket_creator_test.go
Periods can be used in the creation of a GCS bucket, but if it exists
then there is a requirement that the domain that is used with the period
be owned or registered with the project. We can instead modify the project name to use
elgoog_com so that we do not rely on a project owning that domain.
https://cloud.google.com/storage/docs/naming-buckets#example_bucket_names
=> Modify scratch bucket creation name to not use "."

cli_tools/common/utils/storage/resource_location_retriever.go
* Prefer `europe-west4` over `europe-north` when source file is in `eur4` dual region as `europe-west4` is supported by Cloud Build as of now.
* Added support for `ASIA1` dual region when determining zone to run operations in.
=> Update dual-region to region mappings

cli_tools/gce_onestep_image_import/main.go
To help customers easily find the guide, output the help link when onestep import failed.
=> [onestep import] output help link for customers

cli_tools/common/image/importer/daisy_inflater.go
[no prod impact] This only impacts the shadow test output.
Minimum 10gb of disks will be allocated. We want to output that number correctly.
=> [import] calculate alloc size with minimum limit 10gb

daisy_workflows/image_import/windows/network.ps1, daisy_workflows/image_import/windows/run_startup_scripts.cmd, daisy_workflows/image_import/windows/run_startup_scripts_x86.cmd, daisy_workflows/image_import/windows/translate.ps1, daisy_workflows/image_import/windows/translate_bootstrap.ps1, daisy_workflows/image_import/windows/translate_windows_wf.json, daisy_workflows/image_import/windows/translate_windows_x86_wf.json
- Adding network.ps1 which is launched by run_startup_scripts.cmd
- Added network.ps1 to workflow files so it's copied into the components GCS location
- Added copying network.ps1 to instance in translate_bootstrap.ps1
- network.ps1 does the following:
- Verified that the connected adapter is set to DHCP, is set the static IP it will change the adapter to DHCP and set the DNS server to also be obtained by DHCP. If updated it will also restart the network adapter and wait 30 seconds via a ping test.
- It will always test connectivity to packages.cloud.google.com and output the DNS configuration of the adapter.
=> Adding detection and remediation of static IP & DNS

cli_tools/gce_onestep_image_import/README.md, cli_tools/gce_onestep_image_import/onestep_importer/importer.go, cli_tools/gce_onestep_image_import/onestep_importer/importer_test.go, cli_tools/gce_ovf_export/README.md, cli_tools/gce_ovf_export/exporter/param_validator.go, cli_tools/gce_ovf_export/exporter/param_validator_test.go, cli_tools/gce_ovf_import/README.md, cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go, cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go, cli_tools/gce_vm_image_export/README.md, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_export/exporter/exporter_test.go, cli_tools/gce_vm_image_import/README.md, cli_tools/gce_vm_image_import/cli/args.go, cli_tools/gce_vm_image_import/cli/args_test.go, cli_tools/gce_windows_upgrade/upgrader/validators.go, cli_tools/gce_windows_upgrade/upgrader/validators_test.go
`client_id` is used for logging and metrics, and we're seeing failures where operations are failing when this parameter is not passed. Following this PR, `client_id` will be optional for all CLI tools; when omitted, the value is the empty string.
=> CLI Tools: Make client_id optional

daisy/common.go, daisy/test_data/TestNewFromFile_SupportsNestedVariables.child.wf.json, daisy/test_data/TestNewFromFile_SupportsNestedVariables.parent.wf.json, daisy/test_data/TestNewFromFile_SupportsNestedVariables_VarInFilename.child.wf.json, daisy/test_data/TestNewFromFile_SupportsNestedVariables_VarInFilename.parent.wf.json, daisy/workflow_test.go
This fixes a regression from #1701 where child workflows were receiving the autovars from their parents.
Example failure [source](https://oss-prow.knative.dev/view/gs/compute-image-tools-test/logs/ci-daisy-e2e/1420369751300902912).
```
[image-import-and-translate-custom-network-test]: 2021-07-28T13:07:26Z Validating workflow
[image-import-and-translate-custom-network-test]: 2021-07-28T13:07:26Z Validating step "create-network"
[image-import-and-translate-custom-network-test]: 2021-07-28T13:07:26Z Validating step "create-subnetwork"
[image-import-and-translate-custom-network-test]: 2021-07-28T13:07:27Z Validating step "import-and-translate-image"
[image-import-and-translate-custom-network-test.import-and-translate-image]: 2021-07-28T13:07:27Z Validating step "import" …
```
=> Daisy: Don't clobber child variables from parent workflow

cli_tools/gce_image_publish/publish/publish.go
trying to look into https://github.com/GoogleCloudPlatform/compute-image-tools/issues/1576, but looks like this is not the culprit as we do check for existing dependencies in https://github.com/GoogleCloudPlatform/compute-image-tools/blob/4daadb12a29336c34f1ee255294839d594e3748c/daisy/workflow.go#L562
=> I assume here we don't need the duplicated dependency

cli_tools/common/utils/paramhelper/resources.go, cli_tools/common/utils/paramhelper/resources_test.go
This fixes a bug in #1699 where validation fails when the network or subnetwork is specified using apiary style URLs. The failure was:
```
[image-export] 2021/08/02 07:45:19 "https://www.googleapis.com/compute/v1/projects/compute-image-test-pool-001/regions/us-central1/subnetworks/compute-image-test-pool-001-subnet-1" is not a valid subnet resource identifier. See https://cloud.google.com/compute/docs/reference/rest/v1/subnetworks/get for naming guidelines.
```
https://oss-prow.knative.dev/view/gs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1422101173669728256
After this PR, the tool supports both full URI formats shown in go/gce-aips/2813.
=> CLI tools: Accept legacy apiary URL styles for resources

cli_tools/common/utils/param/populator.go, cli_tools/common/utils/param/populator_test.go
This fixes a bug in #1699 where validation fails when region population is required. The failure was:
`Invalid value for field 'region': ''`
https://oss-prow.knative.dev/view/gs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1422101173669728256
=> CLI Tools: Populate region prior to network

cli_tools/common/image/importer/bootable_disk_processor.go, cli_tools/common/image/importer/bootable_disk_processor_test.go, cli_tools/common/image/importer/processor_test.go
This works toward our larger goal of splitting daisy out of the compute-image-tools repo.
Testing:
* Added unit tests for no-external-ip (default behavior, and behavior when flag enabled)
* Added unit tests to verify privacy log hook is applied
* Updated existing unit tests that verify resource labeling 
* Ran an import to verify no-external-ip still functions
* Ran an import to verify resource labeling
=> Daisy Refactor: Remove validation hooks from bootable disk processor

cli_tools/common/utils/storage/buffered_writer.go, cli_tools/common/utils/storage/buffered_writer_test.go, cli_tools/gce_export/main.go, cli_tools/gce_onestep_image_import/onestep_importer/aws_importer.go
Motivation: customer faced issue: the failed msg is only in serial log, not in gcloud console. Fixed by allowing setting proper err log prefix.
Also, the err match regex is changed from storage.object.create to to storage.object.* because a customer failed due to the lack of storage.object.get.
There will be another fix on gcloud: the permission issue was not caught by gcloud permission check.
=> [cli-tools] fix buffered writer err log prefix so it can be picked up by 'waitForInstanceSignals'

daisy_workflows/image_import/import_image.sh
This change enables qemu-img's `--target-is-zero` option. Since we're writing to new persistent disks, we don't need to re-zero the destination.
This table shows the elapsed  time (minutes:seconds) for running `daisy_workflows/image_import/inflate_file.wf.json` against four different disk files. Overall, applying this PR results in ~2x speedup for inflation. Notably, this speedup includes file types other than VMDK; the one VHD example had a nearly 3x speedup.
FileGB | DiskGB | Type | Operation | Duration
-- | -- | -- | -- | --
24 | 82 | VMDK | Legacy | 33:47
24 | 82 | VMDK | NoZero | 17:54
24 | 82 | VMDK | NoZeroS512 | 17:34
24 | 82 | VMDK | Native | 1:58
2 | 10 | VMDK | Legacy | 5:14
2 | 10 | VMDK | NoZero | 1:59
2 | 10 | VMDK | NoZeroS512 | 1:51
2 | 10 | VMDK | Native | 0:34
0.3 | 10 | …
=> Image import: Don't re-zero PDs

daisy_workflows/image_import/import_image.sh
Using `--target-is-zero` caused test failures since `qemu-img` on the inflation worker instance doesn't have the `--target-is-zero` flag: that was added in qemu-img 5. The worker instance has version 2.8.1.
Failed tests:
- https://oss-prow.knative.dev/view/gs/compute-image-tools-test/logs/ci-daisy-e2e/1423045403158253568
- https://oss-prow.knative.dev/view/gs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1422944487633588224
=> Revert "Image import: Don't re-zero PDs (#1709)"

cli_tools/common/utils/validation/validation_utils.go, cli_tools/common/utils/validation/validation_utils_test.go
OVF import: fix project IDs validation by supporting "google.com:" prefix. This was failing import for internal Google App Engine projects.
=> OVF import: fix project IDs validation by supporting "google.com:" prefix

cli_tools/gce_vm_image_import/README.md
Fix flag names in gce_vm_image_import README (underscore vs dash). Also some flags have a double dash before the flag name.
=> Fix flag names in gce_vm_image_import README (underscore vs dash)

cli_tools/common/utils/logging/service/log_entry.go, cli_tools/gce_vm_image_export/main.go
This adds logging for snapshot export, which was implemented in https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1627.
For testing, I created a snapshot, exported it, and observed that the input params were captured.
=> Image Export: Add logging for snapshot export

cli_tools/test_data/test_import_ovf_to_instance.wf.json, cli_tools/test_data/test_import_ovf_to_machine_image.wf.json, daisy/disk.go, daisy/disk_test.go, daisy_workflows/image_import/import_and_translate.wf.json, daisy_workflows/image_import/import_from_image.wf.json, daisy_workflows/image_import/inflate_file.wf.json, daisy_workflows/ovf_import/import_ovf_to_instance.wf.json, daisy_workflows/ovf_import/import_ovf_to_machine_image.wf.json
We added `disk.IsWindows` in #935 to assist feature development in the CLI tool. The `isWindows` param is no longer required since we handle it manually now:
https://github.com/GoogleCloudPlatform/compute-image-tools/blob/7964ff4bbecbb5c6e253be250d8083821f9a194a/cli_tools/common/image/importer/daisy_inflater.go#L121
=> Daisy: Remove disk.IsWindows

cli_tools/common/image/importer/bootable_disk_processor.go, cli_tools/daisycommon/daisy_worker.go, cli_tools/daisycommon/daisy_worker_test.go, cli_tools/gce_ovf_export/exporter/instance_disks_exporter.go, cli_tools/gce_ovf_export/exporter/steps.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go, cli_tools/gce_vm_image_export/exporter/exporter.go, daisy/workflow.go
This is part of our initiative to move daisy out of `compute-image-tools`. It removes the method `RunWithModifiers` from the `daisy.Workflow` struct, and updates its call sites to use the `Run` method.
=> Remove workflow.RunWithModifiers

daisy/step_wait_for_instances_signal.go, daisy/step_wait_for_instances_signal_test.go, daisy_workflows/image_import/import_image.sh
We detected broken <serial-output> line, which caused checksum mismatch for disk checksum verification.
After a serial of test, we realized that any serial output streamed to daisy-log may be broken, because each "ComputeClient.GetSerialPortOutput" can get a incomplete output result. Example:
Full output:
123456789
abcdefg
987654321
ComputeClient.GetSerialPortOutput call1 get:
123456789
abc
ComputeClient.GetSerialPortOutput call2 get:
defg
987654321
The possible reason is that, stdout output (like "echo") relies on a buffer, whose size is usually PIPE_BUF=512 bytes, which can't be modified. Once the buffer is full, it will be flushed, even though the whole line hasn't been written.
The checksum output is much longer than others (302 bytes), so it has much higher chance to hit this issue. …
=> [daisy] fix output breakage for waitForInstanceSignal

daisy/compute/compute.go, daisy/compute/test_client.go, daisy/compute/test_client_test.go, daisy/step_wait_for_instances_signal.go, daisy/step_wait_for_instances_signal_test.go, daisy_integration_tests/step_wait_for_instance_signal.wf.json
* Move GetGuestAttributes out of beta compute client
* Add support for GuestAttributes config in WaitForInstancesSignal
Test results. Using this config:
```
"wait": {
"WaitForInstancesSignal": [
{
"Name": "inst-builder",
"GuestAttribute": {
"KeyName": "heh/fake-key",
"SuccessValue": "heh"
}
}
]
}
```
Test instance that has wrong value fails:
```
[test-guest-attrs]: 2021-08-11T18:15:18-07:00 Running step "wait" (WaitForInstancesSignal)
[test-guest-attrs.wait]: 2021-08-11T18:15:18-07:00 WaitForInstancesSignal: Instance "inst-builder-test-guest-attrs-gw3yn": watching for key heh/fake-key, SuccessValue: "heh".
[test-guest-attrs]: 2021-08-11T18:15:28-07:00 Error running workflow: step "wait" run error: WaitForInstancesSignal bad guest attribute value found for …
```
=> Daisy:support guestattrs in WaitForInstancesSignal

daisy_integration_tests/step_wait_for_instance_signal.wf.json
my previous invocation of the integ test worked because i have this key set at the project level. set it in the workflow to be sure it works.
=> enable guest attrs in wait integ test

daisy_workflows/image_import/enterprise_linux/translate_centos_8.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json, daisy_workflows/image_import/inspection/boot-inspect.wf.json
During import, a disk using LVM is failing to mount with guestfs 1.34, but successfully mounts with guestfs 1.40. 
We previously attempted to use the Debian 10 worker in https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1438; at that time 
Ultimately we'll need to migrate off Debian 9 completely. This change is a small step in that direction, and unblocks the user who is blocked on their import. 
- Ran the daisy e2e tests that had previously failed.
=> CLI Tools: Use deb10 worker for EL8 import and inspection

daisy_workflows/image_build/debian/debian_10_worker.sh, daisy_workflows/linux_common/bootstrap.sh, daisy_workflows/linux_common/utils/common.py
This is a followup to #1721; in image import, we're now seeing failures for Debian 10 when executing `apt -y update`:
```
apt -y update
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
```
Testing:
* Ran `daisy_integration_tests/debian_10_translate.wf.json `, which emitted the above error. Applied this PR, and the error was fixed.
=> apt update: use --allow-releaseinfo-change

daisy_workflows/image_build/debian/debian_10_worker.sh, daisy_workflows/linux_common/bootstrap.sh, daisy_workflows/linux_common/utils/common.py
#1730 was intended to fix Debian 10 import, but caused a regression where older versions of apt. eg: `Command line option --allow-releaseinfo-change is not understood in combination with the other options`
https://oss-prow.knative.dev/view/gs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1430390246482120704
=> Revert "apt update: use --allow-releaseinfo-change (#1730)"

cli_tools/common/utils/daisyutils/daisy_utils.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_workflows/image_import/debian/translate.py, daisy_workflows/image_import/debian/translate_debian_11.wf.json
This adds support for importing Debian 11 to image and instance import. 
Testing
- Passed an invalid `-os` to `gce_ovf_import` and `gce_vm_image_import` and confirmed that `debian-11` was in the list of suggested values.
- Manually ran an import of Debian 11 without `--os` and confirmed that inspection chose the correct translation workflow.
- Ran new and existing Debian import tests.
=> Image import: Support Debian 11

daisy_workflows/image_import/ubuntu/translate.py
This PR will fix issue #1747.
The solution could be one of `rm -f /etc/netplan/*.yaml` or `rm -rf /etc/netplan/*` but I would like to use the first approach to preserve everything on the image if they do not prevent making an image.
=> fix `/etc/netplan` clean up issue for Ubuntu 18+ which interrupts the import process

daisy_workflows/image_import/enterprise_linux/translate.py
In #1750 we removed support for the guest agent in EL6 due to a user report; after further research, we've found that the issue was in the user's VM.
=> Revert "EL6 import: Don't install guest packages (#1750)"

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_workflows/image_import/enterprise_linux/translate.py
This was prompted by a user's report of a failed RHEL 6 import, where the guest agent was crashing due to `rsyslog` not being enabled. This PR:
1. Enables the rsyslog service during translate for RHEL6. rsyslog is an [explicit dependency](https://github.com/GoogleCloudPlatform/guest-configs/blob/master/packaging/google-compute-engine.spec) for RHEL6, and while in RHEL 7+ it's [required to be running](https://github.com/GoogleCloudPlatform/guest-agent/blob/main/google-guest-agent.service#L10), in RHEL6, however, the init conf [doesn't assert that rsyslog is running](https://github.com/GoogleCloudPlatform/guest-agent/blob/main/google-guest-agent.conf). 
3. Added an e2e test.
=> EL6 import: Enable rsyslog and add e2e test

cli_tools/common/assert/assert.go, cli_tools/common/assert/assert_test.go, cli_tools/common/disk/inspect.go, cli_tools/common/image/importer/api_inflater.go, cli_tools/common/image/importer/bootable_disk_processor.go, cli_tools/common/image/importer/bootable_disk_processor_test.go, cli_tools/common/image/importer/daisy_inflater.go, cli_tools/common/image/importer/daisy_inflater_test.go, cli_tools/common/image/importer/inflater_test.go, cli_tools/common/image/importer/request.go, cli_tools/common/imagefile/qemu_img_test.go, cli_tools/common/utils/daisyutils/daisy_utils.go, cli_tools/common/utils/daisyutils/daisy_worker.go, cli_tools/common/utils/daisyutils/daisy_worker_test.go, cli_tools/common/utils/daisyutils/daisy_worker_testing.go, cli_tools/gce_ovf_import/domain/ovf_import_params.go, cli_tools/gce_ovf_import/domain/ovf_import_params_test.go, cli_tools/gce_ovf_import/multi_image_importer/request_builder.go, cli_tools/gce_vm_image_import/cli/args.go, cli_tools/mocks/mock_daisy_worker.go
This updates image import (and therefore a portion of OVF import) to use the DaisyWorker facade. Specifically:
1. Inflating the disk using qemu-img
2. Calculating the checksum of the API-inflated disk
3. Translating the disk
Disk inspection was already using the DaisyWorker facade.
=> Image Import: Use daisy worker

test-infra/prowjobs/cleanerupper/main.go
The third argument to `shouldDelete` should be a timestamp string.
Error without fix: `Error parsing create time "OS policy assignment API prober": parsing time "OS policy assignment API prober" as "2006-01-02T15:04:05Z07:00": cannot parse "OS policy assignment API prober" as "2006"`
/woof
=> fix cleanerupper deletion of OS policy assignments

cli_tools/common/image/importer/api_inflater.go
Now network/subnet in shadow test workflow is not respected.
Impact: some imports failed to run shadow test.
It's not urgent since:
1. It won't break any import result.
2. It just lost a very small portion of shadow test result, so it won't impact the shadow test conclusion.
Fix: populate the value from the request.
Manually tested on my own test project. It's not worth adding new e2e test due to the above reason, and also due that its testing requires default network to be deleted, which will impacts the existing test set.
=> [import] respect custom network/subnet in shadow test workflow

daisy_workflows/image_import/ubuntu/translate.py, daisy_workflows/linux_common/tests/test_apt.py, daisy_workflows/linux_common/utils/apt.py
This updates Ubuntu translate to avoid installing cloud-init 21.3-1, which blocks systemd from starting the guest agent on first boot. 
It achieves this by querying `apt` to find the available package versions, and picking a version such that 21.3-1 is avoided if possible. If a version other than 21.3-1 is found, this falls back to the previous behavior of allowing apt to choose which version to install. In this case, the guest agent will start after the first boot, which is the current behavior.
Testing:
- Ran Ubuntu e2e tests.
=> Ubuntu import: When possible, don't install cloud-init 21.3-1

cli_tools/common/mount/inspector_test.go, cli_tools/gce_windows_upgrade/upgrader/test_common_test.go, cli_tools/gce_windows_upgrade/upgrader/upgrader.go, cli_tools/gce_windows_upgrade/upgrader/utils.go, cli_tools/gce_windows_upgrade/upgrader/workflows.go
This changes windows upgrade to use the `DaisyWorker` facade. For testing, I ran the the tests in gce_windows_upgrade.Dockerfile.
=> Windows upgrade: Use daisy worker

cli_tools/gce_ovf_export/domain/args.go, cli_tools/gce_ovf_export/domain/args_test.go, cli_tools/gce_ovf_export/domain/test_data.go, cli_tools/gce_ovf_export/exporter/exporter.go, cli_tools/gce_ovf_export/exporter/instance_disks_exporter.go, cli_tools/gce_ovf_export/exporter/instance_export_cleaner.go, cli_tools/gce_ovf_export/exporter/instance_export_preparer.go, cli_tools/gce_ovf_export/exporter/steps.go
This updates `gce_ovf_export` to use the DaisyWorker facade, rather than making calls directly to `daisy.Worker.Run`.
For testing, I created a GCE instance with three disks, exported it before and after this PR and compared:
- The log output lines had the same prefixes
- Worker instances had the same label format
- The resulting exported OVFs were the same.
=> OVF Export: Use Daisy worker

daisy/workflow.go, daisy/workflow_test.go
Before if `DisableCloudLogging` was called, the `cloudLoggingClient` would still be created despite cloud logging explicitly not being enabled.
Added a condition to fix this behavior.
=> Stop creation of cloud logging client when cloud logging is disabled

cli_tools/common/utils/daisyutils/workflow_hook_workflow_vars.go, cli_tools/common/utils/daisyutils/workflow_hook_workflow_vars_test.go
While working on adding the module tests to presubmit hooks, I found that the DaisyWorker doesn't implement the logic from #1378 that ensures the network is inferred when the user only specifies the subnet. Prior to this PR, when using the DaisyWorker, the workflow would attempt to use the default value that's declared in the daisy workflow, which in the case of inspection is "global/networks/default"
Testing:
- Ensured that this test is passing now: https://github.com/GoogleCloudPlatform/compute-image-tools/blob/bc0c805f462ddeb9d9b7c15e146602a1da5e4c93/cli_tools_tests/module/diskinspect/disk_inspect_test.go#L430
=> CLI Tools: Ensure network is cleared when only subnet is specified

cli_tools/mocks/README.md
This adds a README file to explain our usage of mocks, and gives tips on updating existing mocks and creating new mocks.
=> CLI Tools: Document mocks

cli_tools/mocks/mock_daisy_logger.go, common/logging/logging.go, daisy/daisy_test_runner/main.go, daisy/logger.go, daisy/logger_test.go, daisy/step_create_instances.go
While debugging failed imports, I've noticed that a subset of logs don't include serial logs. This occurred since there's a race condition between reading serial port logs, and daisy declaring that the workflow is finished. The go routine that collects serial port logs continues after daisy makes that declaration, to ensure that all of the instances logs get sent to Cloud Logging in a single batch.
This PR ensures that serial port logs are eagerly collected, so that when a workflow finishes, `ReadSerialPortLogs` returns all of the instance's serial port logs. It achieves this by accumulating each portion of serial port logs as they're available, and enforces an explicit call to write to cloud logging. This allows a client of `daisy.Workflow` to call `ReadSerialPortLogs` at any point and …
=> Daisy: Eagerly record serial logs.

cli_tools/common/disk/inspect.go, cli_tools/common/image/importer/api_inflater.go, cli_tools/common/image/importer/bootable_disk_processor.go, cli_tools/common/image/importer/bootable_disk_processor_test.go, cli_tools/common/image/importer/daisy_inflater.go, cli_tools/common/image/importer/daisy_inflater_test.go, cli_tools/common/image/importer/inflater_test.go, cli_tools/common/image/importer/processor.go, cli_tools/common/utils/daisyutils/daisy_utils.go, cli_tools/common/utils/daisyutils/daisy_worker.go, cli_tools/common/utils/daisyutils/daisy_worker_test.go, cli_tools/common/utils/daisyutils/daisy_worker_testing.go, cli_tools/gce_ovf_export/exporter/instance_disks_exporter.go, cli_tools/gce_ovf_export/exporter/instance_export_cleaner.go, cli_tools/gce_ovf_export/exporter/instance_export_preparer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_windows_upgrade/upgrader/upgrader.go, cli_tools/gce_windows_upgrade/upgrader/upgrader_test.go, cli_tools/gce_windows_upgrade/upgrader/workflows.go, cli_tools/gce_windows_upgrade/upgrader/workflows_test.go
This PR updates DaisyWorker to allow workflows to be retried. To achieve this, clients of DaisyWorker supply a closure that *generates* a workflow. On the first invocation, and any retries, this factory is used to create a new workflow. This is required since daisy workflows aren't designed to be run multiple times.
This PR is the first half of removing the fallback-to-PD-standard feature from daisy. The second PR adds a hook that implements the fallback-to-PD-standard behavior.
Testing
* Ran a subset of the OVF and image import e2e tests locally.
=> CLI Tools: Allow workflows to be re-run

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
The `Import with subnet but without network` tests are currently failing with the error:
>  Image 'e2e-test-image-import-subnet-xjryl' doesn't exist after import: googleapi: Error 404: The resource 'projects/compute-image-test-pool-001/global/images/e2e-test-image-import-subnet-xjryl' was not found, notFound
This is occurring since the e2e tests confirm that the imported image is present. In #1781 I changed the project where this tests runs, but did not update the project that is used to assert the image exists.
https://oss-prow.knative.dev/view/gs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1460137697052987392
=> Import e2e tests: Look for image in project where import occurred

cli_tools/common/utils/daisyutils/workflow_hook_fallback_pd.go, cli_tools/common/utils/daisyutils/workflow_hook_fallback_pd_test.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_import_e2e_common.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
This fixes the failure that we're seeing in the "Allow import to work when SSD quota is exhausted" e2e test.
https://oss-prow.knative.dev/view/gs/compute-image-tools-test/logs/ci-ovf-import-e2e-tests-daily/1460869781400850432
Two changes:
1. Implement pd-standard fallback for attached disks
2. Decouple disk import from final instance creation
The test is failing with an error "Intermediate image ovf-w1207zz123-1 already exists. Re-run import." This happened since the SSD quota was insufficient to create the imported instance; prior to this PR, OVF import would re-run *everything*, and find that the disks had already been imported to images.
This PR splits OVF import into two phases:
1. Import disks to images.
2. Create an instance from the images.
While working on this, I noticed an …
=> OVF import: Fix PD-fallback

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_workflows/image_import/suse/suse_import/translate.py
This adds support for importing SLES 15SP3 -- the existing import logic worked, so it was just a config update to allow 15SP3. 
- Added e2e test for 15SP3.
=> Import: Add suport for SLES 15SP3

cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
Using `us-central2-a` in a magical way caused us confusion when debugging a failing test.
=> OVF Import Tests: Explain why us-central2-a is used for PD fallback tests

docs/daisy-installation-usage.md
Updating the URL of the daisy in "daisy-installation-usage" document.
=> daisy: modify daisy URL in daisy installation usage doc

gce_onestep_image_import.Dockerfile
onestep-import docker image should have the same config as the regular import docker image. gcsfuse and qemu is required for inspection.
=> [onestep-import] install gcsfuse and qemu for onestep-import

cli_tools/common/image/importer/daisy_inflater_test.go, cli_tools/common/image/importer/inflater.go, cli_tools/common/image/importer/inflater_test.go
Enable the API as main inflater.
=> [safely Enable VMDK API] stage 2: enable API inflater

gce_image_import_export_tests.Dockerfile, test-infra/prowjobs/wrapper/withgcloud.Dockerfile
For those e2e test which directly running local binary, we need gcsfuse/qemu-img on local as well to enable file inspection.
=> [e2e test] add qemu/gcsfuse for test docker images

cli_tools/common/image/importer/process_planner.go, cli_tools/common/image/importer/process_planner_test.go
Additionally fix staticcheck errors in modified files.
=> Image Import: Warn when UEFI boot is specified but not detected.

cli_tools/common/disk/inspect.go, cli_tools/common/disk/inspect_test.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
follow staticcheck-S1012-and-ST1005 checks by modifying capitalized strings and replacing time-now-sub by time since
=> follow staticcheck-S1012-and-ST1005 checks

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_workflows/image_import/windows/translate_bootstrap.ps1
We had  a report of Windows Server 2016 failing to import when the original instance was exported from Azure. The translation instance (which runs the user's VM) rebooted every five minutes.
This occurred since [Azure uses COM1 for their EMS server](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-windows). Daisy (and these translation scripts) use COM1. My theory is that the first pipe fails [here](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/c66dc9accdb83fc50fe0e825b861321a937f01a7/daisy_workflows/image_import/windows/run_startup_scripts.cmd#L55), and causes the script to die. This is consistent with the reboots that we see every five minutes; those reboots are scheduled by run_startup_script.cmd, and intended to be cleared by …
=> Windows import: Don't fail when EMS is on COM1

cli_tools/common/utils/validation/validation_utils.go, cli_tools/common/utils/validation/validation_utils_test.go, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_export/exporter/exporter_test.go, daisy_workflows/export/disk_export.wf.json
Image export for non-raw files: fix the issue of temporary buffer disk failing to resize occasionally with a resize2fs error by creating buffer disk of the same size as the image raw size.
Additionally:
* Added disk snapshot name validation
* Fixed raw disk export instance having OS disk match the size of the exported image as this is unnecessary
TODOs:
* Have buffer disk match image size for VMDK/VHD export when image path is provided (instead of a name as for this PR)
* Ensure disk snapshot export works
=> Fix image export failing occasionally for large images by allocating buffer disk size to match raw image size

cli_tools/common/utils/validation/validation_utils.go, cli_tools/common/utils/validation/validation_utils_test.go, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_export/exporter/exporter_test.go
This is a continuation of work from https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1821 to prevent large image exports from failing due to buffer disk resize errors. This PR adds the functionality added in 1821 but for images that are specificied as URIs.
=> Validating image URI on image export and setting temporary disk to match the image size.

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
This fixes the `windows-10-x86-byol` test on testgrid, which is failing since the OS Config agent cannot be found:
```
2022/01/25 18:59:27 windows-startup-script-url: Exception caught in script:
2022/01/25 18:59:27 windows-startup-script-url: At C:\WINDOWS\TEMP\metadata-scripts463353643\windows-startup-script-url.ps1:85 char:5
2022/01/25 18:59:27 windows-startup-script-url: +     Get-Service google_osconfig_agent
2022/01/25 18:59:27 windows-startup-script-url: +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022/01/25 18:59:27 windows-startup-script-url: Test Failed: Cannot find any service with service name 'google_osconfig_agent'.
2022/01/25 18:59:27 windows-startup-script-url: 
2022/01/25 18:59:27 windows-startup-script-url: 
```
VMM doesn't support OS config agent on non-server Windows: …
=> Import e2e: OS config is not supported for Windows 10

cli_tools/go.mod, cli_tools_tests/go.mod, common/go.mod
Each 'replace' needs a corresponding 'require latest'. Without that, even though it works for our repositories, it blocked others to pull the module. It will fail with "unknown revision v0.0.0".
v0.0.0 is a pseudo version number and can't work when the module consumer doesn't have the same "replace".
=> Fix go.mod: each 'replace' needs a corresponding 'require latest'

cli_tools_tests/e2e/gce_ovf_import/scripts/ovf_import_test_3_disks.sh, daisy_integration_tests/scripts/post_translate_test.sh
This PR improves the reliability of the post-translate tests that we use in Linux; I found the flakiness while adding the OS config agent to SLES.
Two improvements:
1. Allow retry for all distros when installing a test package. We already do this for Ubuntu, so this adds support for EL and Suse. Retry avoids a false positive when the system is performing a package update during startup, which causes the package manager to lock transactions.
2. Avoid false positive for unlocked users if the user is added by the guest agent. The guest agent adds users with project- or instance-configured SSH keys. `passwd` thinks the user has an unlocked password, since the agent creates the user with a password hash of `*`. This page talks about the idiom of using an asterisk password to disable password …
=> Linux import: Improve reliability of e2e tests

daisy_workflows/image_build/debian/build_fai.py
it seems we lose permissions through the daisy transfer operation. for now, fix them explicitly.
=> chmod +x fai scripts

cli_tools_tests/go.sum
e2e test build is failing right now due to the out-of-date dependency.
=> [gce_image_import_export] fix e2e test build

daisy_workflows/image_import/windows/translate.ps1
We observed a Windows 10 64-bit import that failed when running `Configure-Power`. This PR skips `Configure-Power` for all versions of Windows 10 until we find a more granular filter.
=> Windows 10 import: Skip Config-Power

daisy_workflows/build-publish/rhui/cds_artifacts/rhui-tools.conf
checked by gunicorn-auth service; missing section crashes the service
=> cds build: include security section

daisy_workflows/image_import/windows/run_startup_scripts.cmd, daisy_workflows/image_import/windows/run_startup_scripts_x86.cmd
The time to complete the run_startup_scripts can very from image to image, and can be greater than 5 minutes. Therefore the timeout value has been made adaptive to be incremented with every reboot.
=> Image Import: use adaptive timeout in run_startup_scripts.

cli_tools/common/mount/inspector.go, cli_tools/common/mount/inspector_test.go
In https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1743 we improved mount detection for the precheck tool; when doing so, we used the wrong CLI binary -- it should have been `findmnt`.
Found by @yswe, thanks!
=> Fix getDeviceForMount call

daisy_workflows/build-publish/rhui/cds.wf.json, daisy_workflows/build-publish/rhui/cds_artifacts/rhui-health-check.service, daisy_workflows/build-publish/rhui/cds_artifacts/rhui-health-check.timer, daisy_workflows/build-publish/rhui/health_check.py, daisy_workflows/build-publish/rhui/install_cds.sh, daisy_workflows/build-publish/rhui/install_rhua.sh, daisy_workflows/build-publish/rhui/rhua.wf.json, daisy_workflows/build-publish/rhui/rhua_artifacts/rhui-health-check.service, daisy_workflows/build-publish/rhui/rhua_artifacts/rhui-health-check.timer
A first pass at health checks for RHUI; for now, it includes a single check. The goal is to validate the overall approach prior to adding more checks.
To facilitate deployment, the script currently exposes the following flags:
```
`health_check.py \`
--node {cds,rhua}  \
--result_file RESULT_FILE \
--nfs_mount NFS_MOUNT_POINT
```
Key points:
- The health checker runs on a timer, and writes the result (`{OK|ERROR}`) to a sentinel file that's read by nginx's health check handler
- Logs are written to stdout, allowing them to be queried with `journalctl`
=> RHUI: Runner for health checks

daisy_workflows/build-publish/rhui/cds.wf.json, daisy_workflows/build-publish/rhui/cds_artifacts/rhui-health-check.service, daisy_workflows/build-publish/rhui/health_check.nginx.conf, daisy_workflows/build-publish/rhui/install_cds.sh, daisy_workflows/build-publish/rhui/install_rhua.sh, daisy_workflows/build-publish/rhui/rhua.wf.json, daisy_workflows/build-publish/rhui/rhua_artifacts/rhua.patch, daisy_workflows/build-publish/rhui/rhua_artifacts/rhui-health-check.service
- Health checks run on `8080`; RHUA listens on `80`, so I didn't want to interfere with anything that depends on that.
- nginx on the CDS node already includes `/etc/nginx/conf.d` drop-ins. RHUA required patching.
- I moved the results file from the health check to nginx's default HTML directory
=> nginx for rhua health checks

cli_tools/import_precheck/README.md, cli_tools_cloudbuild.yaml
Import_Precheck tool: Update_cloudbuild_pipeline_to_Add_binaries_for_32-bit Operating Systems
/cc EricEdens
/cc yswe
/assign EricEdens
/assign yswe
=> Import_Precheck: Update_cloudbuild_pipeline_to_Add_binaries_for_32-bit Operating Systems

OWNERS, daisy_workflows/build-publish/rhui/health_check.py
* add cds and rhua service checks
* move nfs mount path to constant
* always log to stdout (systemd will get it to syslog for us)
* always run read & write checks on all node types (mount options aren't different across types)
* simplify nfs mount type check for readability
the final commit refactors the plugin architecture to use classes, but this is just an idea i had. feel free to review excluding that commit. output format is maintained (added fake service name to the check in this example to force a failure):
```
MountIsNFS - INFO - checking that /var/lib/rhui/remote_share is mounted as NFS
MountIsNFS - INFO - success
MountIsWritable - INFO - checking that /var/lib/rhui/remote_share is writable
MountIsWritable - INFO - success
MountIsReadable - INFO - checking that …
```
=> Update RHUI health checks

README.md, cli_tools_tests/e2e/README.md, daisy_workflows/README.md, daisy_workflows/import_userguide.md
Updates docs to reflect the tools that didn't move to https://github.com/GoogleCloudPlatform/compute-image-import.
=> Refresh docs to reflect current tools

daisy_workflows/build-publish/test-workflow.json
Created a new generic testing image exclusively to test image publish workflows. This image should always be deleted after 12 hours. In the prod environment, where testing with this workflow is intended to be used, the image will be published to `bct-prod-images`.
=> Test image daisy workflow

daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9-ha.repo, daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9-ha.spec, daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9.repo
Making the el9 RHUI config multi-arch has one issue, which is that the HA repos are x86-only. After consulting with RH, we decided to split the HA repos out to their own package, and install it only on x86 images at image build time.
=> split ha repos from el9 rhui config

daisy_workflows/build-publish/rhui/cds.wf.json, daisy_workflows/build-publish/rhui/cds_artifacts/config.opsagent.yaml, daisy_workflows/build-publish/rhui/health_check.nginx.conf, daisy_workflows/build-publish/rhui/install_cds.sh, daisy_workflows/build-publish/rhui/install_rhua.sh, daisy_workflows/build-publish/rhui/rhua.wf.json, daisy_workflows/build-publish/rhui/rhua_artifacts/config.opsagent.yaml, daisy_workflows/build-publish/rhui/status.nginx.conf
This updates the RHUA and CDS images to include Cloud Ops configurations to collect the following logs:
1. nginx logs (CDS and RHUA)
2. rhui-manager logs (RHUA)
3. rhui-sync logs (RHUA)
For (2) and (3), it adds a processor that splits the log into structured fields.
- Ran the configs on the CDS and RHUA nodes, and confirmed that the logs and metrics were sent to Cloud Ops. 
- Looked at the merge config from `journalctl`, and verified that the syslogs were still being collected (and verified in the Cloud Ops UI):
```
2022/06/10 17:43:12 Merged config:
logging:
receivers:
nginx_access:
type: nginx_access
nginx_error:
type: nginx_error
rhui_manager:
type: files
include_paths:
- /root/.rhui/rhui.log*
rhui_sync:
type: files
include_paths:
- /var/log/rhui-subscription-sync.log
syslog:
type: …
```
=> CDS: Collect nginx metrics and logs

daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp.cfg
This prevents dnf from asking you if you want to import the key when pulling a package the first time.
=> Also import the Cloud SIG GPG key.

cli_tools/gce_image_publish/publish/publish_test.go
This test only passes on GCE VMs coincidentally; update it to work with local invocation.
Before this PR:
```
+>>> go test -v -run TestCreatePublishWithTemplate
=== RUN   TestCreatePublishWithTemplate
=== RUN   TestCreatePublishWithTemplate/pass_template
publish_test.go:797: CreatePublishWithTemplate() called with template {}: got error {}
WorkProject unspecified
=== RUN   TestCreatePublishWithTemplate/pass_with_invalid_template
--- FAIL: TestCreatePublishWithTemplate (0.06s)
--- FAIL: TestCreatePublishWithTemplate/pass_template (0.06s)
--- PASS: TestCreatePublishWithTemplate/pass_with_invalid_template (0.00s)
FAIL
exit status 1
FAIL	github.com/GoogleCloudPlatform/compute-image-tools/cli_tools/gce_image_publish/publish	0.202s
```
After this PR:
```
+>>> go test -v -run …
```
=> gce_image_publish test fix

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json
Fixes a reference to an older image name used in testing that was changed later. This will resolve an error being seen in the publish stage where the image name differs from what is expected.
=> Update image name in Windows 10 21h2 publish file

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json
Staging uses a different set of licenses than in other environments. This updates the licenses on Windows Enterprise publish workflows in Daisy to reflect this difference.
=> Update licenses attached to staging images (Windows Enterprise)

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json
Reworks the logic in the publish workflow to add the testing environment, allowing for publishing to bct-prod, which was missing in the original push adding the workflows. This is needed for integration tests; also matches the logic of other publish files. Also updates image families to match those of previous iterations for consistency.
=> Update windows client publish workflows

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json
Fixes missing "- else" from client publish files that would result in unexpected EOF issues in publish process.
=> Update windows client publish file environment logic

daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json
This will make the naming less confusing for future iterations of Win11.
=> Update image family for Windows 11 21h2

daisy_workflows/build-publish/partner/freebsd_11.publish.json, daisy_workflows/build-publish/partner/freebsd_12.publish.json, daisy_workflows/build-publish/partner/freebsd_13.publish.json, daisy_workflows/build-publish/partner/opensuse_leap_15.publish.json, daisy_workflows/build-publish/partner/opensuse_leap_15_arm64.publish.json
it was my fault for assuming these were already in working order. `gce_image_publish` is strict about json, so final elements must not end in a comma.
=> fix more typos in partner workflows

daisy_workflows/build-publish/sqlserver/sql-2022-preview-windows-2022-dc.wf.json
Microsoft is moving away from a universal installer, so each version going forward may have their own SSMS installer version. We're going to have to start naming these to account for pulling/using the correct secrets in Concourse.
This change is a precondition for upcoming changes to the Concourse pipeline; nonbreaking as this currently is not used.
=> Renaming SSMS variable in SQL 22 publish file

daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json
We're reaching timeouts due to long running Windows Updates. Pushing timeout back 1hr (to 5hr total) to account.
=> Update timeouts on Server 2016 builds

daisy_workflows/build-publish/rhui/install_cds.sh, daisy_workflows/build-publish/rhui/install_rhua.sh
The original design for RHUI node image builds was to install content from repo, but patch it before use. This has become unmaintainable because the content of the Ansible playbooks changes frequently. As a temporary measure, pin the version to the version corresponding to the patch file.
=> pin rhui package versions

daisy_workflows/build-publish/rhui/cds_artifacts/answers.yaml
We are pinning both rhui-installer and rhui-tools in #2009; but we must also pin these CDS packages because they are not version locked or depended on, and newer versions expect the content from the newer rhui-installer and rhui-tools packages.
=> RHUI: also pin CDS packages

daisy_workflows/image_build/windows/post_install.ps1
This update has appeared in the past and hangs up the build on an update loop. Updated Install-WindowsUpdates to skip it.
=> Update post_install.ps1 to skip KB5007651

prowjobs_cloudbuild.yaml
global volume is not allowed when count of steps < 2
=> test image build: move global volumes to local

daisy_workflows/image_build/windows/post_install.ps1
Server 2012R2 doesn't have CurrentMajorVersionNumber or CurrentMinorVersionNumber so this breaks the build for 2012R2. The known issue KB doesn't target this version of Windows Server, so it is safe to skip in this manner.
=> Add logic to skip Server 2012R2 in W10/11 KB check

daisy_workflows/build-publish/sqlserver/sql-2012-enterprise-windows-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2012-standard-windows-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2012-web-windows-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2016-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2014-standard-windows-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2014-web-windows-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2016-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2019-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2016-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2019-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2016-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2019-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2016-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2019-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2004-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-uefi.publish.json
Reflecting changes to the pipeline where staging environment is no longer used. client builds are handled in a different PR adding some functionality, so they were left out here.
=> Remove staging environment from publish files

daisy_workflows/build-publish/rhui/cds.publish.json, daisy_workflows/build-publish/rhui/rhua.publish.json
Restore prefix fields. Had set prefix to differ to avoid any race conditions with publishing, but realized this parameter serves a double purpose in specifying the GCS path.
=> correct RHUI publish prefix

daisy_workflows/image_build/sqlserver/configs/sql_server_2022.ini
SNAC_SDK became an invalid feature option in the latest RC, blocking install. Removing it to allow installs to continue.
=> Update sql2022 install parameters

daisy_workflows/kernel_commit_query/debian.sh, daisy_workflows/kernel_commit_query/kcq.py, daisy_workflows/kernel_commit_query/kernel_commit_query.wf.json, daisy_workflows/kernel_commit_query/rhel.sh, daisy_workflows/kernel_commit_query/rocky.sh, daisy_workflows/kernel_commit_query/suse.sh, daisy_workflows/kernel_commit_query/ubuntu.sh, daisy_workflows/linux_common/utils/common.py
This workflow intends to inspect a Linux system to determine if its
kernel contains required patch(es) implementing a given feature.
The initial version implements a "apply & check" strategy where it
will reconstruct the changes chain between two kernel versions and
check if the expected patches are present in the chain.
+ Removed `pip_packages` workflow argument;
+ Small code consistency adjustment;
+ Fixed `flake8` tests reported issues;
+ Simplified the environment configuration steps by:
+ moving it all out of the main program
+ having a shell script for each of "os type"
+ no need of packages and package manager instruction as pass-ins
=> Kernel Commit Queries

daisy_workflows/image_build/sqlserver/sql-2022-enterprise-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-enterprise-windows-2019.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-enterprise-windows-2022-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-enterprise-windows-2022.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-standard-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-standard-windows-2019.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-standard-windows-2022-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-standard-windows-2022.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-web-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-web-windows-2019.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-web-windows-2022-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-web-windows-2022.wf.json
Including 2022 and 2019 Windows Server builds. Evaluating 2016 in future PR. Leverages existing workflows used for preview builds, adjusted for actual release candidate versions.
=> Add daisy workflows for SQL Server 2022 release versions

daisy_workflows/export/disk_export.wf.json
in disk enumeration in Debian 11.
=> Revert the debian worker image for disk_export due to a potential race

daisy_workflows/build-publish/debian/debian_10.wf.json, daisy_workflows/build-publish/enterprise_linux/centos_7.wf.json
To enable SBOM generation for debian 10 and ensure debian workflow consistency with other workflows such as Enterprise Linux, debian 10 build-publish will use the disk export subworkflow.
It would be useful to have confirmation from someone more familiar with these workflows that replacing "CopyGCSObjects" with "disk_export.wf.json" maintains the same export behavior.
=> Use disk export subworkflow in Debian 10

daisy_workflows/export_metadata/export-metadata.ps1
Turns out that for some cases where the change log contains the keywords we'll end up parsing the wrong lines and using wong strings.
=> export-metadata: regex and case sensitive match Version Source

daisy_workflows/kernel_commit_query/kcq.py
Don't use the upstream exported patches for checking distribution's changelog and rely only on the git log's data.
=> kcq: don't export upstream kernel patches for Changelog analysis

daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json, daisy_workflows/build-publish/enterprise_linux/centos_stream_8.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_7.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.wf.json
SBOM generation support for a few more distros: may add more in this pull request if there are no additional confirmed bugs such as the bug relating to mounting with EL9 distros.
=> sbom generation for a few more Enterprise Linux workflows

daisy_workflows/build-publish/debian/debian_11.wf.json, daisy_workflows/build-publish/debian/debian_11_arm64.wf.json
Use disk export in debian 11, and add SBOM generation support. 
Identical changes to #2046 but for the other build-publish debian workflows.
=> SBOM and disk export changes to debian 11

daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-11-21h2-ent-x64-uefi.wf.json
Timeouts have been occurring during the sysprep phase; bumping 1h to give it time.
=> Update timeout threshold for Win11 builds

daisy_workflows/build-publish/rhui/install_cds.sh, daisy_workflows/build-publish/rhui/install_rhua.sh
* The entitlement cert and enrollment cert are actually the same; so simplify to use one value. 
* Don't unregister at the end, merely disable repos. This enables automated cert refresh for the entitlement cert within the RHUA software.
=> RHUA use single enrollment cert

daisy_workflows/kernel_commit_query/debian.sh
Given the wrapping around cloud build init_script environment the kcq.py script is not found in the same pwd.
=> Kernel Commit Query: fix kcq.py invocation from debian wrapper

daisy_workflows/kernel_commit_query/kernel_commit_query.wf.json
Due to network connectivity we may take longer than 30m so extending it for now while we work on optimizations.
=> Kernel Commit Query: extend time out to 40m

daisy_workflows/image_build/windows/windows_install_media/components/2016_64Bit/upgrade.ps1, daisy_workflows/image_build/windows/windows_install_media/components/2019_64Bit/upgrade.ps1
A few of the 2022 differences were missed in the previous PR. I have successfully upgraded a 2012r2 instance to 2019 using the fixed version of this script.
=> 2016/2019 Upgrade script fixes.

daisy_workflows/build-publish/windows/windows-server-2012-r2-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-uefi.wf.json
Timeout at 4h is occurring during final windows updates; increasing to 5h to allow completion.
=> Update timeout for 2012r2 builds to 5h

daisy_workflows/kernel_commit_query/debian.sh, daisy_workflows/kernel_commit_query/kcq.py
Remove the upstream kernel cloning step and instead uses upstream cgit api to query and parse a commit, additionally this change removes the apt-get upgrade step since we are interested on the images content and not transitioned stated between release and now.
=> kernel commit query: changelog check: improve execution time

daisy_workflows/export/disk_export.wf.json
As a follow up to the symlink change, use a debian 11 worker instead of debian 10. 
Even if the disks /dev/sda and /dev/sdb are flipped, the symlinks should export the correct disk.
=> Change worker to debian 11

daisy_workflows/sbom_validation/test_sbom_export.sh
Change sbom validation to search for any file ending with *.sbom.json, rather than a specific file name of "sbom.json."
This is a precursor to another change which exports the sbom file to the final destination, instead of just the outspath.
=> Minor validation change

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-10-20h2-ent-x86-bios.wf.json, daisy_workflows/image_build/windows/windows-10-21h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-11-21h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-81-ent-x64-uefi-byol.wf.json
Reflecting the removal of byol to the names in the previous PR. BYOL is still included in the license string and is intended.
=> Update Windows Client workflow names

daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json, daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/export_disk.sh, daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json
Add input variable for copying the sbom file to the final location, similar to the disk file. 
In the caller workflow, such as almalinux_8.wf.json, the "sbom_destination" variable is explicitly not set by default. This ensures that if an SBOM should not be generated, an empty SBOM file is output but it is not copied anywhere.
=> Sbom export

daisy_workflows/sbom_validation/test_sbom_export.sh
From a previous change, export_disk.sh now creates an empty sbom file all the time. 
For the sbom file to be a success, it should not be empty. The presubmit now checks that the sbom file is not empty for enterprise linux.
=> Presubmit tests that sbom file is not empty

daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json
There was a mistake in passing in an empty variable, so this is to revert that mistake. A future change will hopefully fix this for all the sbom workflows.
=> Temporarily revert empty daisy variable

daisy_workflows/build-publish/debian/debian_10.wf.json, daisy_workflows/build-publish/debian/debian_11.wf.json, daisy_workflows/build-publish/debian/debian_11_arm64.wf.json, daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json, daisy_workflows/build-publish/enterprise_linux/almalinux_9.wf.json, daisy_workflows/build-publish/enterprise_linux/centos_7.wf.json, daisy_workflows/build-publish/enterprise_linux/centos_stream_8.wf.json, daisy_workflows/build-publish/enterprise_linux/centos_stream_9.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_7.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_7_9_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_4_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_6_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_9.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_arm64.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.wf.json
Add the ability to export the SBOM to the final destination, similar to the disk tar gz file. By default this copies the sbom file in place, if no sbom_destination is passed in.
Currently, it is assumed that the name of the sbom file is "export-image.sbom.json" in the disk export workflow. 
Once other builds have been updated, sbom_destination may become a required variable, similar to gcs_url.
=> SBOM export to final destination, copy in place by default

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-uefi.wf.json
This change adds the placeholder variable for sbom final export destination in windows workflows. 
This variable is necessary for specific automated builds to compile in daisy while providing an input for "sbom_destination."
=> Placeholder sbom destination var, unused currently

daisy_workflows/export_metadata/export-metadata.py
To maintain backward compatibility use gpt's label metadata to identify the root fs - in addition to the guuid logic.
=> export metadata: use gpt's label metadata to identify root

daisy_workflows/image_build/windows/windows-11-21h2-ent-x64-uefi.wf.json
Windows 11 requires a minimum 64GB, so increasing to the nearest multiple of 10 rounded up.
=> Increase disk size for W11 build

daisy_workflows/image_build/enterprise_linux/build_installer.py
The distinction between -boot and -dvd1 isos for what concerns /EFI and /images directory is the content ownership, in the -boot some files will be 'nobody' owned, whereas in the dvd1 image all files are 'root' owned, rsync will try to sync the content attributes but fail for 'nobody' since the group and user are not yet available.
This change makes it consistent both -boot and -dvd1 use cases where the resulting/installed content will always be owned by root.
=> el: fix rsync errors with -boot iso variant

daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
With the current configuration debian-11-arm64 will fail to boot with efi loaders created grub with if grub-efi-arm64-signed & shim-signed modules are present.
=> debian-11-arm64: fix boot issue

daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json, daisy_workflows/build-publish/enterprise_linux/almalinux_9.publish.json
AlmaLinux 8:
```
"UEFI_COMPATIBLE", "VIRTIO_SCSI_MULTIQUEUE", "SEV_CAPABLE", "SEV_LIVE_MIGRATABLE", "GVNIC"
```
AlmaLinux 9:
```
"UEFI_COMPATIBLE", "VIRTIO_SCSI_MULTIQUEUE", "SEV_CAPABLE", "SEV_SNP_CAPABLE", "SEV_LIVE_MIGRATABLE", "GVNIC"
```
=> Update AlmaLinux guest_features to match RHEL

daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json, daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/export_disk.sh, daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json
Add the daisy config variables so sbom-util can be used to generate the sbom, instead of a fixed gcs location where syft is stored.
=> Add skeleton for sbom-util SBOM generation path

daisy_workflows/export/export_disk.sh
Currently concourse is writing an empty sbom file to the output bucket, investigate whether the reason is the "./" in front of the output file path.
=> Fix empty sbom bug

daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/export_disk.sh
Using syft_source for sbom generation is now deprecated, remove it from the disk export script.
=> Remove syft sbom generation mode, deprecated

daisy_workflows/image_build/debian/build_fai.py, daisy_workflows/image_build/debian/fai_config/files/etc/hostname/BOOKWORM, daisy_workflows/image_build/debian/fai_config/files/etc/netplan/90-default.yaml/BOOKWORM, daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC, daisy_workflows/image_build/debian/fai_config/scripts/BOOKWORM/10-clean, daisy_workflows/image_build/debian/fai_config/scripts/GCE_CLEAN/10-gce-clean
- Use the now upstream changes for hostname configuration.
- We still use our own clean file because we aren't using the other parts of the upstream one. Rectify our clean script with upstream.
- Replace the default netplan config so that we can use DNS search domains from DHCP (revert when https://salsa.debian.org/cloud-team/debian-cloud-images/-/merge_requests/357 is merged).
=> Debian build fixes for Bookworm

daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
Until we can change the agent's mutil-nic behavior we need to include dhclient.
=> Include dhclient in the Debian builds.

daisy_workflows/image_build/windows/bootstrap_install.ps1
gsutil ls adds a slash at the end of the path, so when copying sbomutil, do not add an extra slash twice.
=> Remove backslash on windows path

daisy_workflows/image_build/windows/bootstrap_install.ps1
ResumableUploadAbortException 403 error seems to happen only when using gsutil -m cp.
=> remove multithreading for single file upload on gsutil

daisy_workflows/build-publish/windows/windows_export.wf.json, daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/export_disk.sh
Windows workflows generate the sbom in the powershell script, before disk export. Without this change, disk export overrides the sbom file with an empty file.
=> Do not replace windows sbom with empty sbom

daisy_workflows/image_build/windows/post_install.ps1
Works around an issue introduced in June's updates that prevent the installation of .Net Framework 3.5 or 2.0 after running security patches.
=> Add workaround to .Net install issue June 2023

daisy_workflows/build-publish/windows/windows_export.wf.json, daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/export_disk.sh
Reverts GoogleCloudPlatform/compute-image-tools#2176
There is a name conflict between the windows and linux default sbom names. A future change will be made to avoid this conflict.
=> Revert "Do not replace windows sbom with empty sbom"

daisy_workflows/image_build/windows/bootstrap_install.ps1
Before this change, the driver directory was incorrectly referenced, leading to a scan of the entire \ directory.
=> Correctly reference driver directory

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows_export.wf.json, daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/export_disk.sh
The disk export workflow replaces sbom files with an empty file. However, windows workflows generate an sbom before this. To prevent the windows sbom file from being empty, this change is necessary.
=> Do not overwrite windows sboms at the end

daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-uefi.wf.json
Ensure that the windows sbom name is passed in, because it is different from the linux sbom name used in disk_export.wf.json.
=> Pass in existing file name for robust sbom naming

daisy_workflows/image_build/windows/bootstrap_install.ps1
This change allows us to have one directory for all sbom files, which can be passed in as extra_content to sbomutil.
=> Move windows iso and other files to sbom folder

daisy_workflows/image_build/sqlserver/sql_install.ps1
Keep the sbom folder names the same for windows and sql images, so documentation is not confusing.
=> Rename sbomcontents to sbomcomponents for consistency with windows

daisy_workflows/export/image_export.wf.json
Allow quick sbom generation for the image export workflow, which can be followed up by a common documentation update for both disk_export and image_export workflows.
=> Allow image export to generate sboms

daisy_workflows/image_build/windows/bootstrap_install.ps1
If sbomutil.exe is added to the components directory, it is added to the sbom file by default.
We do not want this, so download sbomutil.exe to C:\ instead
=> Do not add sbomutil.exe to the sbom

daisy_workflows/image_build/windows/bootstrap_install.ps1, daisy_workflows/image_build/windows/components/SetupComplete.cmd, daisy_workflows/image_build/windows/post_install.ps1
After SBOM generatino was added, bootstrap files such as the Cloud SDK installer are stored in sbomcomponents instead of builder. This updates the cmd file to reflect this.
=> Change builder folder name to sbomcomponents

daisy_workflows/sbom_validation/windows_sbom_validation.wf.json
When running the presubmit, we do not want to have to pass in a workflow_root, and instead want the default workflow_root to work.
This sets the default value correctly.
=> Set default windows workflow root for presubmits

daisy_workflows/image_build/windows/post_install.ps1, daisy_workflows/image_build/windows/windows-build-bios.wf.json, daisy_workflows/image_build/windows/windows-build-uefi.wf.json
BGinfo hasn't been run in some time; cleaning up code involved with it that is no longer used.
=> Remove bginfo from Windows builds

daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
This can be removed if Debian decides to upstream our changes.
=> Enable secure boot on debian-12 arm for GCE builds

daisy_workflows/image_build/install_package/installpackage.py
That way we don't deal with dependencies for build testing derived images.
=> package install: use dpkg for debian rather than apt-get

daisy_workflows/image_build/windows/windows-build-bios.wf.json, daisy_workflows/image_build/windows/windows-build-uefi.wf.json
This is so on the first boot in the build process the installation disk has the correct set of Guest OS Features.
=> Adding the appropriate GuestOsFeatures for Windows builds

daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.publish.json, daisy_workflows/image_build/enterprise_linux/rhel_8.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_8_byos.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_9.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_9_byos.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_8.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_9.wf.json
Ping me on corp if you need context. I updated the image-build stuff too because CIT is starting to rely on guest os feature tags more so it would be good to keep things in sync everywhere.
rhel 8 and 9 byos did not previous have the v1 tags but it's still rhel and they have the backports so I added it, if there's something I'm missing LMK.
/cc @zmarano @elicriffield
=> Tag images that contain kernel commit 43955a1a2 with SEV_LIVE_MIGRATABLE_V2

daisy_workflows/build-publish/enterprise_linux/centos_7_predictable_nic.publish.json, daisy_workflows/build-publish/enterprise_linux/centos_7_predictable_nic.wf.json
Publish template is still missing so it can't successfully push to ARLE, forgot I need this workflow.
=> Add image publish workflow for centos-7-predictable-nic

daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_arm64.cfg
/cc @elicriffield @zmarano 
/hold
This would make gcloud work for now by installing a version of python3 that works and allow us to release rocky 8 arm this month.
The downside of removing the python38 mark is that gcloud will break when the user does `dnf upgrade`, but even the current image `rocky-linux-8-optimized-gcp-arm64-v20231010` has this problem. The upside is that we don't leave python38 installed permanently for a temporary workaround.
=> Install python38 on rocky 8 optimized gcp arm64

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json
Times out during sysprep. +1h gives headroom.
=> Update timeout for W10 21H2

daisy_workflows/image_build/windows/post_install.ps1
Likely a temporary exception to allow the build to complete.
Looking at Windows Update logs for a failed test VM it appears the KB is never actually attempted by the Windows Update service, yet the build log shows it repeatedly trying and Succeeding with Errors.
=> Exclude KB5034439 from Server 2022 builds

daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.publish.json
/cc @zmarano @elicriffield 
```
[acrate_google_com@rocky8optimized ~]$ uname -r && sudo dnf install -y kernel-devel >/dev/null && casr/src/kernels/$(uname -r )/arch/x86/include/asm/mem_encrypt.h | grep 'early_set_mem_enc_dec_hypercall(unsigned long vaddr, unsigned long size, bool enc) {}' && echo "Kernel contains ac3f9c9f1b37edaa7d1a9b908bc79d843955a1a2"
4.18.0-513.9.1.el8_9.cloud.0.1.x86_64
early_set_mem_enc_dec_hypercall(unsigned long vaddr, unsigned long size, bool enc) {}
Kernel contains ac3f9c9f1b37edaa7d1a9b908bc79d843955a1a2
[acrate_google_com@rocky8optimized ~]$
```
```
[acrate_google_com@rocky9optimized ~]$ uname -r && sudo dnf install -y kernel-devel >/dev/null && cat /usr/src/kernels/$(uname -r )/arch/x86/include/asm/mem_encrypt.h | grep …
```
=> Tag rocky 8/9 optimized with SEV_LIVE_MIGRATABLE_V2

daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_arm64.cfg
This reverts commit 08601f6f19d8afd701fbec68c9ca5dcdc8472e08.
gcloud preamble changes are rolled out, I built an image from this and it passes CIT
/cc @zmarano @elicriffield
=> Revert "Install python38 on rocky 8 optimized gcp arm64 (#2258)"

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-10-21h2-ent-x64-uefi.wf.json
Missed a timeout reference in the last PR. Updating the other build file to match the new timeout.
=> Update W10 21H2 build timeout

daisy_workflows/image_build/windows/windows-server-2025-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2025-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2025-dc-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2025-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2025-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2025-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2025-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2025-uefi-payg.wf.json
- Adding Server 2025 image build workflows
- Server 2022 payg licenses are being used so instance are charged/licensed for usage.
=> Windows Server 2025 image build workflows

daisy_workflows/image_build/windows/post_install.ps1
Removing netsh helpers from Windows 11 installations
=> Removing netsh helpers from Windows 11 installations

daisy_workflows/image_build/windows/bootstrap_install.ps1
- Bump retry count to 3
- Throw terminating error if max retries exceeded
- Fix name reference to failed update
=> Update bootstrap slipstreaming logic to throw error after max_retries

daisy_workflows/image_build/windows/windows-build-uefi.wf.json
Updating windows builds to run on n2 for Windows 11 CPU support
=> Updating windows builds to run on n2 for Windows 11 CPU support

daisy_workflows/image_build/install_package/cos/package_replacement/dev_cloudbuild.yaml
By adding a command line arg for '_DEST_PROJECT', we can specify which project the preloaded image should be uploaded to. Previously, it would just use the default project in the gcloud config of whatever/whomever was invoking the dev_cloudbuild.yaml script.
Ideally, this will allow us to upload the preloaded image to the gcp-guest project, like the other preloaded images for other distros during the guest-package-build concourse pipeline.
=> Allow the preloading script to create a preloaded COS image in different projects

daisy_workflows/image_build/enterprise_linux/build_installer.py
New RHEL 9.4 ISO is to big to fit, had to make the partitions larger
=> New RHEL 9.4 ISO is to big to fit, had to make the partitions larger

daisy_workflows/image_build/install_package/cos/install_package_cos.wf.json, daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh, daisy_workflows/image_build/install_package/cos/package_replacement/dev_cloudbuild.yaml, daisy_workflows/image_build/install_package/cos/replacepackage.sh
In the concourse pipeline, the guest agent repo is checked out using the most recent commit. Then once the tests have passed on that commit, a tag is created. So at the time of preloading a COS image for testing, a tag won't exist. The preloading script should then take the commit sha as input.
Additionally, the homedir patch that is currently present in the COS code base for the guest agent package is no longer needed for updating to newer versions of guest agent since it was upstreamed, so that patch can be skipped.
CCing @dorileo, @a-crate, @zmarano.
=> Make the preloading script take a commit sha as input for the guest-agent repo (rather than a tag)

daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_4_sap.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_arm64.cfg
Since RHEL 9.4 (and possibly 9.3), installation fails at package selection due to the redhat-insights packages depending on subscription-manager. This only affects on demand as BYOS images have subscription-manager included.
=> Fix RHEL 9.4 installation errors due to redhat-insights client.

daisy_workflows/image_build/install_package/cos/replacepackage.sh
In order to avoid gcloud builds submit errors in the concourse guest package build workflow, specify the source after gcloud builds submit,
CCing @dorileo, @a-crate , @zmarano.
=> Specify source after 'gcloud builds submit'

daisy_workflows/image_build/install_package/cos/package_replacement/preload.sh
Currently, tests on COS fail because they time out. This is due to the 'finished-test' keyword not being logged correctly. This change enables logging such that the preloaded image will write to logs.
CC @a-crate, @dorileo, @zmarano
=> Enable logging so 'finished-test' can be written

daisy_workflows/image_build/install_package/cos/install_package_cos.wf.json, daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh, daisy_workflows/image_build/install_package/cos/package_replacement/dev_cloudbuild.yaml, daisy_workflows/image_build/install_package/cos/package_replacement/disable_auto_updates.sh, daisy_workflows/image_build/install_package/cos/package_replacement/disable_readonly_rootfs.sh, daisy_workflows/image_build/install_package/cos/replacepackage.sh
In order to add support for further milestones, we:
1) Take the patches from master and apply those (since these are the most recent patches).
2) Step 1 (above) then removes the requirement of specifying the overlays branch name, so that is removed from all occurrences.
In order to add support for arm images we:
1) make machine type configurable (t2a for arm images)
2) change zone to accommodate ARM (central)
3) replace COS customizer's disable auto update step with our own script (since the default step is not compatible with ARM images) 
4) rewrite the disabling read only root fs script (to not hang after the reboot).
CCing @a-crate, @dorileo, @zmarano.
=> Add support for other COS milestones (+109, +105) and also ARM images

daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json
EL 7 and Debian 10 are EOL next week, use a newer disk image for the presubmit
=> Use new images after EOL

daisy_workflows/image_build/install_package/cos/install_package_cos.wf.json, daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh, daisy_workflows/image_build/install_package/cos/package_replacement/dev_cloudbuild.yaml, daisy_workflows/image_build/install_package/cos/package_replacement/preload.sh, daisy_workflows/image_build/install_package/cos/replacepackage.sh, daisy_workflows/image_build/install_package/install_package.wf.json
This PR adds ARM support for COS preloading:
- Adds worker_machine and machine_type as args to the install_package_cos.wf.json: allows us to specify ARM specific machine types i.e. debian-11-worker-arm64, t2a-standard-1
- Moves compiling the debian package (compile_debian_package.sh) out of the cloudbuild and in the worker machine. This is because for ARM image, debian packaging should be compiled in an ARM env and cloudbuild does not support ARM.
- Delete's instance_config file in worker machine to pass all debian tests.
CCing @a-crate, @dorileo, and @zmarano.
=> Add ARM support for COS preloading

daisy_workflows/export/disk_export.wf.json
To generate the sha sum, we need to copy the tar gz file.
The windows images are 10 GB, SQL server images are 14 GB. Default disk size is 10 GB it seems, so 20 GB is a safe size.
=> Use 20 GB so windows image copy has enough space

daisy_workflows/export/disk_export.wf.json
Some SQL images might be 30 GB or higher, so this is a safer value for the sha hash
=> Use 40 GB daisy instance

daisy_workflows/image_build/install_package/cos/install_package_cos.wf.json
Depending on whether we are running on arm image or on amd image, the worker image will have to be either debian-11-worker or debian-11-worker-arm64 etc..
CCing @a-crate, @dorileo, and @zmarano.
=> Pass worker image in as an arg

cli_tools/gce_image_publish/main.go
Add a -date_version option that sets the publish version to vYYYYMMDD
-date_version can not be used with -publish_version
=> Add a -date_version option that sets the publish version to vYYYYMMDD

daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_arm64.cfg
Make sure that Optimized Rocky doesn't use a kernel from Rock-BaseOS.repo and always uses the kernel from Rocky-CloudKernel.repo
=> Update Optimized Rocky to be sure to use cloud-kernel 

daisy_workflows/image_build/accelerator_images/ubuntu_2204_with_nvidia_550.wf.json
There is no amd64, although 2404 has it.
=> Update image path for Ubuntu 2204 accelerator build

daisy_workflows/image_build/accelerator_images/build_rocky_linux_8_optimized_gcp_accelerated.sh, daisy_workflows/image_build/accelerator_images/build_rocky_linux_9_optimized_gcp_accelerated.sh
We aren't building with GPU machines so this is guaranteed to fail
=> Drop nvidia-smi from build script

gce_recovery_scripts/README.md, gce_recovery_scripts/recover_windows_instance.sh, gce_recovery_scripts/reinstall-gvnic-gq.ps1
- recover_windows_instance.sh - Generic script to do offline remediation of a Windows instance's boot disk.
- reinstall-gvnic-gq.ps1 - Script to be used with recover_windows_instance.sh to do offline removal of Windows gvnic driver and installation of known good version Windows gvNIC GQ driver.
=> Scripts to do offline remediation of Windows instances.

daisy_workflows/export/disk_export.wf.json, daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json, daisy_workflows/sbom_validation/windows_sbom_validation.wf.json
We will likely deprecate debian 10 and 11 workers, so we should switch to the debian 12 worker.
=> Switch to debian 12 worker

daisy_workflows/image_build/debian/debian_worker.sh
I saw at least one build failure that looked like this:
```
2024-11-18T16:02:40.781311+00:00 inst-installerprep-rocky-linux-8-build-build-rocky-pv6n7 google_metadata_script_runner[640]: startup-script-url: + DEBIAN_FRONTEND=noninteractive apt-get -q -y install python3-pip
[   16.308162] google_metadata_script_runner[640]: startup-script-url: E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1490 (apt-get)
2024-11-18T16:02:40.804449+00:00 inst-installerprep-rocky-linux-8-build-build-rocky-pv6n7 google_metadata_script_runner[640]: startup-script-url: E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1490 (apt-get)
[   16.308314] google_metadata_script_runner[640]: startup-script-url: E: Unable to acquire the dpkg frontend lock …
```
=> Disable APT Daily on Debian worker image to avoid APT lock contention

daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_arm64.cfg
Removes warnings for nonexistent eclipse aarch64 module in RHEL 8.
```
Modular dependency problems:
Problem 1: nothing provides requested module(eclipse:rhel8:8020120200522125903)
Problem 2: nothing provides requested module(eclipse:rhel8:8030020201023061315)
Dependencies resolved.
```
=> Disable the eclipse module for RHEL 8 aarch64 to avoid warnings from dnf.

daisy_workflows/export/disk_export_ext.wf.json, daisy_workflows/export/disk_resizing_mon.sh, daisy_workflows/export/export_disk_ext.sh
- Newer Linux kernels (notably the 6.1 kernel in Debian 12 used in this workflow) have non-deterministic device ordering. Relying on the device names is no longer reliable. Instead we use the ID's generated by the built in udev rules.
=> Fix external image/disk export scripts to work with Debian 12.

daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2025-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2025-dc-uefi.publish.json
Add support for byol environment publishing recently added to concourse
=> Update server and server core publish workflows for byol

daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_550.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.wf.json
The publish can use the full URI but Daisy needs a relative path
=> Update licenses on Daisy build workflows

daisy_workflows/image_build/install_package/cos/package_replacement/install_go.sh
COS builds are complaining with error `go: golang.org/x/crypto@v0.35.0 requires go >= 1.23.0 (running go 1.22.2)`. Update golang dependency to [match with other Guest Packages](https://github.com/GoogleCloudPlatform/guest-test-infra/blob/34a575c40a725468ccc9a71663b2b3203e5ead95/packagebuild/common.sh#L57C3-L57C47)
=> Update golang dependency

daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.publish.json
In the Cloud Console, the current description is identical to the 570 one, making it confusing which is which.
=> Update "latest" Rocky Accel Descriptions

daisy_workflows/image_build/install_package/install_package.wf.json
pd-ssd is not compatible with c4a,  allow overriding disk type instead of hardcoding
/cc @dorileo @drewhli
=> allow overriding disk type instead of hardcoding

daisy_workflows/image_build/install_package/cos/package_replacement/preload.sh
google-startup-scripts.service is missing in COS 109 so the test can't be run.
Adding /lib into the find path for COS 109 since google-startup-scripts.service stays in /lib/systemd/system.
Also add more logging here for future debugging purposes.
=> Fix CIT tests for COS 109

daisy_workflows/image_build/install_package/installpackage.py
Adds logic to check for and remove a broken symlink if one exists for resolv.conf while preserving the previous behavior for OSes that do not have a broken symlink or have a file at that location.
Context: Debian-13 moved to a symlink for resolv.conf which causes a terminating error when the builder finds a broken symlink it can't follow.
Verified that Rhel-8, Rhel-9, and Debian-12 can still build with this change.
=> Update installpackage resolv.conf check

daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_x86.cfg
Different labels `EOM` and `EOF` was used for `/etc/yum.repos.d/centos-stream9-baseos.repo`, use same and have consistency across file
=> Fix kickstart file syntax

daisy_workflows/image_build/install_package/installpackage.py, daisy_workflows/image_build/install_package/windows/installpackage.ps1
This will help triaging the test failures. Test no longer need to handle it individually and restart the agent.
/cc @dorileo @drewhli 
/hold
=> Enable debug logging on test images

daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh
COS recently has a TPC patch that's added to the master branch. But the script didn't support google-guest-agent repo so applying the patch will complain on milestones < 125. Let's add the short-term fix for now to add the patch to the ignored list.
In the long term, we should migrate the script to add google-guest-agent repo and always use master branch.
=> Fix patch didn't apply issue for COS image

daisy_workflows/build-publish/enterprise_linux/almalinux_9_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/centos_stream_10_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/centos_stream_9_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_10_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_10_byos_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_byos_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_byos_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.publish.json, daisy_workflows/image_build/enterprise_linux/almalinux_9_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/centos_stream_10_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/centos_stream_9_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_10_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_10_byos_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_8_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_8_byos_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_9_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_9_byos_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_9_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.wf.json
The drivers seem to be also present on all the EL ARM images. Given that we added the tag to all the EL x86_64 images, it makes sense to do the same for ARM.
/hold
=> Add IDPF tag to EL ARM images.

daisy_workflows/image_build/install_package/cos/install_package_cos.wf.json, daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh
Editted daisy_workflows/image_build/install_package/ cos/package_replacement/compile_debian_package.sh to install the new google-guest-agent repo (plugin manager).
The patches for the new repo in COS will be renamed with a common prefix. Will file another CL to update it in the build script.
=> cos: update build script to install plugin manager
