GoogleCloudPlatform/compute-image-tools

daisy/workflow/common.go, daisy/workflow/common_test.go, daisy/workflow/step_create_disks.go, daisy/workflow/step_create_disks_test.go, daisy/workflow/step_create_images.go, daisy/workflow/step_create_images_test.go, daisy/workflow/step_create_instances.go, daisy/workflow/step_create_instances_test.go, daisy/workflow/step_delete_resources.go, daisy/workflow/step_delete_resources_test.go, daisy/workflow/step_wait_for_instances_stopped.go, daisy/workflow/step_wait_for_instances_stopped_test.go, daisy/workflow/test_common.go, daisy/workflow/validate.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
RefMaps handle mutex locking to resource references. Resources now have Resource struct which will help will subsequent work on resource persistence, resource real name access, etc.
=> Changed way resource references are managed -- RefMaps

daisy/daisy.go, daisy/workflow/common.go, daisy/workflow/common_test.go, daisy/workflow/step_create_instances.go, daisy/workflow/test.workflow, daisy/workflow/test_common.go, daisy/workflow/validate.go, daisy/workflow/validate_test.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
- Add logging that prints to stdout and streams to GCS
- Rename Workflow.Bucket to GCSPath 
- Fix sources upload
=> Add logging to Daisy

README.md, daisy/README.md
Add basic documentation and examples for workflow steps and the dependency map.
=> Update Daisy README

daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
Autovars are resolved AFTER Vars, meaning that Vars values override autovars. Also, autovars should not be used in top-level workflow fields, e.g. Name, Project, Zone, etc. Autovars pull values from these fields, so simultaneously pulling from and substituting in these top-level fields will create unpredictable behavior.
=> Added autovars processed after Vars.

daisy/workflow/step_sub_workflow.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
This is functionally equivalent to passing variables on the commandline to the subworkflow directly.
=> Added Vars field for Subworkflow steps.

daisy/workflow/sources.go, daisy/workflow/sources_test.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
Sources and any subworkflow relative paths will be looked up based on the directory the workflow file is in.
=> Lookup sources using the workflows working directory

daisy/compute/compute.go, daisy/compute/compute_test.go, daisy/workflow/step_create_disks.go, daisy/workflow/step_create_images.go, daisy/workflow/step_create_instances.go
Daisy will add a default description to instances, disks, and images. A custom description can be set in the workflow.
=> Add descriptions to resources

daisy/daisy.go, daisy/workflow/step_create_disks.go, daisy/workflow/step_create_images.go, daisy/workflow/step_create_instances.go, daisy/workflow/step_wait_for_instances_signal.go, daisy/workflow/step_wait_for_instances_signal_test.go, daisy/workflow/test.workflow, daisy/workflow/validate.go, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go
Populate WaitForInstancesSignal intervals
Fix index error if json error is the first position
Add USER autovar and add it to resource descriptions
Add validate flag to daisy that will just run validation
WaitForInstancesSignal can wait for only FailureMatch
=> Bug fixes and feature additions

daisy/README.md, daisy/workflow/common.go, daisy/workflow/step_create_disks.go, daisy/workflow/step_create_disks_test.go, daisy/workflow/step_create_images.go, daisy/workflow/step_create_images_test.go, daisy/workflow/step_create_instances.go, daisy/workflow/step_create_instances_test.go, daisy/workflow/validate.go
Actually allow partial URL's
Add more tests, clean up existing ones.
=> Allow creating of instances and disks in any project and zone.

daisy/README.md, export/README.md, export/export.go
Use -gcs_path flag to specify upload location
Use a parallel gzip library
Add -oauth flag to specify oauth credentials file
Fix status printout when exporting
=> Update the export tool

daisy/compute/common_test.go, daisy/compute/compute.go, daisy/compute/compute_test.go
This method isn't being used yet, but will be in following PRs.
=> Added compute.CreateInstance.

Dockerfile.daisy, daisy/daisy_test.go, daisy/workflow/step_includeworkflow.go, daisy/workflow/step_sub_workflow.go, daisy/workflow/test.wf.json, daisy/workflow/test_sub.wf.json, daisy/workflow/workflow.go, daisy/workflow/workflow_test.go, daisy_latest_cloudbuild.yaml, daisy_release_cloudbuild.yaml
Autovars can now be used in Vars
=> Use a custom unmarshaller for vars, fix IncludeWorkflow autovars

daisy/compute/compute.go, daisy/workflow/resources.go, daisy/workflow/step_includeworkflow.go, daisy/workflow/step_includeworkflow_test.go, daisy/workflow/step_wait_for_instances_signal.go, daisy/workflow/workflow.go
STOPPED is a status too
Fix IncluedWorkflow issues caused by previous PR
=> Fix WaitForInstancesSignal again

daisy/compute/compute.go, daisy/compute/compute_test.go, daisy/compute/test_client.go, daisy/compute/test_client_test.go, daisy/workflow/common.go, daisy/workflow/disk.go, daisy/workflow/image.go, daisy/workflow/instance.go, daisy/workflow/step_create_instances.go, daisy/workflow/step_wait_for_instances_signal.go, daisy/workflow/step_wait_for_instances_signal_test.go
Move WaitForInstanceStopped out of compute.go
=> Fix deletion and wait for instance to use link for project/zone

daisy/disk.go, daisy/disk_test.go, daisy/step_includeworkflow.go, daisy/workflow.go
- nested Step dependency wasn't working.
- Had to mark IncludeWorkflows' parent on NewIncludedWorkflow.
=> Fix attached disk checking between steps in different IncludeWorkflows.

daisy_workflows/image_import/enterprise_linux/translate_el.sh
Fix error
oot: command not found
=> translate_el.sh: s/oot/chroot

daisy_workflows/image_import/enterprise_linux/translate_el.sh
Fix wrong variable name, path for chroot and add explicit boot config
=> translate_el.sh: license/path fixes and boot config

daisy_tutorials/README.md, daisy_tutorials/modify_image/README.md, daisy_tutorials/modify_image/emacs_image.wf.json, daisy_tutorials/modify_image/emacs_install.sh
Let me know what you think of the directory structure. Should this be under `daisy_workflows`? It is good to separate educational material from full working actually-used examples. Looks like `daisy_workflows/examples` should me morphed into tutorials.
=> Modify image tutorial.

daisy_workflows/image_import/import_image.sh
- Also, add progress to the qemu-img convert command (will pipe this to a status message later).
=> Fix gcloud commands which now ask for input.

daisy/prowjob/requirements.txt, daisy/prowjob/run/__main__.py, daisy/prowjob/run/common.py, daisy/prowjob/run/e2e_tests/__main__.py, daisy/prowjob/run/gcs.py, daisy/prowjob/run/git.py, daisy/prowjob/run/unit_tests/__main__.py, test-infra/prow/config.yaml
Will need a few things still, but it's functional. Next thing coming up for e2e test runner: test timeouts.
=> First e2e test runner version. Also, a few e2e test fixes.

daisy_workflows/image_import/ubuntu/translate_ubuntu.py, daisy_workflows/image_import/ubuntu/translate_ubuntu.sh, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
This tool should mount the disk independently if LVM is being used or if
/boot is in a separate partition and perform customizations in the VM
image.
=> translate_ubuntu: use python-guestfs

daisy_workflows/image_import/enterprise_linux/translate_el.py
In centos 6, dracut doesn't have --kver option, it uses grub and not
grub2 and file 70-persistent-net.rules should be removed to force it to
be regenerated at boot, otherwise networking may not work due to
hardcoded MAC address in this file
=> translate_el: fix centos 6

daisy/step_wait_for_instances_signal.go
Returning early before instance is fully stopped can cause issues if the next step uses any of the resources.
=> Don't return from waitForSerialOutput if instance is STOPPING

daisy_workflows/e2e_tests/copy_gcs_object.wf.json
A grade-A fix from the Yours Truly, the Typo King.
=> Fix copy_gcs_object test

daisy/validate.go, daisy/validate_test.go, daisy/workflow.go, daisy/workflow_test.go
=> Add clearer errors on invalid project and zone

daisy_workflows/image_build/debian/debian_8.wf.json, daisy_workflows/image_build/debian/debian_9.wf.json, daisy_workflows/image_build/enterprise_linux/README.md, daisy_workflows/image_build/enterprise_linux/build_installer.py, daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_7.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_7_byol.wf.json
Update Debian bootstrap-vz versions.
Remove unused RHEL point release bits and update README.
=> Cleanup some image build bits.

daisy_workflows/image_import/enterprise_linux/translate.py
Fix comparison with the string '7' instead of the number
=> image_import: el: install sdk in el_release 7

docs/daisy-import-userguide.md
LVM and different partition schemes are supported
=> docs: Remove partitions and LVM limitation from import guide

daisy/error.go, daisy/error_test.go, daisy/image.go, daisy/resources.go, daisy/step_delete_resources.go, daisy/step_delete_resources_test.go, daisy/workflow.go
Fail validation if an image is marked OBSOLETE or DELETED
Fixes issue #233 and #242
=> Only log errors when a resource DNE in DeleteResources

import_precheck/check.go, import_precheck/check_disks_linux.go, import_precheck/check_disks_windows.go, import_precheck/check_osversion.go, import_precheck/check_powershell.go, import_precheck/check_ssh.go, import_precheck/common.go, import_precheck/main.go, import_precheck/report.go, import_precheck/user_linux.go, import_precheck/user_windows.go
This precheck tool, for now, only checks OS Versions against a list of GCE official supported OSes.
=> Starting precheck tool.

README.md, daisy/README.md, docs/daisy.md, docs/index.md
=> remove word "complex" from docs so we dont scare away users.

cli_tools/gce_image_publish/main.go, cli_tools/gce_image_publish/main_test.go, daisy_workflows/image_build/sqlserver/sql-2012-standard-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2014-standard-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2012-r2-dc.wf.json
Add flag overrides for publish template values
Allow running multiple publish templates
=> Update gce_image_publish tool

cli_tools/daisy/main.go, cli_tools/daisy/main_test.go, cli_tools/gce_image_publish/main.go, cli_tools/gce_image_publish/main_test.go, daisy/workflow.go, daisy/workflow_test.go
Also fix gce_image_publish
Remove daisy storage endpoint override as it has no known use
=> Make ComputeEndpoint a workflow field

cli_tools/gce_image_publish/main.go, cli_tools/gce_image_publish/main_test.go
Individual image failures wont stop the entire publish process
Add -filter flag to allow filtering on image prefixes
=> Make each Image in a publish template it's own workflow

daisy_workflows/image_build/debian/README.md, daisy_workflows/image_build/debian/build.py, daisy_workflows/image_build/debian/debian.wf.json, daisy_workflows/image_build/debian/debian_8.wf.json, daisy_workflows/image_build/debian/debian_9.wf.json, daisy_workflows/image_build/debian/google_cloud_test_repos/__init__.py, daisy_workflows/image_build/debian/google_cloud_test_repos/manifest-schema.yml, daisy_workflows/image_build/debian/google_cloud_test_repos/tasks.py
- Also cleanup unnecessary tar exports and other oddities.
=> Fix Debian build workflows to correctly handle Google Cloud Repos.

daisy_workflows/image_build/debian/build.py, daisy_workflows/image_build/debian/debian.wf.json, daisy_workflows/image_build/enterprise_linux/build_installer.py, daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/common-packages.cfg, daisy_workflows/image_build/enterprise_linux/ks_helpers.py, daisy_workflows/image_build/enterprise_linux/save_logs.py, daisy_workflows/image_build/linux_common/bootstrap.py, daisy_workflows/image_build/linux_common/utils.py
- Remove a bunch of unused utility functions from ancient days.
- Fix logging output for bootstrapper, utils, and all Linux builds.
- Use Status, Success, and Failure serial console logging for Daisy workflows.
- Add in the net-tools package for EL (which was missing in EL7 builds for some reason).
=> Refactor Linux build logging and utils.

daisy_workflows/image_import/import_and_translate.wf.json
This workflow is needed for the new `gcloud compute images import` changes.
=> Add a new workflow that imports and then runs a specified translate workflow

daisy_workflows/image_import/import_and_translate.wf.json, daisy_workflows/image_import/import_image.wf.json
The import workflows only take GCS paths, not local files. Their descriptions now correctly reflect this fact.
=> Change descriptions in import workflow to be more accurate.

daisy_workflows/image_import/enterprise_linux/translate.py
=> Add CloudSDK to EL6 translation

test-infra/prow/new_config.yaml, test-infra/prowjobs/daisy-e2e/Dockerfile, test-infra/prowjobs/unittests/Dockerfile, test-infra/prowjobs/wrapper/Dockerfile, test-infra/prowjobs/wrapper/main.go
Results are parsed by testgrid and gubenator.
=> Prowjobs: adding a wrapper binary to the prowjobs. Uploads results to GCS.

daisy_workflows/image_test/README.md, daisy_workflows/image_test/boot.wf.json, daisy_workflows/image_test/img_test.wf.json, daisy_workflows/image_test/scripts/boot.sh
Implementing boot tests on the image given by the source_image variable
=> Start implementation of Linux integration tests

daisy/compute/compute.go, daisy/compute/compute_test.go, daisy/compute/test_client.go, daisy/compute/test_client_test.go, daisy/disk.go, daisy/resource.go, daisy/step_attach_disk_test.go, daisy/step_attach_disks.go, daisy/test_common_test.go, docs/daisy-workflow-config-spec.md
=> Daisy: Add AttachDisks step type

daisy_workflows/e2e_tests/image_export.wf.json, daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/export_disk.sh, daisy_workflows/export/image_export.wf.json
=> Fix export workflows

daisy_workflows/image_test/linux_common/bootstrap.py, daisy_workflows/image_test/linux_common/utils.py, daisy_workflows/image_test/metadata-ssh-tester.py, daisy_workflows/image_test/metadata-ssh.wf.json
First implementation of metadata-ssh tests
Include linux_common for metadata ssh tests to allow reuse in other
tests
=> image_test: Add metadata-ssh tests

test-infra/README.md, test-infra/prow/config.yaml, test-infra/prowjobs/daisy-e2e/Dockerfile, test-infra/prowjobs/flake8/Dockerfile, test-infra/prowjobs/flake8/main.sh, test-infra/prowjobs/gocheck/Dockerfile, test-infra/prowjobs/wrapper/main.go
Use latest container sources
Clean up wrapper a bit to catch errors
=> prow: add flake8 presubmit for python code

daisy_workflows/image_import/import_disk.wf.json, daisy_workflows/image_import/import_image.sh
- Only tries to import the first VMDK in an OVA archive.
- Assume the format of the vmdk is what we see from an exported vmware OVA.
- Yes, its hacky- open to suggestions.
=> Add pseudo support for OVA

docs/daisy-workflow-config-spec.md
=> docs: fix typo s/Dasiy/Daisy

docs/daisy-workflow-config-spec.md
sorry, I review misspelled words using manual heuristics, and sometimes I decide that random letters are variables.
My brain clearly miscategorized this token. But, reading it (since I'm actually considering using this software), I realized that this is also not right....
=> spelling: files

daisy_workflows/image_build/debian/README.md, daisy_workflows/image_build/debian/build.py, daisy_workflows/image_build/debian/debian_8.wf.json, daisy_workflows/image_build/debian/debian_9.wf.json
- This is more consistent with the other image builds.
=> Fix Debian build and take full .tar.gz path as image_dest arg.

docs/daisy-workflow-config-spec.md
zones is what I'm seeing on gce
=> s/zone/zones in PartialURL description

daisy/README.md, daisy/disk_test.go, daisy/network_test.go, daisy/step_delete_resources_test.go, daisy/step_includeworkflow_test.go, daisy/test_common_test.go, daisy/workflow.go, daisy/workflow_test.go, docs/daisy-installation-usage.md
- Test Cloud Logging permissions when creating client by pinging the service.
- Update documentation.
- Add more tests.
=> Cloud Logging - test permissions when creating client.

cli_tools/daisy/main.go, cli_tools/daisy/main_test.go, daisy/logger.go, daisy/logger_test.go, daisy/step_attach_disks.go, daisy/step_create_disks.go, daisy/step_create_images.go, daisy/step_create_instances.go, daisy/step_create_instances_test.go, daisy/step_create_networks.go, daisy/step_delete_resources.go, daisy/step_deprecate_images.go, daisy/step_includeworkflow.go, daisy/step_sub_workflow.go, daisy/step_wait_for_instances_signal.go, daisy/step_wait_for_instances_signal_test.go, daisy/validate.go, daisy/workflow.go, daisy/workflow_test.go, daisy_workflows/e2e_tests/validate_cloud_logging.wf.json
Daisy logs to all sources by default, the daisy binary has flags to disable each location
StepInfo records step name and step type
=> Daisy: Fixup cloud logging

daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
Adds a step to set the vEthernet MTU inside a container. This change is
then reflected in all subsequent containers based on the
windowsservercore and nanoserver images.
Fixes a bug where the host vEthernet MTU was not being set correctly
because the interface did not exist yet.
=> Daisy: set MTUs in Windows-for-containers image.

daisy/logger.go, daisy/step_attach_disks.go, daisy/step_create_disks.go, daisy/step_create_images.go, daisy/step_create_instances.go, daisy/step_create_instances_test.go, daisy/step_create_networks.go, daisy/step_delete_resources.go, daisy/step_includeworkflow.go, daisy/step_wait_for_instances_signal.go, daisy/workflow.go
Clean up log text
Make GCS links clickable instead of using the gs:// path
=> Daisy: Log serial output to cloud logging

daisy_workflows/image_test/configuration/centos.py, daisy_workflows/image_test/configuration/configuration-test.py, daisy_workflows/image_test/configuration/configuration.wf.json, daisy_workflows/image_test/configuration/debian.py, daisy_workflows/image_test/configuration/generic_distro.py, daisy_workflows/image_test/configuration/redhat.py, daisy_workflows/image_test/configuration/suse.py, daisy_workflows/image_test/configuration/ubuntu.py, daisy_workflows/image_test/img_test.wf.json, daisy_workflows/image_test/linux_common/utils.py
Currently working on:
rhel-6
centos-6
rhel-7
centos-7
debian-8
debian-9
Detected sshd_config mismatch on the following images:
ubuntu-1404-lts
ubuntu-1604-lts
ubuntu-1710
ubuntu-1804-lts
(https://github.com/GoogleCloudPlatform/compute-image-packages/issues/604)
Couldn't test SUSE because of missing gsutils. This will require changes
in bootstrap.py (will be sent in another PR)
=> Add linux configuration integration tests

daisy_workflows/image_test/configuration/configuration-test.py, daisy_workflows/image_test/configuration/debian.py, daisy_workflows/image_test/configuration/freebsd.py, daisy_workflows/image_test/configuration/generic_distro.py, daisy_workflows/image_test/configuration/suse.py, daisy_workflows/image_test/configuration/ubuntu.py
=> Configuration integration tests cmdline

daisy/instance.go, daisy_workflows/e2e_tests/create_instances.wf.json
=> Daisy: allow creating instances with local-sdd attached

daisy_workflows/image_test/disk/disk-local-ssd.sh, daisy_workflows/image_test/disk/disk-testee.sh, daisy_workflows/image_test/disk/disk-tester.py, daisy_workflows/image_test/disk/disk.wf.json, daisy_workflows/image_test/img_test.wf.json, daisy_workflows/image_test/linux_common/utils.py
Implementing Disk requirements from daisy_workflows/image_test/README.md
=> Disk integration test

daisy_workflows/image_test/disk/disk-tester.py, daisy_workflows/image_test/disk/disk.wf.json, daisy_workflows/image_test/linux_common/bootstrap.py, daisy_workflows/image_test/linux_common/utils.py, daisy_workflows/image_test/metadata-ssh/metadata-ssh-tester.py, daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json, daisy_workflows/image_test/oslogin-ssh/oslogin-ssh-master-tester.py, daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
Fix broken API after google/google-api-python-client#499
=> Fix oauth2 deprecation

cli_tools/daisy_test_runner/main.go, test-infra/prow/Makefile, test-infra/prow/cluster/deck_deployment.yaml, test-infra/prow/cluster/hook_deployment.yaml, test-infra/prow/cluster/horologium_deployment.yaml, test-infra/prow/cluster/plank_deployment.yaml, test-infra/prow/cluster/sinker_deployment.yaml, test-infra/prow/cluster/splice_deployment.yaml, test-infra/prow/cluster/starter.yaml, test-infra/prow/cluster/tide_deployment.yaml, test-infra/prow/cluster/tot_deployment.yaml, test-infra/prow/config.yaml, test-infra/prow/plugins.yaml, test-infra/prowjobs/gocheck/main.sh
=> prow: update container versions

cli_tools/daisy_test_runner/main.go, daisy/common.go, daisy/common_test.go, daisy/test_data/almost_too_big.txt, daisy/test_data/big_string.txt, daisy/test_data/test_2.txt, daisy_workflows/image_test/boot/boot.bat, daisy_workflows/image_test/boot/boot.wf.json, daisy_workflows/image_test/linux_images.test.gotmpl, daisy_workflows/image_test/multi-nic/multi-nic-master.bat, daisy_workflows/image_test/multi-nic/multi-nic-master.sh, daisy_workflows/image_test/multi-nic/multi-nic-slave.bat, daisy_workflows/image_test/multi-nic/multi-nic-slave.sh, daisy_workflows/image_test/multi-nic/multi-nic.wf.json, daisy_workflows/image_test/windows_images.test.gotmpl, test-infra/prow/config.yaml
Also added network, metadata-script and multi-nic tests to prow testing.
=> Port boot and multi-nic integration tests to windows

daisy_integration_tests/2003_32_translate.wf.json, daisy_integration_tests/2008r2_vmware_translate.wf.json, daisy_integration_tests/2012r2_vmware_translate.wf.json, daisy_integration_tests/2016_translate.wf.json, daisy_integration_tests/can_retrieve_sources.wf.json, daisy_integration_tests/centos_6_qcow2_translate.wf.json, daisy_integration_tests/centos_7_qcow2_translate.wf.json, daisy_integration_tests/image_export_latest.wf.json, daisy_integration_tests/image_export_release.wf.json, daisy_integration_tests/scripts/output-and-stop.sh, daisy_integration_tests/scripts/retrieve-files-from-gcs.sh, daisy_integration_tests/scripts/stop.sh, daisy_integration_tests/step_attach_disks.wf.json, daisy_integration_tests/step_copy_gcs_object.wf.json, daisy_integration_tests/step_create_disks.wf.json, daisy_integration_tests/step_create_images.wf.json, daisy_integration_tests/step_create_instances.wf.json, daisy_integration_tests/step_create_networks.wf.json, daisy_integration_tests/step_include_workflow.subwf.json, daisy_integration_tests/step_include_workflow.wf.json, daisy_integration_tests/step_wait_for_instance_signal.wf.json, daisy_integration_tests/ubuntu_1404_img_translate.wf.json, daisy_integration_tests/ubuntu_1604_import_and_translate.wf.json, daisy_integration_tests/ubuntu_1604_vmware_translate.wf.json, daisy_integration_tests/validate_cloud_logging.wf.json, daisy_integration_tests/vmdk_import.wf.json
Most workflows are unchanged, just formatted
step_copy_gcs_object and the export workflows are updated to fix permission issues.
=> e2e tests: fix a few permission issues, format workflows

cli_tools/import_precheck/user_linux.go
Root may not be root in some cases.
=> Check uid instead of username.

daisy_workflows/image_test/boot/boot.wf.json, daisy_workflows/image_test/linux_images.test.gotmpl, daisy_workflows/image_test/windows_images.test.gotmpl
And setup the skylake platform for the boot test with n1-standard-96
machine type.
=> Add optional min_cpu_platform parameter to boot test

daisy_workflows/image_test/windows_images.test.gotmpl
=> Solve quota issues for windows too

daisy_workflows/image_build/debian/debian_10_fai.wf.json, daisy_workflows/image_build/debian/debian_9_fai.wf.json
Now it points to the correct buster repository.
=> Fix FAI script reference for building buster images

daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
Tested:
```
$ time daisy -project <project> -zone us-west1-b path/to/windows-1803-for-containers.wf.json`
[Daisy] Running workflow "windows-1803-for-containers-image-build" (id=8zrx7)
[Daisy] Workflow "windows-1803-for-containers-image-build" finished
[Daisy] All workflows completed successfully.
real	14m54.632s
user	0m1.964s
sys	0m0.752s
```
Booted a VM with the image:
```
C:\>docker --version
Docker version 18.03.1-ee-3, build b9a5c95
```
=> Install Docker EE 18.03 in windows_for_containers workflow.

daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/disk_export_ext.wf.json, daisy_workflows/export/image_export.wf.json, daisy_workflows/export/image_export_ext.wf.json
Passing this variable to CreateInstance step. Specifying subnet is necessary when a
GCP project has custom network setup.
=> Added subnet variable to image and disk export workflows.

daisy/step_sub_workflow.go
=> daisy: don't cancel workflow on subworkflow completion

daisy_workflows/image_build/debian/build.py, daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json, daisy_workflows/image_import/debian/translate.py, daisy_workflows/image_import/enterprise_linux/translate.py, daisy_workflows/image_import/suse/translate.py, daisy_workflows/image_import/ubuntu/translate.py, daisy_workflows/linux_common/utils/__init__.py, daisy_workflows/linux_common/utils/common.py, daisy_workflows/linux_common/utils/diskutils.py, image_test/configuration/linux/generic_distro.py, test-infra/prowjobs/flake8/main.sh
Fix weird imports and various failing flake8 lines
=> Flake8 fixups

daisy_workflows/image_build/debian/debian.wf.json, daisy_workflows/image_build/debian/debian_fai.wf.json, daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json, daisy_workflows/image_import/debian/translate_debian.wf.json, daisy_workflows/image_import/enterprise_linux/translate_el.wf.json, daisy_workflows/image_import/freebsd/translate_freebsd.wf.json, daisy_workflows/image_import/suse/translate_suse.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json, image_test/configuration/linux-configuration.wf.json, image_test/metadata-ssh/metadata-ssh.wf.json, image_test/network/network.wf.json, image_test/oslogin-ssh/oslogin-ssh.wf.json
utils.py was changed from module to package and split into multiple files; update workflow JSON to reflect this
=> Fix utils.py path in workflows

cli_tools/osconfig_agent/osconfig_linux.go, unittests.sh
=> Add stubs for zypper support

cli_tools/osconfig_agent/google-osconfig-agent.goospec, cli_tools/osconfig_agent/inventory.go, cli_tools/osconfig_agent/main.go
This is really basic for now, it's almost a straight copy paste of the relevant code. This will morph as we update the design of the overall agent.
=> osconfig_agent: Merge in inventory agent functionality

daisy_workflows/image_import/windows/translate_windows_10_byol.wf.json
* Support end user supplied licensing
=> Add image_import workflows for Windows 10

daisy_workflows/image_import/windows/translate_windows_7_byol.wf.json
* Support end user supplied licensing
=> Add image_import workflows for Windows 7

daisy_workflows/image_build/enterprise_linux/build_installer_uefi.py, daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-uefi-post.cfg, daisy_workflows/image_build/enterprise_linux/save_logs.py
Some changes I needed to make UEFI workflow successful
=> UEFI workflow updates

daisy_workflows/linux_common/utils/common.py, daisy_workflows/linux_common/utils/diskutils.py
Fix diskutils.py and HttpGet when downloading raw functions to work with python 3.
=> Fix conversion to python 3 in translation workflows

image_test/oslogin-ssh/oslogin-ssh-master-tester.py, image_test/oslogin-ssh/oslogin-ssh.wf.json
Add a status message to be printed before starting each test.
Make it logs easier to identify which test is failing.
=> image_test: oslogin: add status messages

cli_tools/osconfig_agent/config/config.go, cli_tools/osconfig_agent/logger/logger.go, cli_tools/osconfig_agent/main.go, cli_tools/osconfig_agent/ospackage/ospackage_linux.go, cli_tools/osconfig_agent/service/service.go, osconfig_tests/test_suites/inventory/inventory.go
=>  osconfig_agent: Add Apt and Yum ospackage commands

cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/mock_test.go, cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client.go, cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client_example_test.go, cli_tools/google-osconfig-agent/inventory/inventory.go, cli_tools/google-osconfig-agent/logger/logger.go, cli_tools/google-osconfig-agent/main.go, cli_tools/google-osconfig-agent/ospackage/ospackage_linux.go, cli_tools/google-osconfig-agent/ospackage/ospackage_windows.go, cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec, cli_tools/google-osconfig-agent/patch/patch_policies.go, cli_tools/google-osconfig-agent/patch/patch_policies_test.go, cli_tools/google-osconfig-agent/patch/patch_state.go, cli_tools/google-osconfig-agent/patch/patch_state_test.go, cli_tools/google-osconfig-agent/patch/patch_window.go, cli_tools/google-osconfig-agent/patch/patch_window_test.go, cli_tools/google-osconfig-agent/patch/updates_linux.go, cli_tools/google-osconfig-agent/patch/updates_windows.go, cli_tools/google-osconfig-agent/service/service.go, cli_tools/google-osconfig-agent/tasker/tasker.go, test-infra/prowjobs/gobuild/main.sh
Tested via `go build` and `go test`
=> Correct OSConfig import paths following name change

cli_tools/google-osconfig-agent/90-google-osconfig-agent.preset, cli_tools/google-osconfig-agent/google-osconfig-agent.conf, cli_tools/google-osconfig-agent/google-osconfig-agent.service, cli_tools/google-osconfig-agent/packaging/build_packages.wf.json, cli_tools/google-osconfig-agent/packaging/build_packages_deb.sh, cli_tools/google-osconfig-agent/packaging/build_packages_goo.sh, cli_tools/google-osconfig-agent/packaging/build_packages_rpm.sh, cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec, cli_tools/google-osconfig-agent/packaging/googet/install.ps1, cli_tools/google-osconfig-agent/packaging/google-osconfig-agent.spec, go/packages/packages_linux.go, osconfig_tests/test_suites/inventory/inventory.go
Add daisy workflows for the package builds
Auto start on el distros
=> osconfig_agent: update packaging process

cli_tools/google-osconfig-agent/patch/patch_run.go, cli_tools/google-osconfig-agent/patch/patch_state_test.go
This will make the saved data easier to read and ensure that if we add steps, order will be preserved.
=> Change patchSteps to strings

daisy_workflows/image_import/windows/translate.ps1
Install latest gce windows drivers from official repo.
=> Add driver package installation steps.

cli_tools/google-osconfig-agent/packaging/common.sh, cli_tools/google-osconfig-agent/packaging/debian/changelog, cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec, cli_tools/google-osconfig-agent/patch/patch_run.go, cli_tools/google-osconfig-agent/patch/system_linux.go, cli_tools/google-osconfig-agent/patch/system_windows.go, cli_tools/google-osconfig-agent/service/service.go
=> osconfig agent: disable system auto updates on agent start

osconfig_tests/test_suites/package_management/package_management_test_data.go
extracted out the demo package that is being used for testing osconfig-agent for each test setup
=> fix test assertion on correct package name

osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/package_management/package_management_test_data.go, osconfig_tests/test_suites/package_management/package_management_utils.go
* more refactoring done to add tests for other package managers
=> Add e2e tests for centos

osconfig_tests/test_suites/package_management/package_management_test_data.go
Needed to change packagemanager list to a tuple since centos/rhel uses the same package manager
=> Add test cases for rhel-7

osconfig_tests/test_suites/package_management/package_management_test_data.go
Also, renamed the variable to use more meaningful name
=> Fix more flaky tests

cli_tools/gce_image_publish/publish/publish.go
Mostly working - need to set `expiryDate` so that we don't deprecate existing images
=> make SetExpire public, so that expiry date can be computed

cli_tools/google-osconfig-agent/config/config.go, cli_tools/google-osconfig-agent/config/config_test.go, cli_tools/google-osconfig-agent/main.go, cli_tools/google-osconfig-agent/ospackage/ospackage.go, cli_tools/google-osconfig-agent/ospatch/patch_run.go, cli_tools/google-osconfig-agent/ospatch/patch_state.go, cli_tools/google-osconfig-agent/packaging/common.sh, cli_tools/google-osconfig-agent/packaging/debian/changelog, cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec
Cache metadata lookups on config
Update package versions
=> osconfig agent: close connections once finished with them, add metadata key for endpoint override

cli_tools/google-osconfig-agent/ospatch/patch_run.go, cli_tools/google-osconfig-agent/ospatch/system_linux.go, cli_tools/google-osconfig-agent/ospatch/system_test_stub.go, cli_tools/google-osconfig-agent/ospatch/system_windows.go, cli_tools/google-osconfig-agent/ospatch/updates_linux.go, cli_tools/google-osconfig-agent/ospatch/updates_test_stub.go, cli_tools/google-osconfig-agent/ospatch/updates_windows.go
Created stuff files for future unit tests.
=> osconfig agent: actually enable ospatch when set in metadata

osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/package_management/package_management_test_data.go, osconfig_tests/test_suites/package_management/package_management_utils.go
* created the rapture test repository
* Added a cowsay package
* Since windows updates takes a long time, i had to increase the assertion timeout for test case failure.
=> [osconfig-agent] add windows end to end tests

osconfig_tests/compute/instance.go, osconfig_tests/test_config/project_config.go, osconfig_tests/test_suites/inventory/inventory.go, osconfig_tests/test_suites/patch/patch.go, osconfig_tests/test_suites/patch/test_setup.go, osconfig_tests/utils/utils.go
Fixes failing WIndows tests
Adds tests for reboot (expected reboot and no-reboot)
Adds tests for Apt and Yum settings
=> osconfig tests: add new patch tests

osconfig_tests/compute/instance.go, osconfig_tests/test_suites/inventory/inventory.go, osconfig_tests/test_suites/inventory/test_setup.go, osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/package_management/package_management_test_data.go, osconfig_tests/test_suites/patch/patch.go, osconfig_tests/test_suites/patch/test_setup.go, osconfig_tests/utils/utils.go
OSPackage was still checking serial console output
Standardized WaitForGuestAttributes a bit more
Removed CreateOsConfigTest as it didn't test the agent at all
=> osconfig_tests: Fix Package tests, add rhel8 to Patch and Inventory

daisy_workflows/image_import/windows/translate.ps1
The deregister/register doesn't appear to do anything, so remove it all to deflake import
Running tests now to ensure this wasn't there for some forgotten reason
=> windows import: deflake NTP setup

osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/package_management/package_management_test_data.go, osconfig_tests/test_suites/package_management/package_management_utils.go, osconfig_tests/test_suites/patch/test_setup.go, osconfig_tests/utils/utils.go
Package management tests are simplified and Windows bugs fixed
Patch tests should work better now on Windows
=> osconfig_test: fix package management tests and tweak patch tests slightly

daisy/workflow.go
add cleaning up done msg for workflow
=> add cleaning up done msg for workflow

gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
Missed this change in last merged PR
=> fix a import line

gce_image_import_export_tests/compute/image.go, gce_image_import_export_tests/storage/file.go, gce_image_import_export_tests/test_suites/export/image_export_test_suite.go, gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
Current logic of verifying "labels" is incorrect. Changed the logic.
Improved implementation of verifying import/export result as well.
=> [import wrapper] fix e2e test "ImageImportWithRichParams"

cli_tools/gce_image_publish/publish/publish.go
When I bring my local workflow to CI, all I got was
```
googleapi: got HTTP response code 404 with body: Not Found
```
add some log to trace down where it actually fails :-\
=> improve error message from createWorkflow

daisy_workflows/export/export_disk_ext.sh
Use parallel uploading for exporting vmdk.
=> use parallel uploading for exporting vmdk

osconfig_tests/gcp_clients/gcp_clients.go, osconfig_tests/main.go, osconfig_tests/osconfig_server/assignment_wrapper.go, osconfig_tests/osconfig_server/osconfig_wrapper.go, osconfig_tests/test_suites/inventory/inventory.go, osconfig_tests/test_suites/package_management/package_management.go, osconfig_tests/test_suites/package_management/package_management_utils.go, osconfig_tests/test_suites/patch/patch.go
Cleanup client instantiation
Fix issues with the previous cleanup PR
=> osconfig_tests: fix OSPackage tests

daisy_workflows/image_build/windows/README.md, daisy_workflows/image_build/windows/bootstrap_install.ps1, daisy_workflows/image_build/windows/components/Autounattend-template.xml, daisy_workflows/image_build/windows/components/SetupComplete.cmd, daisy_workflows/image_build/windows/post_install.ps1, daisy_workflows/image_build/windows/windows-build.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc.wf.json
This PR includes:
- Bootstrap and Post-Install PowerShell files
- Windows Build base workflow
- Windows Server 2016 workflow
- Brief documentation describing workflow configuration and invocation
=> Create Windows Server build from ISO wf and doc

osconfig_tests/gcp_clients/gcp_clients.go, osconfig_tests/test_suites/patch/patch.go
Added new gcp client for new version. This allows us to move to v1alpha2 in stages.
=> [OS Config] Update patch tests to v1alpha2

daisy_integration_tests/81_x64_translate.wf.json, daisy_integration_tests/daisy_e2e.test.gotmpl, daisy_workflows/image_import/windows/translate_windows_8-1_x64_byol.wf.json
- Import (translate) workflow
- Daisy integration test
=> Import: Windows 8.1 x64

daisy_integration_tests/2019_translate.wf.json, daisy_integration_tests/daisy_e2e.test.gotmpl, daisy_workflows/image_import/windows/translate_windows_2019.wf.json, daisy_workflows/image_import/windows/translate_windows_2019_byol.wf.json
- Import (translate) workflow
- Daisy integration test
- Test import image (no drivers/GCE binaries) exists in test project
=> Import: Windows Server 2019

daisy/step.go, daisy/workflow.go, daisy_workflows/image_import/debian/translate_debian.wf.json, daisy_workflows/image_import/enterprise_linux/translate_el.wf.json, daisy_workflows/image_import/freebsd/translate_freebsd.wf.json, daisy_workflows/image_import/suse/translate_suse.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json, daisy_workflows/image_import/windows/translate_windows_wf.json
Extra info in translate timeout due to disk potentially not being bootable in GCE.
=> Extra error message when disk not bootable during import

osconfig_tests/test_suites/guestpolicies/guest_policies.go, osconfig_tests/test_suites/guestpolicies/guest_policies_test_data.go, osconfig_tests/test_suites/guestpolicies/guest_policies_utils.go, osconfig_tests/test_suites/inventory/inventory.go, osconfig_tests/test_suites/inventory/test_setup.go, osconfig_tests/test_suites/patch/patch.go, osconfig_tests/test_suites/patch/test_setup.go, osconfig_tests/utils/utils.go
Not all tests pass regularly yet, was having some issues with timeouts and want to get multiple runs in to see where the issues are.
=> osconfig_tests: add suse support

test-infra/prowjobs/cloudbuild.yaml
Currently the command breaks the auto build because the path doesn't work. Needs to change the path.
Verified the new command from my machine.
=> fix test images build cmd

cli_tools/gce_ovf_import/ovf_utils/ovf_programmatic_units.go, cli_tools/gce_ovf_import/ovf_utils/ovf_programmatic_units_test.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
In addition, converts the existing unit test into a table-based test.
This is in preparation for fixing
https://groups.google.com/d/msg/gce-discussion/k0LKjsH3dw8/Z5q_yv4nAAAJ
=> Refactor: Move ovf programmatic unit parsing to its own file.

cli_tools/gce_ovf_import/ovf_utils/ovf_programmatic_units.go, cli_tools/gce_ovf_import/ovf_utils/ovf_programmatic_units_test.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
Fixes https://groups.google.com/forum/#!topic/gce-discussion/k0LKjsH3dw8
=> Support additional unit types for OVF disk and memory sizes.

cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, daisy/resource_registry.go, daisy/resource_registry_test.go, daisy/workflow.go, daisy/workflow_test.go
cleanup all disks on OVF import failure. Added the ability to force clean in Daisy.
=> Ovf import cleanup on error

osconfig_tests/compute/instance.go, osconfig_tests/test_suites/guestpolicies/guest_policies.go, osconfig_tests/test_suites/guestpolicies/guest_policies_test_data.go, osconfig_tests/test_suites/guestpolicies/guest_policies_utils.go, osconfig_tests/utils/utils.go
=> osconfig_tests: ensure latest package is isntalled for GuestPolicies

cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go, daisy_workflows/image_import/import_disk.wf.json, daisy_workflows/image_import/import_image.sh
Testing:
Ran `go run gce_ovf_import_tests/main.go -test_project_id edens-test -test_zone us-central1-a`
=> Wait until persistent disks are attached prior to proceeding with import workflow.

cli_tools/common/utils/logging/service/logger.go
Enable logging. Need to wait for server side ready and do some test.
=> [wrapper logging] enable logging

osconfig_tests/test_suites/patch/patch.go, osconfig_tests/test_suites/patch/test_setup.go
Tested images:
-test_case_filter=debian-9
-test_case_filter=debian-10
-test_case_filter=ubuntu-1604-lts
-test_case_filter=centos-7
/woof
=> add OS Config agent e2e tests for pre-/post-patch steps

cli_tools/common/utils/logging/service/log_entry.go, cli_tools/common/utils/logging/service/logger.go, cli_tools/common/utils/logging/service/logger_test.go, cli_tools/common/utils/param/param_utils.go, cli_tools/gce_ovf_import/main.go, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_export/main.go, cli_tools/gce_vm_image_import/main.go
2 fix:
1. fix the hash function. Previous call is incorrect.
2. Update "project" and "obfuscated project" after the actual project name is fetched.
=> [logging] fix obfuscated project

osconfig_tests/test_suites/patch/patch.go, osconfig_tests/test_suites/patch/test_setup.go
Tested on
- windows-1803-core
- windows-1809-core
- windows-2012
- windows-2012-core
- windows-2019
- windows-2019-core
=> fix OS Config prepost patch agent e2e test setup

cli_tools/common/utils/daisy/daisy_utils.go, cli_tools/common/utils/daisy/daisy_utils_test.go, cli_tools/common/utils/daisy/resource_labeler.go, cli_tools/common/utils/logging/service/log_entry.go, cli_tools/common/utils/logging/service/logger.go, cli_tools/common/utils/string/string_utils.go, cli_tools/common/utils/string/string_utils_test.go, cli_tools/gce_ovf_import/main.go, cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go, cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/main.go, daisy/common.go, daisy/common_test.go, daisy/disk.go, daisy/disk_test.go, daisy/step_copy_gcs_objects_test.go, daisy/workflow.go, daisy_workflows/image_import/import_image.sh
In order to build dashboard for imported file format, we need to output it. The source is from qemu-info.
=> [logging] output 'imported file format'

daisy_workflows/image_import/import_image.sh
Testing:
- Ran OVF integration tests
=> Clarify when disk resizing fails due to insufficient privileges.

daisy/compute/test_client.go, daisy/step.go, daisy/step_update_instances_metadata.go, daisy/step_update_instances_metadata_test.go
You can now update an instance metadata as one of the steps in the following way:
```json
"UpdateInstancesMetadata": [
{
"Instance": "test-daisy-instance",
"Metadata": {
"test": "testing",
"test2": "testing2"
}
}
]
```
=> Add UpdateInstancesMetadata step

osconfig_tests/compute/instance.go, osconfig_tests/config/config.go, osconfig_tests/test_suites/guestpolicies/guest_policies.go, osconfig_tests/test_suites/guestpolicies/guest_policies_utils.go, osconfig_tests/test_suites/inventory/test_setup.go, osconfig_tests/test_suites/patch/patch.go, osconfig_tests/utils/utils.go
OSPackage tests renamed to GuestPolicies
=> osconfig_tests: ensure packages are updated prior to running tests

cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go, gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Still running integration tests; I'll wait for those prior to pushing.
=> Ensure OVF scratch data disk can be resized.

gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
De-duplicates the test description that was added in #1012.
=> Remove duplicated OVF test description.

daisy_workflows/export/export_disk.sh, daisy_workflows/export/export_disk_ext.sh, daisy_workflows/image_import/import_image.sh
Check for Google API access from image import/export scripts running in VMs.
=> Check for Google API access from image import/export scripts

daisy_workflows/image_import/import_image.sh
- Makes the pattern matching more flexible by removing the surrounding text.
- Indicates which role needs to be added.
=> Clarify roles that are required during import.

cli_tools/common/utils/daisy/daisy_utils.go
Added old variants of --os flag values for Windows client for backward compatibility
=> Added old variants of --os flag values for Windows client

cli_tools/diagnostics/google-compute-engine-diagnostics.goospec, cli_tools/diagnostics/main_windows.go, cli_tools/diagnostics/main_windows_test.go, cli_tools/diagnostics/rdp_status.ps1
Collect basic OS rdp settings according to the [troubleshooting guide](https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-rdp#os_configuration)
1. Created an external script `rdp_status.ps1`
2. Bumped the version to `1.1.0@0`
3. Sample of [rdp_status.txt](https://gist.github.com/YangLu1031/06d17984af0515b995ba6023f67f31ea#file-sample-of-rdp_status-txt)
=> Collect Basic RDP settings

daisy/logger_test.go, daisy/step_create_instances.go, daisy/step_create_instances_test.go
Testing:
- Ran OVF's integration tests.
=> Add retry to serial log polling.

daisy_workflows/image_build/enterprise_linux/build_installer.py, daisy_workflows/image_build/enterprise_linux/build_installer_uefi.py, daisy_workflows/image_build/enterprise_linux/centos_6.wf.json, daisy_workflows/image_build/enterprise_linux/centos_7.wf.json, daisy_workflows/image_build/enterprise_linux/centos_7_uefi.wf.json, daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json, daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/el6-post.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg, daisy_workflows/image_build/enterprise_linux/ks_helpers.py, daisy_workflows/image_build/enterprise_linux/rhel_6.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_6_byol.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_7.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_7_byol.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_7_sap.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_7_uefi.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_8.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_8_uefi.wf.json
Introduce a flag to optionally include the google-guest-agent package.
=> Enable building with NGE

daisy_workflows/image_build/enterprise_linux/ks_helpers.py
previous PR missed some lines, incorrectly applied some
=> fix package replacement

daisy_workflows/image_build/debian/debian_9.wf.json
=> add install_nge flag for deb9

daisy_workflows/image_build/debian/debian.wf.json
didn't stage this change in previous PR
=> add install_nge flag for debian base wf

cli_tools/common/utils/daisy/daisy_utils.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/go.mod, cli_tools/go.sum
Supported for image import in the previous PR. Now add supporting for image export/instance import
=> Better hint for missed default network: add supporting for image export/instance import

cli_tools/common/utils/daisy/daisy_utils.go, daisy_integration_tests/rhel_8_translate.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json
Includes support for GCP-licensed import. BYOL to come in a future PR.
=> Add support for importing RHEL8.

daisy_workflows/image_import/windows/bootstrap_2003.ps1, daisy_workflows/image_import/windows/translate_bootstrap.ps1
[Windows image import] translate script: add -Force for creating folder to ignore error if the folder exists.
=> [Windows image import] translate script: add -Force for creating folder

cli_tools/common/utils/daisy/daisy_utils.go, cli_tools/common/utils/storage/storage_client.go
Wrap storage and OS flag related errors in Daisy error to avoid exposing PII data
=> Wrap storage and OS flag related errors in Daisy error

daisy_workflows/image_import/import_image.sh
This is motivated by the VHDX format, which uses a journal to spool modifications to the underlying image. If the journal is non-empty, then it must be consumed prior to reading the image. VHDX calls this [log replay](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-vhdx/0d588e33-23a6-4c71-b27f-87d97ac3e914). qemu-img's repair isn't limited to VHDK, however [ref](https://manpages.debian.org/testing/qemu-utils/qemu-img.1.en.html).
Testing:
1. Created a truncated VMDK, and observed that import quit after the repair failed.
=> If an image is undecodable by qemu-img, attempt to repair it.

cli_tools/diagnostics/main_windows.go, cli_tools/diagnostics/main_windows_test.go
Need to dump docker image list for analysis:
https://github.com/kubernetes/kubernetes/issues/88011
=> Dump docker image list

daisy_integration_tests/centos_7_translate_immutable_etc_resolv.wf.json, daisy_workflows/image_import/enterprise_linux/translate.py, daisy_workflows/linux_common/utils/common.py
Testing:
- Ran new integration test, which fails prior to the patch to translate.py.
=> Allow EL import to proceed when /etc/resolv.conf is immutable.

daisy_integration_tests/daisy_e2e.test.gotmpl, daisy_integration_tests/debian_8_translate.wf.json, daisy_integration_tests/debian_9_translate.wf.json, daisy_workflows/image_import/debian/translate.py, daisy_workflows/image_import/suse/translate.py, daisy_workflows/image_import/ubuntu/translate.py, daisy_workflows/linux_common/utils/common.py, image_test/configuration/linux/debian.py, image_test/configuration/linux/redhat.py, image_test/oslogin-ssh/oslogin-ssh-master-tester.py
Adds retries for:
- Debian
- Ubuntu
- SUSE
And refactors `utils.RetryOnFailure` to allow configurable retry options (initial delay and total elapsed time)
=> Add retry to linux import package installation.

cli_tools/common/utils/daisy/daisy_utils.go, daisy_integration_tests/sles_12_4_byol.wf.json, daisy_integration_tests/sles_sap_12_4_byol.wf.json, daisy_workflows/image_import/suse/translate.py, daisy_workflows/image_import/suse/translate_sles_sap_12_byol.wf.json, test-infra/prowjobs/flake8/main.sh
* Adds two new tests: SLES 12.4 and SLES for SAP 12.4
* Includes a new `--os` flag value of `sles-sap-12-byol`
=> Add support for importing SLES 12.4

daisy_integration_tests/scripts/post_translate_test.sh
if the google guest agent binary exists, modify the test logic for check_google_services
=> update post translate test for NGE

daisy_integration_tests/scripts/run_daisy_and_check_logs.sh, daisy_integration_tests/validate_cloud_logging.wf.json
I ran this ~10 times, and it passed each time. The key fix is pausing for 30 seconds between running the daisy workflow and checking stackdriver.
=> Fix validate_cloud_logging test.

daisy_workflows/linux_common/utils/common.py
Over the weekend, our opensuse 15.1 tests [1] started failing. The root cause is that the Debian 10 worker was failing to install a dependency because it couldn't reach security.debian.org on its first attempt.
1. daisy_integration_tests/opensuse_15_1.wf.json
=> Retry apt-get update until a package is successfully installed.

daisy/resource.go, daisy/step_create_images_test.go, daisy/test_common_test.go
=> daisy: fix image IgnoreLicenseValidationIfForbidden

prowjobs_cloudbuild.yaml
=> build windows-upgrade test docker

test-infra/prow/config.yaml
=> [windows upgrade e2e] fix typo

daisy_workflows/image_build/windows_for_containers/windows-1903-core-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-1909-core-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-for-containers-uefi.wf.json
Add workflow files for builds of the following w/ UEFI firmware:
- Windows Server v1903
- Windows Server 2019 w/ desktop experience
=> Add Windows Containers w/ UEFI firmware

daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
* See the available versions of Docker here:
https://dockermsft.azureedge.net/dockercontainer/DockerMsftIndex.json
=> Update Docker version to latest

cli_tools/gce_windows_upgrade/upgrader/upgrader.go, cli_tools/gce_windows_upgrade/upgrader/utils.go, cli_tools/gce_windows_upgrade/upgrader/utils_test.go
As per feedback from tech writer team, we show the cleanup guide again after the upgrade succeeded.
=> [windows upgrade] show cleanup guide again when success

daisy_workflows/linux_common/utils/common.py
We've seen failed imports when the user sets 70-persistent-net.rules to immutable. This change clears the attribute prior to deleting the file.
- Observed error message: `rm_f: /etc/udev/rules.d/70-persistent-net.rules: Operation not permitted
- Previous related change: #1151
=> Clear immutable attr from 70-persistent-net.rules before deleting.

cli_tools/common/utils/flags/key_value_flag.go, cli_tools/common/utils/flags/key_value_flag_test.go, cli_tools/common/utils/flags/string_utils.go, cli_tools/common/utils/flags/string_utils_test.go, cli_tools/gce_vm_image_import/importer/args.go
moved implementations of flag.Value from image import into common utils
=> refactored flag value into common utils

cli_tools/gce_vm_image_import/importer/importer.go, cli_tools/gce_vm_image_import/importer/inflater.go, cli_tools/gce_vm_image_import/importer/source.go
Some minor cleanups:
- Remove extra lambda
- Remove unused struct variable
- Narrow scope of interface
=> Cleanup in cli_tools/gce_vm_image_import/importer.

daisy_workflows/image_import/ubuntu/translate.py
=> Check for /etc/resolvconf/resolv.conf.d/base before modifying it.

daisy_workflows/image_build/debian/build.py, daisy_workflows/image_build/debian/build_fai.py, daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json, daisy_workflows/image_build/enterprise_linux/export_metadata.py
Fix the error for PR https://github.com/GoogleCloudPlatform/compute-image-tools/commit/6a77267762f67473d7ddf0545ec8d602e24d8760
1 make export-metadata and save-build-logs in parallel
2 fix guest package name
=> Fix build failure

daisy/compute/compute.go
This is split from the https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1282/files?file-filters%5B%5D=.go
Since daisy is in a separate module, we need to split daisy-changes into a separate PR.
=> [new vmdk api adoption] daisy support new vmdk alpha API

go/e2e_test_utils/go.mod, go/e2e_test_utils/launcher.go
- Add a key value string as variables flag to E2E tests
=> Add variables flag to E2E tests

daisy_integration_tests/2012r2_vmware_translate.wf.json, daisy_integration_tests/2019_translate.wf.json, daisy_integration_tests/scripts/v2v_adapt.sh, daisy_integration_tests/v2v_adapt_e2e.test.gotmpl, daisy_integration_tests/v2v_adapt_windows.wf.json, daisy_integration_tests/v2v_adapt_windows_byol.wf.json, daisy_integration_tests/windows_10_x64_byol.wf.json, daisy_integration_tests/windows_7_x64_byol.wf.json, daisy_integration_tests/windows_8_x64_byol.wf.json, test-infra/prow/config.yaml
First batch of M4CE adaptation E2E tests which use existing Daisy translate tests. The tests added in this batch are succeeding adaptation but some are failing the testing phase. M4CE team is working actively on fixing these issues and running the tests will allow them to check the progress of their work.
=> First batch of M4CE adaptation E2E tests

cli_tools_e2e_test/gce_ovf_import/scripts/ovf_import_test_ubuntu_3_disks.sh
Bring 3-disk Ubuntu OVF import test verification script in line with post_translate_test.sh to fix flaky failures like unable to ping google.com
=> Update 3-disk Ubuntu OVF import test verification script

cli_tools_e2e_test/gce_ovf_import/scripts/ovf_import_test_windows_two_disks.ps1
Bring Windows 2-disk OVF import E2E test verification script in line with post_translate_test.ps1 (added OSConfigAgent check, re-tries for Windows activation)
=> Update Windows 2-disk OVF import E2E test verification script

daisy_workflows/image_build/debian/build.py, daisy_workflows/image_build/debian/build_fai.py, daisy_workflows/image_build/debian/debian.wf.json, daisy_workflows/image_build/debian/debian_10_fai.wf.json, daisy_workflows/image_build/debian/debian_10_worker.sh, daisy_workflows/image_build/debian/debian_10_worker.wf.json, daisy_workflows/image_build/debian/debian_9.wf.json, daisy_workflows/image_build/debian/debian_fai.wf.json, daisy_workflows/image_build/debian/debian_sid_fai.wf.json, daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json, daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
- Move image builds to use the Debian 10 worker image.
=> Open source Debian 10 worker image build.

cli_tools/gce_vm_image_import/importer/api_inflater_test.go, cli_tools/gce_vm_image_import/importer/inflater.go
=> Image import: Disable shadow VMDK inflation.

cli_tools/common/domain/interfaces.go, cli_tools/common/utils/flags/key_value_flag_test.go, cli_tools/common/utils/param/param_utils.go, cli_tools/common/utils/param/populator_test.go, cli_tools/common/utils/storage/scratch_bucket_creator.go, cli_tools/common/utils/storage/scratch_bucket_creator_test.go, cli_tools/mocks/mock_scratch_bucket_creator.go
Check if scratch bucket provided as a flag is in the same project, for image import and export.
=> Check if scratch bucket provided as a flag is in the same project

daisy_integration_tests/v2v_adapt_windows.wf.json, daisy_integration_tests/v2v_adapt_windows_byol.wf.json
Updated V2V adapt E2E test criteria to match the new V2V adaptation module output format.
=> Updated V2V adapt E2E test criteria

daisy_workflows/image_import/windows/translate.ps1
Prompted by an import of Windows 2012r2 where VMWare Tools failed to uninstall. 
- Imported an image that reproduced the problem:
- Confirmed new message: 'Translate: Unable to remove VMWare Tools. Consider manually removing.'
- Confirmed that the serial console logs included the msiexec logs
- Launched instance on GCE, connected with RDP
- Ran daisy_integration_tests/2012r2_vmware_translate.wf.json
=> Windows import: Continue when VMWare Tools fails to uninstall

cli_tools/common/distro/distro.go, cli_tools/common/distro/distro_test.go, cli_tools/gce_vm_image_import/importer/errors.go
This updates cli_tools/common/distro to support Windows.
=> distro.Release: Support Windows

cli_tools/gce_vm_image_import/importer/api_inflater.go, cli_tools/gce_vm_image_import/importer/inflater.go
Right now there are some shadow test error which we don't know the actual failure reason. Let's log the actual reason.
=> [VMDK API shadow test] log more info for shadow test err

daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/disk_export_ext.wf.json, daisy_workflows/export/image_export.wf.json, daisy_workflows/export/image_export_ext.wf.json, daisy_workflows/export_metadata/export_metadata.wf.json, daisy_workflows/image_import/debian/translate_debian.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_6.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_7.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_8.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_6_licensed.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json, daisy_workflows/image_import/import_image.wf.json, daisy_workflows/image_import/inflate_file.wf.json, daisy_workflows/image_import/inspection/boot-inspect.wf.json, daisy_workflows/image_import/suse/translate_suse.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
=> Move imports/exports to use debian-10-worker.

cli_tools/common/utils/daisy/daisy_utils.go, cli_tools/common/utils/daisy/daisy_utils_test.go, cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go, cli_tools/gce_vm_image_import/importer/api_inflater.go
@zmarano  is deprecating the Debian 9 worker.
=> Migrate cli_tools to use Debian 10 worker

daisy_workflows/image_import/windows/translate.ps1
Correcting the googet package name used to remove the GCE PowerShell googet package.
=> Correcting GCE PowerShell googet package name

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
Expected err msg needs to be fixed.
=> [small] fix import-without-permission e2e err msg

daisy_workflows/image_import/windows/translate.ps1
- Changing hibernate conditional logic to use Windows build number, 7601 and greater.
- Build numbers only increase in versions of windows. https://www.gaijin.at/en/infos/windows-version-numbers
- Moved $pn to $script:pn, so the product name can be reused throughout the script.
- Adding OS edition and version logging at start of script for easier debugging of issues.
=> Limiting hibernate to Win7/2008R2 SP1 and above.

daisy_integration_tests/scripts/post_translate_test.ps1, daisy_workflows/image_import/windows/translate.ps1
- Disabling hiberation via registry setting
-- If present the c:\hibernation.sys file will be removed on the next reboot.
=> Changing hibernation management to use direct registry modification

daisy_workflows/image_build/debian/debian_10_fai.wf.json
Includes change to enable fsck on the root fs.
=> Update Debian cloud build tools commit.

daisy_workflows/image_build/enterprise_linux/kickstart/centos-7-options.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/centos-8-options.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/centos-stream-8-options.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-options.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rhel-8-options.cfg
* The DHCP response includes the correct MTU settings and gets applied correctly on the interface.
* There were also duplicate entries for enabled IPv6 in EL7.
=> Remove unnecessary MTU settings.

cli_tools/gce_ovf_import/README.md, cli_tools/gce_vm_image_export/README.md, cli_tools/gce_vm_image_import/README.md, cli_tools/gce_vm_image_import/cli/args.go
Updated READMEs for image importer/exporter and OVF importer. Updated help text for a couple of args in image importer.
=> Updated READMEs for image importer/exporter and OVF importer.

daisy_workflows/image_import/windows/translate.ps1, daisy_workflows/image_import/windows/translate_bootstrap.ps1
Fixing powershell syntax issues
=> Fixing powershell syntax issues

cli_tools/common/utils/logging/service/logger.go, cli_tools/common/utils/logging/service/logger_test.go
`runWithServerLogging` executes a function, then logs the results. Prior to this, a panic would cause the application to crash. Following this PR, `runWithServerLogging` traps the panic and sends a "failure" message using the panic's details and a stack trace.
Follow-up from https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1497#discussion_r562353775
=> CLI logging: Trap panics in application code

cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go, daisy_workflows/ovf_import/create_gmi.wf.json
This is a follow-up to #1497 where we refactored instance import to use import modules.
=> Machine image import: Use import module for alpha and beta

daisy_workflows/image_build/enterprise_linux/kickstart/centos-7-options.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-options.cfg
Could conflict with the guest-agent host key generation.
=> Disable systemd ssh-keygen service on EL7.

cli_tools/gce_onestep_image_import/main.go
rename onestep import log prefix from [import-image-from-cloud] to [import-image-from-external-cloud]
=> [minor] rename onestep import log prefix

daisy_workflows/image_import/ubuntu/translate.py
Ubuntu's repositories recently switched to the new guest agent, causing some of our tests to fail with "gcloud: command not found". 
https://prow.k8s.io/view/gcs/compute-image-tools-test/logs/ci-images-import-export-cli-e2e-tests/1359769431500132352
The old guest agent's unit file included an `Environment` directive, which is missing from the NGA. This PR fixes the issue by patching the affected unit files. The alternative is to use a drop-in file, but that would persist after Canonical pushes a fix.
Ran the tests in cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go that were previously failing.
```
TranslateDebug: [/lib/systemd/system/google-shutdown-scripts.service] Checking whether /bin/snap is on PATH.
TranslateDebug: …
```
=> Ubuntu 18.04+ import: Add /snap/bin to service's path 

daisy_workflows/image_build/windows/README.md, daisy_workflows/image_build/windows/post_install.ps1, daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-10-20h2-ent-x86-bios-byol.wf.json, daisy_workflows/image_build/windows/windows-build-bios.wf.json, daisy_workflows/image_build/windows/windows-build-uefi.wf.json, daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json
- Migrate to using UEFI disk guest feature, which mean forking windows-build
- Remove bios builds of x64 OSes
- Add windows 10 32/64, 2012r2
=> Add win10/2012 builds. Remove most bios builds. Forking windows-build common wf.

daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-10-20h2-ent-x86-bios-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json
The change was lost by one of the previous commits.
=> Pass "pwsh" variable to windows-build workflow

cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go, cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
This promotes the changes in #1512 from Beta to GA.
=> OVF import: Use import module for GA

daisy_workflows/build-publish/linux_dev/centos_7_dev.wf.json, daisy_workflows/build-publish/linux_dev/centos_8_dev.wf.json, daisy_workflows/build-publish/linux_dev/debian_10_dev.wf.json, daisy_workflows/build-publish/linux_dev/debian_9_dev.wf.json, daisy_workflows/build-publish/linux_dev/development.wf.json, daisy_workflows/build-publish/linux_dev/rhel_7_metal_dev.wf.json, daisy_workflows/build-publish/linux_dev/rhel_8_metal_dev.wf.json, daisy_workflows/build-publish/linux_dev/ubuntu_1604_dev.wf.json, daisy_workflows/build-publish/linux_dev/ubuntu_1804_dev.wf.json
Using development.json instead directly use workflow in image_build
=> Bare metal dev

daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-10-20h2-ent-x86-bios-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json
- Updating image names to include byol
- Extending 2012r2 timeout and fixing edition string
=> Updating byol and 2012r2 workflows

daisy_workflows/image_build/windows/README.md
Updating windows image build docs
- Adding cloudsdk variable to examples/table
- Adding links when referring to external content
- Added specific local folder examples
=> Updating windows image build docs

daisy_workflows/image_build/windows/windows-server-2012r2-dc-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2012r2-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-sac-1909-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-sac-2004-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-sac-20h2-dc-core-uefi-payg.wf.json
- Adding Server Core and semi-annual channel builds
- Updating BYOL family to have a -byol suffix
- Fixed incorrect family names
=> Adding server core and SAC builds

daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2012-r2-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2019-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2019-dc.wf.json
Updating timeout to 100min for SQL 2017
=> Updating timeout to 100min for SQL 2017

daisy_workflows/export_metadata/export-metadata.py
Have RPM package version format match debian, containing epoch if present
Remove EL6 support
=> Rpm add epoch

daisy_workflows/image_build/sqlserver/sql_install.ps1
Adding Get-ResultCodeDescription to sql_install.ps1 for Install-WindowsUpdates cmdlet.
=> Adding Get-ResultCodeDescription to sql_install.ps1

cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go, cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater_test.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go, daisy_workflows/ovf_import/create_gmi.wf.json, daisy_workflows/ovf_import/create_instance.wf.json
OVF Import: switched disks to SSD (from standard) as that was the behavior before the big OVF import refactor.
=> OVF Import: switched disks to SSD (from standard) 

cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
OVF GMI import E2E tests: 
- Fixed storage location test by removing isWindows for a CentOS import. 
- Consolidated network related tests with existing OS related tests to reduce the total number of tests run while keeping the same coverage.
=> OVF GMI import E2E tests: a fix and consolidation

cli_tools/common/utils/daisy/daisy_utils.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_integration_tests/debian_10_translate.wf.json, daisy_workflows/image_import/debian/translate.py, daisy_workflows/image_import/debian/translate_debian_10.wf.json
This adds support for importing Debian 10 as an image, instance, or GMI.
=> Support importing Debian 10

daisy_workflows/build-publish/linux_dev/development.wf.json
[Daisy] Errors in one or more workflows:
rhel-7-metal-dev: error populating workflow: error populating step "build-bare-metal": unknown workflow Var "development" passed to IncludeWorkflow "build-bare-metal"
=> add optional var development

test-infra/prow/config.yaml
Increase number of instances per zone for unstable and staging tests
Increase timeouts for staging and stable tests
=> Update osconfig test configs

daisy/step_create_images.go, daisy/step_create_images_test.go
- Updated imageUsesAlphaFeatures logic to check each item for nil
- Added imageUsesAlphaFeatures specific tests
=> Updated imageUsesAlphaFeatures and added tests

daisy_workflows/image_import/windows/translate.ps1
Add detection and removal of read-only attribute from windows host file
=> Add detection and removal of read-only attribute from windows host file

daisy_workflows/image_build/install_package/install_package.wf.json, daisy_workflows/image_build/install_package/installpackage.py, daisy_workflows/linux_common/utils/common.py
new workflow and script to create a derivative image with a single package installed
packages are installed from gcs but with repositories available to satisfy dependencies
based on metadata export workflow
=> add install package wf

cli_tools_tests/go.mod, cli_tools_tests/go.sum
Updating cli_tools_tests dependencies to match daisy versions
=> Updating cli_tools_tests dependencies to match daisy versions

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
=> Image import: E2E tests for SLES 15.0 import

cli_tools/mocks/mock_compute_client.go, cli_tools/mocks/mock_resource_location_retriever.go, daisy/compute/compute.go, daisy/compute/compute_test.go, daisy/compute/test_client.go, daisy/image.go, daisy/image_test.go, daisy/step_create_images.go, daisy/step_create_images_test.go, daisy/step_deprecate_images.go, daisy/workflow_test.go
- Adding Alpha API support to the image create/deprecate processes
- This PR does not update any dependency
=> Adding Alpha API support to the image create/deprecate processes.

daisy_workflows/image_build/windows/post_install.ps1
Refactor `Generate-NativeImage` function to optimize all .Net apps.
=> Refactor Generate-NativeImage

daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg
There was a typo in previous PR https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1642
=> Fix el8 complete dnf cache remove command

daisy_workflows/build-publish/debian/debian_11.publish.json, daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json, daisy_workflows/build-publish/enterprise_linux/centos_7.publish.json, daisy_workflows/build-publish/enterprise_linux/centos_8.publish.json, daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_7.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
This reverts commit 619d9631785e62971e980e414f166f0061a20bee. Tests are not happy.
=> Revert "Add GVNIC flag to supported OS's. (#1658)"

cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_export/exporter/exporter_test.go
A common error is specifying a source image that doesn't exist. 
Given an invocation of `gcloud compute images export  --image the-image   --project the-project`, the error messages are:
* Old message: `[image-export] 2021/06/16 20:21:44 step "setup-disks" validation error: cannot create disk "disk-image-export": can't use image "projects/the-project/global/images/blahe": imageResourceDoesNotExist: projects/the-project/global/images/the-image does not exist`
* New message: `[image-export] 2021/06/16 13:22:59 Image "the-image" not found`
=> Image export: Improve error message when source image not found

daisy_workflows/build-publish/windows/windows-server-2004-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012r2-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012r2-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.wf.json
=> Fixing variable for cloud sdk

daisy_workflows/image_import/enterprise_linux/translate.py
A customer reported they had a CentOS 7 failed import where the machine didn't have `yum`, even though they used `--no-guest-environment`. This updates the EL logic to check whether `yum` is available prior to using it (for non-guest operations).
For testing, I created a CentOS 7 instance and then removed `yum`. I'm still brainstorming on how to make this an e2e test, since we typically depend on startup scripts. I'll leave that to a follow-up PR.
=> EL Import: Don't require yum

daisy_workflows/image_build/install_package/installpackage.py
Evidently installing RPMs in chroots doesn't just work, anymore. Relabel the filesystem using `setfiles`, which is the only relevant tool in the SELinux toolkit that can work in a chroot, without /selinux filesystem mounted. Generate a list of newly installed files and relabel them.
Tested working
=> correct selinux labels in chroot

cli_tools/common/imagefile/inspector_test.go
Recently we've had flaky tests in imagefile/inspector_test.go. For example:
```
imagefile: TestGCSInspector_StopMounting_IfContextCancelled 
inspector_test.go:175: gcsfuse returning mount failure    
inspector_test.go:175: gcsfuse returning mount failure     
inspector_test.go:94:
```
The tests assumed that they'd finish within 120ms. This PR removes that race condition by supplying a pre-cancelled context, and confirming that a retry isn't performed.
https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/GoogleCloudPlatform_compute-image-tools/1706/cli-tools-presubmit-gotest/1422291581582446592
=> CLI Tools: Remove race condition in gcsfuse test

daisy_workflows/image_build/debian/debian_10_worker.sh, daisy_workflows/linux_common/bootstrap.sh, daisy_workflows/linux_common/utils/common.py
Since bullseye, the suite names changed, apt-get asks for input to change the suite during update.
=> Fix Debian apt updates in builds.

cli_tools/gce_vm_image_export/README.md, cli_tools/gce_vm_image_export/exporter/exporter.go, cli_tools/gce_vm_image_export/exporter/exporter_test.go, cli_tools/gce_vm_image_export/main.go, daisy_workflows/export/export_disk_ext.sh, daisy_workflows/export/image_export_ext.wf.json
Reverts GoogleCloudPlatform/compute-image-tools#1664
=> Revert "Adding ability to export fixed-sized VHDs"

daisy_workflows/image_import/enterprise_linux/translate.py
This PR skips installation of the guest environment, gsutil, and gcloud for EL6. 
- Ran a RHEL8 e2e test
- Ran an import with CentOS 6; confirmed the error message, and confirmed that the instance booted:
```
StatusMatch found: "TranslateStatus: GCE packages are not supported for EL6. Skipping installation."
StatusMatch found: "TranslateStatus: Updating initramfs"
StatusMatch found: "TranslateStatus: Update grub configuration"
StatusMatch found: "TranslateStatus: Resetting network to DHCP for eth0."
StatusMatch found: "TranslateStatus: Removing udev 70-persistent-net.rules."
StatusMatch found: "TranslateStatus: Removing SSH host keys."
StatusMatch found: "TranslateStatus: Executing command: ['virt-customize', '-a', '/dev/sdb', '--selinux-relabel']"
SuccessMatch found "TranslateSuccess: …
```
=> EL6 import: Don't install guest packages

daisy_workflows/build-publish/sqlserver/sql-2012-enterprise-windows-2012-r2-dc.publish, daisy_workflows/build-publish/sqlserver/sql-2012-standard-windows-2012-r2-dc.publish, daisy_workflows/build-publish/sqlserver/sql-2012-web-windows-2012-r2-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2012-r2-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2016-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2014-standard-windows-2012-r2-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2014-web-windows-2012-r2-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2012-r2-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2016-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2019-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2012-r2-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2016-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2019-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2012-r2-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2016-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2019-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2016-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2019-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2012-r2-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2016-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2019-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2016-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2019-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2016-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2019-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2019-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2019-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2019-dc-uefi.publish
Adding SQL Server image publish workflows
=> Adding SQL Server image publish workflows

daisy_workflows/image_build/windows/windows-server-2022-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2022-dc-uefi-payg.wf.json
For the windows server 2022 builds.
=> Add windows server 2022 payg workflows

daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.wf.json
Wrapper build workflows and publish workflows
=> Add Win2022-build-publish-workflows

daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-sap-post.cfg
apparently without a trailing newline, this post fails. old ks/anaconda bug
=> newline in SAP post

daisy_workflows/image_import/ubuntu/translate.py
The e2e tests for Ubuntu 18 and newer are showing that the guest agent is not running when we run the startup script tests.
```
STATUS: Checking google-guest-agent
â—   google-guest-agent.service - Google Compute Engine Guest Agent
Loaded: loaded (/lib/systemd/system/google-guest-agent.service; enabled; vendor preset: enabled)
Active: inactive (dead)
STATUS: Checking google-osconfig-agent
â—   google-osconfig-agent.service - Google OSConfig Agent
Loaded: loaded (/lib/systemd/system/google-osconfig-agent.service; enabled; vendor preset: enabled)
Active: active (running) since Fri 2021-11-19 10:25:11 UTC; 44s ago
Main PID: 633 (google_osconfig)
Tasks: 13 (limit: 17904)
Memory: 24.3M
CGroup: /system.slice/google-osconfig-agent.service
â””â”€633 /usr/bin/google_osconfig_agent
```
This updates …
=> Ubuntu import: Add 99-disable-network-activation.cfg from official image

cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_import_e2e_common.go
This was prompted by [flaky e2e tests](https://oss-prow.knative.dev/view/gs/compute-image-tools-test/logs/ci-ovf-import-e2e-tests-daily/1463225589233094656) where we found that:
1. All `gcloud` tests were being invoked with `gcloud beta`
2. The console logs were not being retained from the instance after it was rebooted for running its post-translate test.
In addition, this fixes some small issues found by [staticcheck](https://staticcheck.io/).
=> OVF Import tests: Don't always use beta args; Retain console logs from test instances

daisy_workflows/build-publish/sqlserver/sql-2012-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2012-standard-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2012-web-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-standard-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-web-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2019-dc.wf.json
The 28 SQL server build workflows is part of the pipeline migration to Concourse.
/cc @bkatyl
=> Add sql workflows for the Guest OS pipeline migration

daisy_workflows/build-publish/sqlserver/sql-2012-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2012-standard-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2012-web-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-standard-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-web-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2019-dc.wf.json
It was missing `sqlserver` in the path.  Fixing `/jobs/build-sql-2012-enterprise-windows-2012-r2-dc/builds/4`.
/cc bkatyl
=> Fix sql workflow path

daisy_workflows/build-publish/sqlserver/sql-2012-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2012-standard-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2012-web-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-standard-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2014-web-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2012-r2-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2016-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2019-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2019-dc.wf.json
Update sql disk export destination. Addressing `jobs/build-sql-2012-enterprise-windows-2012-r2-dc/builds/8`.
/cc @bkatyl
=> Update sql disk export destination

daisy_workflows/image_build/windows/post_install.ps1
Add server 2022 to the VSS install regex so VSS is installed on Windows Server 2022
/cc bkatyl
=> Add server 2022 to the VSS install regex

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
=> Image Import e2e: add e2e test for sles sap 15sp3 unregistered

daisy_workflows/build-publish/windows/windows-server-2004-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2012r2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2012r2-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-2019-core-for-containers-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-2019-for-containers-uefi.publish.json
Update publish to staging projects to intended project.
/cc bkatyl
=> Update publish to staging projects

daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows_export.wf.json
Update Windows Server 2022 Export time to ~90~ 60 min.
/cc bkatyl
=> Update Windows Server 2022 Export time to 60 min

daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2022-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2022-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2022-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2022-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2022-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2022-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2022-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2022-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2022-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2022-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2022-dc-uefi.publish, daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2022-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2022-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2022-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2022-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2019-enterprise-windows-2022-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2019-standard-windows-2022-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2019-web-windows-2022-dc.wf.json
Add sql servers on Windows server 2022 build workflows
/cc bkatyl
=> Add sql servers on Windows server 2022 build workflows

cli_tools/common/image/importer/inflater.go, cli_tools/common/image/importer/inflater_test.go, cli_tools/gce_windows_upgrade/upgrader/upgrader.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
=> resolve TODO from tzz: remove out-of-date TODO or create trackers for them

cli_tools/go.mod, cli_tools_tests/go.mod
Need an additonal PR otherwise the common is still the old version
=> [build] update the dependency verison for cli_tools->common to consume the new common build file

daisy_workflows/image_build/sqlserver/configs/sql_server_2012.ini, daisy_workflows/image_build/sqlserver/configs/sql_server_2012_core.ini, daisy_workflows/image_build/sqlserver/configs/sql_server_2014.ini, daisy_workflows/image_build/sqlserver/configs/sql_server_2014_core.ini, daisy_workflows/image_build/sqlserver/configs/sql_server_2016.ini, daisy_workflows/image_build/sqlserver/configs/sql_server_2016_core.ini, daisy_workflows/image_build/sqlserver/configs/sql_server_2017.ini, daisy_workflows/image_build/sqlserver/configs/sql_server_2017_core.ini, daisy_workflows/image_build/sqlserver/configs/sql_server_2019.ini
Users --> BUILTIN\ADMINISTRATORS
=> Users --> BUILTIN\ADMINISTRATORS

rollout/cli_tools_cloudbuild_build.yaml
Grant permission after build. Enable the command which was commented out.
=> [build] grant permission after build

daisy_workflows/build-publish/rhui/rhua_artifacts/answers.yaml
we don't use these values but if they're not in the file, ansible crashes
=> add new vals to rhua answers

daisy_integration_tests/scripts/post_translate_test.ps1, daisy_workflows/image_import/windows/translate.ps1
We disable power saving in Windows on GCP: it causes the web UI's power button to _wakeup_ the Windows instance.  In Windows 10, we skipped this step since it caused translation to timeout (#1482, #1869).
On further investigation, I found that each call to `Get-CimAssociatedInstance -ResultClassName 'Win32_PowerSetting'` was slow on Windows 10--on the order of seconds--and there were over 1600 such calls.
To avoid this, this PR inverts the search: it finds the single power setting that we need, and then finds the subset of indexes that need to be toggled. It completes in less than a second.
- There was an existing Windows 10 x86 test that failed using the previous query. With the new query, it passes.
- Updated the Windows post-translate tests to verify that "Turn off display after" is …
=> Windows 10 import: Disable power savings

daisy_integration_tests/scripts/post_translate_test.ps1, daisy_workflows/image_import/windows/translate.ps1
https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1870 caused test failures for Windows 7 and 2008r2: `Get-CimInstance' is not recognized as the name of a cmdl` [1]
While researching that failure, I found that older versions of Windows weren't having their power settings updated.  This PR switches to use `WMI` instead of `Cmi`, which is supported across all of versions of Windows that we support for import.
The new `try/catch` maintains the [old behavior](https://github.com/EricEdens/compute-image-tools/blob/v20190711/daisy_workflows/image_import/windows/translate.ps1#L154-L156) of where we skip configuring power if there's a powershell issue with querying the power settings; I ran into this issue with the `inspect-uefi-windows-uefi` test image which doesn't allow this …
=> Windows import: Support power settings for 7 and 2008r2

daisy_workflows/build-publish/rhui/cds_artifacts/cds.patch, daisy_workflows/build-publish/rhui/install_cds.sh
update patch to reflect changes made to the ansible template upstream, mainly moves
=> Update cds ansible template

daisy_workflows/build-publish/rhui/cds.publish.json, daisy_workflows/build-publish/rhui/rhua.publish.json
add a 'test' env for rhui images for the pre-release period
=> add test env for rhui image publish

daisy_workflows/build-publish/enterprise_linux/rocky_linux_optimized_gcp_8.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_optimized_gcp_8.wf.json, daisy_workflows/build-publish/rhui/cds.publish.json, daisy_workflows/build-publish/rhui/rhua.publish.json, daisy_workflows/image_build/enterprise_linux/kickstart/rocky-linux-optimized-gcp-8-options.cfg, daisy_workflows/image_build/enterprise_linux/ks_helpers.py, daisy_workflows/image_build/enterprise_linux/rocky_linux_optimized_gcp_8.wf.json
clone of rocky 8 with SIG kernel repo
also fix rhui publications; remove alpha access requirement
=> add rocky linux optimized for gcp

daisy_workflows/build-publish/rhui/cds_artifacts/rhui-health-check.service, daisy_workflows/build-publish/rhui/health_check.py, daisy_workflows/build-publish/rhui/rhua_artifacts/rhui-health-check.service
update service to match changes to health check
=> rhui health check service change

daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-10-20h2-ent-x86-bios-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2012-r2-dc-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2012-r2-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2012-r2-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2012-r2-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2022-dc-core-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-server-2022-dc-core-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-2022-dc-uefi-payg.wf.json, daisy_workflows/image_build/windows/windows-server-sac-20h2-dc-core-uefi-payg.wf.json
Updating Driver Bucket to StorNVMe from NVMe Community driver
=> Updating Driver Bucket to StorNVMe from NVMe Community driver

daisy_workflows/build-publish/rhui/cds_artifacts/cds.patch, daisy_workflows/build-publish/rhui/install_cds.sh
Remove the CDS to RHUA fallback, which doesn't work and causes all 404s to timeout
Tested config change on active CDS node, and tested build change with Daisy.
=> remove cds to rhua dependency

daisy_workflows/build-publish/enterprise_linux/rhel_9.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/el9-post.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rhel-9-options.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rhel9-post.cfg, daisy_workflows/image_build/enterprise_linux/ks_helpers.py, daisy_workflows/image_build/enterprise_linux/rhel_9.wf.json
RHEL 9 build:
need to do some shell game with packages and repo metadata as the versions of package tools on the build ISO and the versions present later in the build process differ in their behavior. also needed to force regeneration of boot loader entries due to some issue in the kernel package triggers that ignore our grub environment.
=> RHEL 9 build

daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-uefi.publish.json
Adding internal environment and associated licenses to daisy publish files
=> Add internal env and associated licenses to windows daisy builds

daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-uefi.publish.json
Resolves formatting error in core images only.
=> Fix syntax in publish file for core images

daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
Enable installing the OSConfig agent on Debian 11 ARM
=> install osconfig on arm

daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-uefi.publish.json
=> Update URIs to publish project for internal

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-10-21h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-81-ent-x64-uefi.wf.json
Adds windows 8.1 and 10 21h2 to daisy workflows.
=> Add daisy workflows for Win8.1 and 10

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json
Adds publish files for Windows 8.1 and 10 21h2.
=> Add publish files for Win8.1 and 10

daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/build_installer.py, daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_arm64.cfg, daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json
=> Rocky Linux 8 Optimized for GCP ARM64.

daisy_workflows/image_build/install_package/installpackage.py
was previously trying to do a targeted relabel of modified files, but apparently larger numbers of files can be modified.
=> installpackage.py: relabel whole fs

daisy_workflows/build-publish/partner/opensuse_leap_15_arm64.publish.json, daisy_workflows/build-publish/partner/opensuse_leap_15_arm64_export.wf.json, daisy_workflows/build-publish/partner/sles_15_arm64.publish.json, daisy_workflows/build-publish/partner/sles_15_arm64_export.wf.json, daisy_workflows/build-publish/partner/ubuntu_1804_arm64.publish.json, daisy_workflows/build-publish/partner/ubuntu_1804_arm64_export.wf.json, daisy_workflows/build-publish/partner/ubuntu_2004_arm64.publish.json, daisy_workflows/build-publish/partner/ubuntu_2004_arm64_export.wf.json, daisy_workflows/build-publish/partner/ubuntu_2204.publish.json, daisy_workflows/build-publish/partner/ubuntu_2204_arm64.publish.json, daisy_workflows/build-publish/partner/ubuntu_2204_arm64_export.wf.json, daisy_workflows/build-publish/partner/ubuntu_2204_export.wf.json
* add arm64 variants for partner export workflows
* add ubuntu 2204 for x86_64 and arm64
=> add arm64 partner exports

daisy_workflows/build-publish/partner/opensuse_leap_15_arm64.publish.json
add missing comma to opensuse leap arm64 publish workflow
=> fix typo in partner publish wf

daisy_workflows/build-publish/sqlserver/sql-2022-preview-windows-2022-dc.wf.json
Reverts GoogleCloudPlatform/compute-image-tools#1993
=> Revert "Renaming SSMS variable in SQL 22 publish file"

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2004-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json, daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json
- Yes, we use the oslogin project for a worker because of ACLs.
- This goes away when Alesksei's team takes over staging publication.
=> Change windows staging publish.

daisy_workflows/build-publish/kokoro/build.sh, daisy_workflows/build-publish/kokoro/kokoro.wf.json
add kokoro build workflow to build-publish dir. no corresponding 'public' workflows in image_build are needed.
=> kokoro build workflow

daisy_workflows/build-publish/sqlserver/sql-2022-preview-windows-2022-dc-uefi.publish.json
Resolves unexpected EOF since some parts were missing.
=> Fix logic in environment conditional

cli_tools/diagnostics/rdp_status.ps1, daisy_workflows/image_build/windows_for_containers/container_image_install.ps1, image_test/configuration/windows/test_config.ps1
Reverts GoogleCloudPlatform/compute-image-tools#1985
=> Revert "Support windows MTU 1500"

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json
Adds prod environment to reflect changes being made in the build pipeline. Remove staging environment as it was deprecated.
=> Update publish files for client builds

daisy_workflows/build-publish/enterprise_linux/almalinux_9.wf.json, daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/export_disk.sh, daisy_workflows/export/export_sbom.sh, image_test/sbom/README.md, image_test/sbom/enterprise_sbom_test.wf.json, image_test/sbom/test_sbom_export.sh
First pass at SBOM generation in almalinux 9.
=> Almalinux sbom changes and test

OWNERS
Add koln67 to owners so reviewers can LGTM to merge, instead of needing to both LGTM and Approve.
=> Add Anthony to owners

daisy_workflows/build-publish/windows/windows-server-2019-core-uefi.publish.json
=> Correcting family name

daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_7_9_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_4_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_6_sap.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json
Add SBOM generation support for remaining distributions in Rhel and Rocky Linux
=> rhel SBOM generation excluding rhel9

daisy_workflows/build-publish/windows_container/windows-2019-dc-core-for-containers-uefi.wf.json, daisy_workflows/build-publish/windows_container/windows-2019-dc-for-containers-uefi.wf.json
Fixing Windows Container build typo
=> Fixing Windows Container build typo

daisy_workflows/kernel_commit_query/kernel_commit_query.wf.json
We got a syntax error on the file.
=> kernel commit query: fix workflow json file

daisy_workflows/export/export_disk.sh, daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json
Incorrect variable name for sbom generation, minor fix.
=> Fix bug with disk export sbom generation naming

daisy_workflows/kernel_commit_query/debian.sh, daisy_workflows/kernel_commit_query/kcq.py, daisy_workflows/kernel_commit_query/kernel_commit_query.wf.json
Install python3-request package and redirect kernel package source extraction stdout and stderr to /dev/null to reduce serial streaming.
=> kernel commit query: debian: install python3 requests

daisy_workflows/build-publish/enterprise_linux/almalinux_9.wf.json, daisy_workflows/build-publish/enterprise_linux/centos_stream_9.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_9.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.wf.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_arm64.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.wf.json
=> EL9 sbom support

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi-byol.publish.json, daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi-byol.wf.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi-byol.publish.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi-byol.wf.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi-byol.publish.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-10-21h2-ent-x64-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-11-21h2-ent-x64-uefi-byol.wf.json, daisy_workflows/image_build/windows/windows-81-ent-x64-uefi-byol.wf.json
Clarifying that these are byol images. No changes to actual workflows.
=> Add -byol to Windows client build workflow names

daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/export_disk.sh
Include export of ${NAME}.sbom.json to the final destination.
=> sbom final destination

daisy_workflows/export_metadata/export-metadata.py
The current implementation assumes a given partition layout and a fixed block device enumeration, this patch introduces a lookup logic looking for a partition based on its guuid.
=> export metadata: fix root fs lookup

daisy_workflows/build-publish/windows_container/windows-2019-dc-core-for-containers-ce-uefi.wf.json, daisy_workflows/build-publish/windows_container/windows-2019-dc-for-containers-ce-uefi.wf.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-ce-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-ce-uefi.publish.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-ce-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-ce-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers.wf.json
Fixes naming issue with putting -ce after -uefi
=> Update CE docker build workflows

daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-ce-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-uefi.wf.json
=> Update sources name for startup script

daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-ce-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-uefi.wf.json
Updating the right file this time.
=> Update CE build file

daisy_workflows/image_build/windows_for_containers/container_image_install_ce.ps1
Uses the script Microsoft provides for installing the Docker CE instead:
https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1
=> Swap manual CE install steps for MS provided

daisy_workflows/image_build/windows_for_containers/container_image_install_ce.ps1
Moves binaries to own folder and places LICENSE.TXT in the same directory, then updates system path to point to the new location
=> Update Docker image CE install for licenses

daisy_workflows/build-publish/enterprise_linux/almalinux_9_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/almalinux_9_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/almalinux_9_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/almalinux_9_arm64.cfg
This PR adds build and publish support for AlmaLinux 9 for ARM64.
Based on RHEL9 and Rocky9 for ARM64 configurations.
=> AlmaLinux 9 for ARM64

daisy_workflows/build-publish/windows_container/windows-server-2019-core-for-containers-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-ce-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-ce-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-uefi.publish.json, daisy_workflows/build-publish/windows_container/windows-server-2019-for-containers-uefi.publish.json, daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-ce-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-ce-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-for-containers.wf.json
Updates the licenses in the Daisy workflows to reflect a fork to Mirantis and Docker CE builds.
=> Update licenses in Windows Container build workflows

daisy_workflows/image_build/windows_for_containers/container_image_install.ps1, daisy_workflows/image_build/windows_for_containers/container_image_install_ce.ps1
Makes necessary changes for Mirantis and Docker CE container image install scripts
=> Update Docker install scripts for Container images

daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
Removes a block that was left in for testing but actually results in an error and is actually a repeat block.
=> Fix container_install.ps1

daisy_workflows/image_build/windows_for_containers/container_image_install.ps1, daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-uefi.wf.json, daisy_workflows/image_build/windows_for_containers/windows-2019-for-containers-uefi.wf.json
Adds steps to image build for Windows Server for containers workflows to include Mirantis license information
=> Update container build workflows and script for Mirantis license

daisy_workflows/export/export_disk.sh
Ensure that sbomutil is working through logging statements
=> Add logging for sbomutil export

daisy_workflows/export/export_disk.sh
Log the root to ensure the right value was passed in from other workflows/builds.
=> Add log for sbom util root

daisy_workflows/export/export_disk.sh
Investigate whether gsutil ls returned an error.
=> Debug gsutil ls

daisy_workflows/export/export_disk.sh
Echo the input arguments to gsutil ls for the sbomutil program versions.
=> Echo the list repositories command input

daisy_workflows/export/export_disk.sh
Remove debugging printline statements
=> remove unnecessary echo

daisy_workflows/image_build/windows/bootstrap_install.ps1
This patch introduces the required bits to download sbomutil, generate the image's sbom and upload it to a given gcs path. Sbom generation is optional for now so we implemented checks and guardrails around required artifacts/conditions to generate sbom.
=> sbom: add required code to generate sboms for windows

daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json
Fix presubmit by removing syft_source
=> Remove unnecessary variable from presubmit

daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2012-r2.wf.json, daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/sqlserver/sql-2014-enterprise-windows-2012-r2.wf.json, daisy_workflows/image_build/sqlserver/sqlserver.wf.json, daisy_workflows/image_build/windows/windows-10-21h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-build-uefi.wf.json
SBOM util is already being fetched on the bootstrap script, pass in the sbom destination for sbom generation.
=> add windows sbom gen on ps1 uefi script

daisy_workflows/image_build/windows/bootstrap_install.ps1
GSPath had an extra /windows in it
=> Fix gspath

daisy_workflows/image_build/windows/bootstrap_install.ps1
Windows executables must end in exe
=> Use sbomutil.exe instead of sbomutil on windows

daisy_workflows/image_build/windows/bootstrap_install.ps1
comp_name is a required argument for sbomutil
=> Pass in component name for windows sboms

daisy_workflows/image_build/sqlserver/sql_install.ps1, daisy_workflows/image_build/sqlserver/sqlserver.wf.json
Modify the script to have the ability to generate sboms for sql server images, just like for windows other images
=> Add skeleton for sql sbom generation

daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2016-dc.wf.json, daisy_workflows/image_build/sqlserver/sql_install.ps1, daisy_workflows/image_build/sqlserver/sqlserver.wf.json
Make changes in one sql server workflow for sbom generation
=> 2016 sql server sbom generation

daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2016-dc.wf.json
Fix variable syntax error with img_family, which is used as the component name field in the sql server sbom.
=> Add dollar sign

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2016-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2019-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2022-uefi.wf.json
Pass in the variable to generate sboms on windows
=> Generate windows sboms

daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.wf.json, daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.wf.json
small number of workflows did not pass in the sbom destination name
=> Fix bug with sbom destination name

daisy_workflows/image_build/sqlserver/sql_install.ps1
Add extra content all in one sbom directory for sql images
=> download extra content for sql server sboms

daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json, daisy_workflows/sbom_validation/test_sbom_export.sh, daisy_workflows/sbom_validation/windows_sbom_validation.wf.json
Add a workflow which can be used as a presubmit for windows sbom generation validation.
=> Add windows sbom validation workflow

daisy_workflows/build-publish/windows/windows-10-21h2-ent-x86-bios.publish.json, daisy_workflows/build-publish/windows/windows-10-21h2-ent-x86-bios.wf.json, daisy_workflows/build-publish/windows/windows-10-22h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-10-22h2-ent-x64-uefi.wf.json, daisy_workflows/build-publish/windows/windows-10-22h2-ent-x86-bios.publish.json, daisy_workflows/build-publish/windows/windows-10-22h2-ent-x86-bios.wf.json
Adds 32 and 64 bit publish workflows to be used with Concourse
=> Create publish workflows for W10 22h2 and 21h2

daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-bios.publish.json, daisy_workflows/build-publish/windows/windows-server-2016-dc-bios.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-bios.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-bios.publish.json, daisy_workflows/image_build/windows/windows-server-2012-r2-dc-bios.wf.json, daisy_workflows/image_build/windows/windows-server-2016-dc-bios.wf.json, daisy_workflows/image_build/windows/windows-server-2019-dc-bios.wf.json, daisy_workflows/image_build/windows/windows-server-2022-dc-bios.wf.json
This would be consistent with how the UEFI workflows are named
=> Use BIOS for naming instead of MBR (Windows Server builds)

daisy_workflows/image_build/debian/build_fai.py
https://salsa.debian.org/cloud-team/debian-cloud-images/-/tree/732707480b4c6a5174066a9d4d5a7b0c05ab0fb1
=> Update Debian built to include intel_iommu change

daisy_workflows/image_build/enterprise_linux/centos_7_predictable_nic.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/centos_7_predictable_nic.cfg
Publish workflows intentionally missing.
/cc @zmarano @koln67
=> Add an image build workflow for centos 7 with predictable NIC names

daisy_workflows/build-publish/enterprise_linux/centos_7_predictable_nic.publish.json
=> Fix centos-7-predictable-nic publish template name

daisy_workflows/image_build/windows/post_install.ps1
- Migrating all netsh commands to PowerShell for win10/2016 and above
- Adding Firewall allow rule for IPv6 echo request
- Limiting Setting DNS Server assignment from DHCP to only be for 2008 as should not be needed by newer operating systems.
=> Migrating all netsh commands to PowerShell for win10/2016 and above

daisy_workflows/image_build/windows/post_install.ps1
Fixing copy/pasta error between scripts
Write-Log --> Write-Host
=> Fixing copy/pasta error between scripts

daisy_workflows/image_build/windows/post_install.ps1
=> Workaround for PS Module Path

daisy_workflows/build-publish/enterprise_linux/rhel_9_c3m.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_c3m.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_c3m.cfg, daisy_workflows/image_build/enterprise_linux/rhel_9_c3m.wf.json
=> RHEL9 for C3M

daisy_workflows/image_build/windows/post_install.ps1
Reverts GoogleCloudPlatform/compute-image-tools#2273
=> Revert "Moving to install drivers first"

daisy_workflows/build-publish/debian/debian_12.publish.json
=> Tag debian 12 with SEV_SNP_CAPABLE and SEV_LIVE_MIGRATABLE_V2

daisy_workflows/build-publish/bare_metal/ubuntu2004_c3metal.publish.json, daisy_workflows/build-publish/bare_metal/ubuntu2004_c3metal.wf.json, daisy_workflows/build-publish/bare_metal/ubuntu2204_c3metal.publish.json, daisy_workflows/build-publish/bare_metal/ubuntu2204_c3metal.wf.json, daisy_workflows/image_build/bare_metal/build_installer.py, daisy_workflows/image_build/bare_metal/c3metal-centos_stream_9.wf.json, daisy_workflows/image_build/bare_metal/c3metal-ubuntu.wf.json, daisy_workflows/image_build/bare_metal/c3metal-ubuntu_preparer.sh, daisy_workflows/image_build/bare_metal/enterprise_linux.wf.json, daisy_workflows/image_build/bare_metal/kickstart/centos_stream_9.cfg
Add c3 baremetal preview daisy workflows for ubuntu and centos stream 9
=> Add c3 baremetal preview daisy workflows for ubuntu and centos stream 9

daisy_workflows/image_build/windows/post_install.ps1
This is to address windows 11 falling sleep
=> Setting to High Performance Power Profile

daisy_workflows/image_build/windows/windows-build-bios.wf.json, daisy_workflows/image_build/windows/windows-build-uefi.wf.json
Enable display adapter on all Windows builds
=> Enable display adapter on all Windows builds

daisy_workflows/image_build/windows/post_install.ps1
Adding force in case it already exists
=> Adding force in case it already exists

daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.publish.json
Add IDPF to guest_features for Rocky 9
=> Update rocky_linux_9.publish.json to add IDPF

daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_2_sap.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_2_sap_byos.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.publish.json
/cc @zmarano @elicriffield 
/hold
=> Tag rhel 9.2 with SEV_LIVE_MIGRATABLE and SEV_LIVE_MIGRATABLE_V2

daisy_workflows/image_build/windows/post_install.ps1
=> Trigger Microsoft Edge Update

daisy_workflows/build-publish/windows/windows-server-2016-dc-bios.publish.json, daisy_workflows/build-publish/windows/windows-server-2019-dc-bios.publish.json, daisy_workflows/build-publish/windows/windows-server-2022-dc-bios.publish.json
=> Remove UEFI_COMPATIBLE feature from windows bios images

daisy_workflows/image_build/windows/post_install.ps1
Adding MicrosoftEdgeUpdateTaskMachineUA task trigger
=> Adding MicrosoftEdgeUpdateTaskMachineUA task trigger

daisy_workflows/image_build/windows/post_install.ps1
Disabling hibernate to prevent Hybrid Sleep
=> Disabling hibernate to prevent Hybrid Sleep

daisy_workflows/image_build/enterprise_linux/rhel_9.wf.json, daisy_workflows/image_build/enterprise_linux/rhel_9_byos.wf.json
Add IDPF to RHEL 9 workflows in image_build
=> Add IDPF to RHEL 9 workflows in image_build

daisy_workflows/build-publish/debian/debian_12.publish.json
=> Remove SEV_SNP_CAPABLE from Debian 12

daisy_workflows/build-publish/sqlserver/sql-2022-enterprise-windows-2025-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2022-enterprise-windows-2025-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2022-standard-windows-2025-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2022-standard-windows-2025-dc.wf.json, daisy_workflows/build-publish/sqlserver/sql-2022-web-windows-2025-dc-uefi.publish.json, daisy_workflows/build-publish/sqlserver/sql-2022-web-windows-2025-dc.wf.json, daisy_workflows/build-publish/windows/windows-11-24h2-ent-x64-uefi.publish.json, daisy_workflows/build-publish/windows/windows-11-24h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-enterprise-windows-2025-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-standard-windows-2025-dc.wf.json, daisy_workflows/image_build/sqlserver/sql-2022-web-windows-2025-dc.wf.json, daisy_workflows/image_build/windows/windows-11-22h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-11-24h2-ent-x64-uefi.wf.json, daisy_workflows/image_build/windows/windows-build-uefi.wf.json
- Win11 24h2 preview build
- Using n2d for Win11 22h2-24h2 and support OS level machine family decision
- SQL 2022 on Windows Server 2025 Preview
=> Win11 & SQL 2022 on Win2025

daisy_workflows/image_build/windows/post_install.ps1
Add Server 2025 to VSS allowlist
=> Add Server 2025 to VSS allowlist

daisy_workflows/build-publish/enterprise_linux/rhel_8_8_sap.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_8_8_sap_byos.publish.json
=> Tag rhel 8.8 with SEV_LIVE_MIGRATABLE_V2

daisy_workflows/build-publish/enterprise_linux/centos_stream_9.publish.json
=> Drop SEV_SNP_CAPABLE from centos-stream-9 images

daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1064235
Note: we need to re-merge our FAI config with the upstream project but much has changed.
=> Fix Debian 12 DNS resolution issues

daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.publish.json
Update almalinux-8 & rocky-linux-9 to add IDPF
=> Update almalinux-8 & rocky-linux-9 to add IDPF

daisy_workflows/image_build/windows/post_install.ps1
Chose 2 months as a general flag between old and new.
=> Update Edge update logic to wait until it finds a newer version

daisy_workflows/build-publish/enterprise_linux/centos_stream_9.publish.json
This reverts commit 2656f0fb4ba1c110436d9889aa5833956219ba1a.
/cc @zmarano @elicriffield
=> Revert "Drop SEV_SNP_CAPABLE from centos-stream-9 images (#2325)"

daisy_workflows/build-publish/debian/debian_11.publish.json
=> Drop SEV_CAPABLE from Debian 11

daisy_workflows/image_build/windows/post_install.ps1
Update post_install.ps1 to detect edge on Server2025 since they changed to scheduled task names
=> Update post_install.ps1 to detect edge on Server2025

daisy_workflows/build-publish/accelerator_images/ubuntu/ubuntu-2204-with-nvidia-550.publish.json, daisy_workflows/build-publish/accelerator_images/ubuntu/ubuntu-2204-with-nvidia-550.wf.json, daisy_workflows/build-publish/accelerator_images/ubuntu/ubuntu-2404-with-nvidia-550.publish.json, daisy_workflows/build-publish/accelerator_images/ubuntu/ubuntu-2404-with-nvidia-550.wf.json, daisy_workflows/image_build/accelerator_images/ubuntu/build-ubuntu-2204-accelerated.sh, daisy_workflows/image_build/accelerator_images/ubuntu/build-ubuntu-2404-accelerated.sh, daisy_workflows/image_build/accelerator_images/ubuntu/ubuntu-2404-with-nvidia-550.json, daisy_workflows/image_build/accelerator_images/ubuntu/ubuntu-accelerated.json
=> Create Ubuntu 22.04 and 24.04 accelerator prototype image workflows

daisy_workflows/build-publish/accelerator_images/ubuntu/ubuntu-2204-with-nvidia-550.publish.json, daisy_workflows/build-publish/accelerator_images/ubuntu/ubuntu-2404-with-nvidia-550.publish.json
Reflects project that is actually being created
=> Updating publish project name

daisy_workflows/build-publish/accelerator_images/ubuntu_2204_with_nvidia_550.wf.json, daisy_workflows/build-publish/accelerator_images/ubuntu_2404_with_nvidia_550.wf.json
=> Fix file paths in publish files

daisy_workflows/image_build/accelerator_images/ubuntu_2204_with_nvidia_550.wf.json, daisy_workflows/image_build/accelerator_images/ubuntu_2404_with_nvidia_550.wf.json
One more reference to update on accelerator install path.
=> Updating file paths

daisy_workflows/build-publish/accelerator_images/ubuntu_2404_with_nvidia_550.publish.json, daisy_workflows/image_build/accelerator_images/ubuntu_2204_with_nvidia_550.wf.json, daisy_workflows/image_build/accelerator_images/ubuntu_2404_with_nvidia_550.wf.json
Matching names so the resources are all in agreement.
=> Update image paths and project name in 2404

daisy_workflows/build-publish/accelerator_images/ubuntu_2204_with_nvidia_550.publish.json
=> Fix publish project for 2204 accelerator

daisy_workflows/build-publish/debian/debian_12_worker.publish.json, daisy_workflows/build-publish/debian/debian_12_worker_arm64.publish.json
=> Update Debian 12 worker licensing

daisy_workflows/build-publish/enterprise_linux/almalinux_9.publish.json, daisy_workflows/build-publish/enterprise_linux/centos_stream_9.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_4_sap.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_4_sap_byos.publish.json, daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.publish.json
/hold
/cc @elicriffield @bkatyl
=> Add TDX_CAPABLE to enterprise linux

daisy_workflows/image_build/accelerator_images/build_ubuntu_2204_accelerated.sh, daisy_workflows/image_build/accelerator_images/build_ubuntu_2404_accelerated.sh
=> Add a script to enable nvidia repos on ubuntu

daisy_workflows/image_build/accelerator_images/build_ubuntu_2204_accelerated.sh, daisy_workflows/image_build/accelerator_images/build_ubuntu_2404_accelerated.sh
=> Include mlx5_ib in ubuntu accelerators

daisy_workflows/image_build/accelerator_images/build_ubuntu_2204_accelerated.sh, daisy_workflows/image_build/accelerator_images/build_ubuntu_2404_accelerated.sh, daisy_workflows/image_build/accelerator_images/rocky_linux_8_optimized_gcp_with_nvidia_550.wf.json, daisy_workflows/image_build/accelerator_images/rocky_linux_9_optimized_gcp_with_nvidia_550.wf.json
* Add -y to apt command added to ubuntu
* Fix image name reference in Rocky
=> Fix build errors in accelerator images

daisy_workflows/image_build/accelerator_images/rocky_accelerated.wf.json
=> Fix install script path

daisy_workflows/image_build/accelerator_images/build_ubuntu_2204_accelerated.sh, daisy_workflows/image_build/accelerator_images/build_ubuntu_2404_accelerated.sh
=> Install ubuntu-drivers-common and the precompiled nvidia driver.

daisy_workflows/image_build/accelerator_images/build_ubuntu_2204_accelerated.sh, daisy_workflows/image_build/accelerator_images/build_ubuntu_2404_accelerated.sh
=> Drop ubuntu-drivers-common, include nvidia-utils in accelerator images

daisy_workflows/image_build/enterprise_linux/build_installer_arm64-64.py, daisy_workflows/image_build/enterprise_linux/enterprise_linux_arm64_64.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_arm64.cfg, daisy_workflows/image_build/enterprise_linux/rhel_8_arm64.wf.json
TODO:
* build_installer.py should just check for disk types, instead of a separate script
* and enterprise_linux.wf.json should extract the variables that change to there scripts and it can stay generic for everything
=> Initial commit of rhel8-arm64 images, not complete

daisy_workflows/image_build/accelerator_images/build_rocky_linux_8_optimized_gcp_accelerated.sh, daisy_workflows/image_build/accelerator_images/build_rocky_linux_9_optimized_gcp_accelerated.sh
=> Fix kernel source path in accelerator scripts

daisy_workflows/image_build/accelerator_images/build_ubuntu_2204_accelerated.sh, daisy_workflows/image_build/accelerator_images/build_ubuntu_2404_accelerated.sh
=> Use open drivers and modules-extra metapackages on ubuntu accelerators

daisy_workflows/image_build/accelerator_images/build_ubuntu_2404_accelerated.sh
=> Fix misspelling of linux-modules-extra-gcp

daisy_workflows/image_build/install_package/installpackage.py
/cc @ChaitanyaKulkarni28 @dorileo @drewhli
=> Resolve dependencies when building derivative images with installpackage

daisy_workflows/build-publish/enterprise_linux/centos_stream_9_arm64.publish.json, daisy_workflows/build-publish/enterprise_linux/centos_stream_9_arm64.wf.json, daisy_workflows/image_build/debian/debian_12_arm64.wf.json, daisy_workflows/image_build/debian/debian_fai.wf.json, daisy_workflows/image_build/enterprise_linux/centos_stream_9_arm64.wf.json, daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_9_arm64.cfg
- Move Debian to use the Debian 12 worker as well.
=> Fix aarch64 builds and add CentOS Stream 9 aarch64 build.

daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_latest.wf.json
=> Fix image family in rocky EL build

daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_latest.wf.json
Remove errant bracket pasted in
=> Fix rocky 8 accelerated image family

daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_accelerator.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_accelerator.cfg
=> Use persistent NIC names for accelerator images

daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_accelerator.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_accelerator.cfg
=> Fix rocky accelerator package names

daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_accelerator.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_accelerator.cfg
=> Use packages for repo configuration instead of writing it manually

daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.publish.json
=> Update Rocky accelerators with prod publish configuration

daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_550.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_550.wf.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.wf.json, daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_accelerator_550.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_accelerator_550.cfg, daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_550.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.wf.json
=> Add workflows for Rocky Linux 8 and 9 with Nvidia 550

cli_tools/gce_image_publish/publish/publish.go, cli_tools/gce_image_publish/publish/publish_test.go
Also fixing debian 10 reference
=> Add public image labels

daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_550.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.publish.json
=> Update description to be in consistent with other images

OWNERS
=> Cleanup owners file.

daisy_workflows/image_build/windows/post_install.ps1
=> Move to GVNIC DQ for all windows images

daisy_workflows/image_build/windows/post_install.ps1
Reverts GoogleCloudPlatform/compute-image-tools#2437 to allow time for modifications to instance_setup.ps1
=> Revert "Move to GVNIC DQ for all windows images"

daisy_workflows/image_build/windows/post_install.ps1
Reverts GoogleCloudPlatform/compute-image-tools#2439
Going back to GVNIC DQ for all windows images
=> Revert "Revert "Move to GVNIC DQ for all windows images""

daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_550.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.wf.json, daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.wf.json
Already present in publish, but should be added here too.
=> Add licenses to base build workflows

daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_550.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_570.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_570.publish.json, daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.publish.json
Makes them easier to distinguish on short descriptions from the non-accelerated image types
=> Update short descriptions for Accelerator images

daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10_arm64.cfg, daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10_x86.cfg
- **remove logic that disables predictable interface naming for rhel-10**
- **change command for specifying NTP servers for rhel-10**
=> change command for specifying NTP servers for rhel-10

daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh
In COS 125, we've made the changes to patch not just guest agent. That caused the patching to guest agent failure. To bypass it, we add ignore patch list.
Error log:
https://storage.cloud.google.com/gcp-guest-daisy-bkt/daisy-image-replace-package-20250514-21:33:40-trlhv/logs/inst-worker-image-replace-package-trlhv-serial-port1.log
=> Fix patching issue on COS CIT tests

daisy_workflows/build-publish/debian/debian_13.publish.json, daisy_workflows/build-publish/debian/debian_13.wf.json, daisy_workflows/build-publish/debian/debian_13_arm64.publish.json, daisy_workflows/build-publish/debian/debian_13_arm64.wf.json, daisy_workflows/build-publish/debian/debian_13_worker.publish.json, daisy_workflows/build-publish/debian/debian_13_worker.wf.json, daisy_workflows/build-publish/debian/debian_13_worker_arm64.publish.json, daisy_workflows/build-publish/debian/debian_13_worker_arm64.wf.json, daisy_workflows/image_build/debian/debian_13_arm64.wf.json, daisy_workflows/image_build/debian/debian_13_worker.wf.json, daisy_workflows/image_build/debian/debian_13_worker_arm64.wf.json
Adding these for Concourse and Daisy usage
=> Add official Debian 13 workflows

daisy_workflows/image_build/install_package/windows/install_package.wf.json, daisy_workflows/image_build/install_package/windows/installpackage.ps1
=> Introduce workflow for deriving windows images for package testing

daisy_workflows/image_build/debian/build_fai.py
GCE_SDK conflicts with something we use, so we need to resolve this upstream. Until then, remove it.
=> Remove conflicting files

daisy_workflows/image_build/install_package/installpackage.py
=> Add support for EL10 package derived image builds
